<?php if (isset($type) && $type == 'initialize') { ?>

    <table class="table table-hover table-striped border" id="table">
        <thead>
            <tr>
                <th>S.No</th>

                <th data-placeholder="state" data-input="state">State</th>
                <th data-placeholder="city" data-input="city">City</th>
                <th data-placeholder="place name" data-input="place_name">Place Name</th>
                <th>Action</th>
            </tr>
        <?php } ?>

        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>
        <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
        <tbody>
        <?php } ?>

        <?php
        if (count($tourismList)) {
            $i = 0;
            if (isset($offset)) {
                $i = $offset;
            } foreach ($tourismList as $places) {
                ?>
                <tr>
                    <td><?php echo $i + 1; ?></td>

                    <td class="text-capitalize"><?php echo $places['state_name']; ?></td>
                    <td class="text-capitalize"><?php echo $places['city_name']; ?></td>
                    <td class="text-capitalize"><?php echo $places['place_name']; ?></td>
                    <td><div>

                            <div class="action-icon delete-place" data-id="<?php echo $places['place_price_id']; ?>" data-place="<?php echo $places['tourism_place_id']; ?>">
                                <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >

                            </div>

                        </div></td>
                </tr>
                <?php $i++;
            }
        } else { ?>
            <tr ><td class="text-center" colspan="7">No data</td></tr>
<?php } ?>
    <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>

        </tbody>
<?php } ?>
<?php if (isset($type) && $type == 'initialize') { ?>

    </table>
<?php } ?>
