<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.1 setup script
 * Date: Fri, 27 Sep 2019 13:56:34 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: susri_db [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'susri_db';
$cfg['Servers'][$i]['host'] = 'susritourmate.co21z9h2oyfd.us-east-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '0gsQ_c`b#-=v\\xC4cU2W,.0fpRt(4H@v';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>