<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Tour_Page_Spiritual,
            'mainActiveTab'=>\Application\Constants\Constants::Tour_Page

        )); ?>
    </div>
</div>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/sol.css">

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-spiritual-tour.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/spiritual-tour-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add Spiritual Tour</div>

            <div class="row">
                <div class="col-12 col-lg-10">
            <div class="row adding-form">
                <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                    <div class="row">
                        <div class="col-12"><label class="text-black-50">State</label>
                            <select  class="form-control" id="states"> <option value="">--select state--</option>
                                <?php foreach ($statesList as $states ) { ?>
                                    <option value="<?php echo $states['id']; ?>"><?php echo $states['state_name']; ?></option>
                                <?php } ?></select>
                        </div>
                        <div class="col-12"><label class="text-black-50">City</label>
                            <select  class="form-control" id="cities"><option value=""></option></select>
                        </div>
                        <div class="col-12"><label class="text-black-50">Place Name</label>
                            <select  class="form-control" id="places" name="places"><option value=""></option></select>
                        </div>
                    </div>
                </div>
            </div>
                </div>
            </div>

            <div class="mt-2">
            <div class="row">
                <div class="col-sm-12 text-left"> <button type="button" class="btn submit-btn" id="addSpiritualTour">Submit</button></div>
            </div>
            </div>
        </div>
    </div>
</div>