<?php
if ($action == 'otp'){
     // echo $message = "Please use this OTP to verify your mobile phone number for Susri Tour Tales App - ".$otp." ";
     echo $message = "Please use OTP ". $otp ." to verify your mobile phone number for Susri Tour Tales App ";
}else if($action =='TEn_Password_Reset_Otp'){
    echo $message = "Otp to reset your password for TWISTT Enabler login is ".$otp.". Please visit www.susritourtales.com";
}else if($action =='booking'){
    echo $message = $data['text'];
}else if($action =='password'){
    echo $message = $data['text'];
}
/* if ($action == 'otp'){
    echo $message = urlencode("Please use this OTP to verify your mobile Susri app ".$otp." ");
}else if($action =='forgot-password'){
    echo $message = urlencode("Dear customer, your otp to reset into Susri app  is ".$otp." ");
}else if($action =='booking'){
    echo $message = urlencode($data['text']);
}else if($action =='password'){
    echo $message = urlencode($data['text']);
} */
