
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::City_Slab_days
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">



<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-4" >
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/slab-price-list'?>"><!--<i class="fa fa-arrow-left mr-2"></i>--></a>  View/Edit City Slab Days</div>
            <div class="row adding-form1">
                <div class="col-12 col-sm-12 col-md-4"">

                <div class="row mt-3 align-items-center">
                        <div class="col-6 text-center">City Tour No Of Days For Expiry Booking Days</div>
                        <div class="col-6 text-center"><input type="text" class="form-control price slab-days" value="<?php echo $days;?>"></div>
                </div>
            </div>

    </div>
    <div class="row mt-3">
        <div class="col-8 text-center"> <button type="button" class="btn submit-btn" id="addSlabDays">Submit</button></div>
    </div>

</div>
</div>
</div>
<script src="<?php echo $this->basePath().'/js/admin/add-city-slab-days.js?v=1';?>"></script>

