<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TA_Admin
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-ta.js?v=1.1"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/ta-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add TA</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12">
                                        <label class="text-black-50">TA Name</label>
                                        <input type="text" class="form-control" id="taName"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">TA Mobile</label>
                                        <input type="text" class="form-control" id="taMobile"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">TA Email</label>
                                        <input type="text" class="form-control" id="taEmail"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Name</label>
                                        <input type="text" class="form-control" id="aeName"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Mobile</label>
                                        <input type="text" class="form-control" id="aeMobile"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Email</label>
                                        <input type="text" class="form-control" id="aeEmail"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">TA Logo</label>
                                        <div class="position-relative w-100 image-upload-wrapper">
                                            <input type="file" class="image-upload" name="image-file" multiple title=" ">
                                            <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath();?>/img/upload-img.svg"> </span>
                                        </div>
                                    </div>
                                    <div class="image-preview-wrapper pb-3"></div>
                                    <div class="col-12"><label class="text-black-50">STTSE Mobile</label>
                                        <input type="text" class="form-control" id="cMobile"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">STTSE Name</label>
                                        <input type="text" class="form-control" id="cName" readonly/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">TAC</label>
                                        <input type="text" class="form-control" id="tac"/>
                                    </div>                                 
                                </div>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="addTa">Submit</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>