<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Samples_list

        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/add-sample-audio.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/samples'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add Sample Audio</div>
            <div class="row adding-form">
                <div class="col-6">
                    <div class="col-10"><label class="text-black-50">File name</label>
                        <input type="text" class="form-control upload-file-name" >
                    </div>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">Language </label>
                        <select class="form-control file-language">
                            <option value="">--select language--</option>
                            <?php foreach ($languages as $language) { ?>
                                <option value="<?php echo $language['id']; ?>"> <?php echo $language['name']; ?> </option>
                            <?php } ?>
                        </select>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Upload Audio </label>
                        <div class="upload-div position-relative">
                            <input type="file" class="upload-file"  accept=".mp3">
                            <span class="position-absolute file_name" ></span>
                            <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath();?>/img/upload-img.svg"> </span>
                        </div>
                    </div>

                    <div class="mt-3">
                        <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="addAudio">Submit</button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>