<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::Home_banners

        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/banners.js"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="main-heading d-flex justify-content-between mb-3">
                <div>
                    Banners
                </div>
                <button class="ml-auto btn btn-dark px-4" data-toggle="modal" data-target="#add-banner">
                    <i class="fas fa-plus"></i> Add Banner
                </button>
            </div>

            <div class="row mx-n2">
                <?php foreach ($banners as $banner)  {?>
                <div class="col-12 col-lg-5 mb-4 banner-image" data-id="<?php echo $banner['banner_id']; ?>">
                    <div class="banner-imagebox border rounded" style="background: url('<?php echo $imageUrl.$banner['image_path'];?>') no-repeat center/cover">
                        <div class="deletebanner" data-toggle="modal" data-target = "#deleteBannerModal" data-id="<?php echo $banner['banner_id']; ?>">
                    <span class="deleteIcon">
                    <i class="fas fa-trash-alt"></i>
                        </span>
                        </div>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<div id="add-banner" class="modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <div class="font-20">Add Banner</div>
                <button type="button" class="close" data-dismiss="modal">&#x2715;</button>
            </div>

            <div class="model-body m-3">
                <div class="upload-image position-relative border rounded mb-2">
                    <img src="<?php echo $this->basePath(); ?>/img/cloud-backup-up-arrow.svg" id="blah"
                         class="position-absolute"/>
                    <input type="file" id="place-cover" accept="image/*">

                    <img src="" id="preview" class="h-100 w-100 d-none">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="cancel-button"
                        style="border: 1px solid #f1f1f1">Cancel
                </button>

                <button type="button" class="btn btn-default shadow-lg submit-btn" id="c2F2ZUhvd3Rv-add-banner">Add
                </button>
            </div>
        </div>

    </div>
</div>
<div id="deleteBannerModal" class="modal fade">
    <div class="modal-dialog modal-confirm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Are you sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&#x2715;</button>
            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button type="button" class="btn btn-info" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="deleteBanner" >Delete</button>
            </div>
        </div>
    </div>
</div>