<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TA_Admin
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/buy-plan.js?v=1.1"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/ta-list'?>"><i class="fa fa-arrow-left mr-2"></i></a>Buy TA</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">TAC</label>
                                        <select class="form-control" id="selTAC" name="selTAC" onchange="tacChanged(this)">
                                            <option value="0">Select TAC</option>
                                            <?php if(count($taList)){ 
                                                foreach($taList as $ta){?>
                                                    <option value="<?php echo $ta['id'] . "," . $ta['ta_cons_id'] . "," . $ta['cons_name']; ?>"><?php echo $ta['tac'] ?></option>
                                                <?php }} ?>
                                        </select>
                                    </div>
                                    <!-- <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">STTSE</label>
                                        <select class="form-control" id="selSE" name="selSE">
                                            <option value="0">Select STTSE</option>
                                            <?php /* if(count($seList)){ 
                                                foreach($seList as $se){?>
                                                    <option value="<?php echo $se['id'] ?>"><?php echo $se['name'] ?></option>
                                                <?php }} */ ?>
                                        </select>
                                    </div> -->
                                    <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">STTSE</label>
                                        <input type="text" class="form-control" id="selSE" readonly value=""/>
                                    </div>
                                    <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">Plan</label>
                                        <select class="form-control" id="selTP" name="selTP" onchange="tpChanged(this);">
                                            <option value="0">Select Plan</option>
                                            <?php if(count($tpList)){ 
                                                foreach($tpList as $tp){?>
                                                    <option value="<?php echo $tp['mtc'] . "," . $tp['cost'] . "," . $tp['id']; ?>"><?php echo $tp['plan_name'] ?></option>
                                                <?php }} ?>
                                        </select>
                                    </div>
                                    <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">MTC</label>
                                        <input type="text" class="form-control" id="tbMTC" readonly value=""/>
                                    </div>
                                    <div class="col-12 col-lg-6 pb-3">
                                        <label class="text-black-50">Cost</label>
                                        <input type="text" class="form-control" id="tbCost" readonly value=""/>
                                    </div>
                                    <input type="hidden" id="htac" value=""/>
                                    <input type="hidden" id="hpid" value=""/>
                                </div>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="buyPlan">Submit</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>