<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TAC_Performance
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-ta-cons.js"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/ta-list'?>"><i class="fa fa-arrow-left mr-2"></i></a>Edit STTSE</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12">
                                        <label class="text-black-50">Name</label>
                                        <input type="text" class="form-control" id="tacName" value="<?php echo $tacDetails['name']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Mobile</label>
                                        <input type="text" class="form-control" id="tacMobile" value="<?php echo $tacDetails['mobile']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Email</label>
                                        <input type="text" class="form-control" id="tacEmail" value="<?php echo $tacDetails['email']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Address</label>
                                        <textarea class="form-control" id="tacAdd" rows="3"><?php echo $tacDetails['address']; ?></textarea>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Bank Name</label>
                                        <input type="text" class="form-control" id="bName" value="<?php echo $tacDetails['bank_name']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">IFSC Code</label>
                                        <input type="text" class="form-control" id="ifsc" value="<?php echo $tacDetails['ifsc_code']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Bank Ac No</label>
                                        <input type="text" class="form-control" id="ban" value="<?php echo $tacDetails['bank_ac_no']; ?>"/>
                                    </div>
                                    <div class="col-12" id="state-wrapper"><label class="text-black-50">PIC</label>
                                        <input type="text" class="form-control" id="pic" value="<?php echo $tacDetails['pic']; ?>"/>
                                    </div>
                                    <div class="col-12" id="state-wrapper"><label class="text-black-50">Commission</label>
                                        <input type="text" class="form-control" id="comm" value="<?php echo $tacDetails['commission']; ?>"/>
                                    </div>  
                                </div>
                                <?php $tacId = substr($_SERVER['REQUEST_URI'], strrpos($_SERVER['REQUEST_URI'], "/")+1);  ?>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="editTac">Submit</button></div>
                                    <input type="hidden" id="htacId" value="<?php echo $tacId; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>