<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Pricing_list

        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/sol.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/vendor/bootstrap-datetimepicker.min.css"/>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/moment.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-pricing.js?v=1.3"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container pl-3 p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/pricing-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Edit Subscription Parameters </div>
            <div class="row adding-form">
                <div class="col-6">
                    <div class="col-10 mt-3"><label class="text-black-50 text-capitalize">Plan name</label>
                        <input type="text" class="form-control" id="pn" value="<?php echo $pricing['planname']; ?>"/>
                    </div>
                    <?php 
                    if(!is_null($pricing['start_date']) && $pricing['start_date'] != "0000-00-00 00:00:00")
                        $startDate = date("d-m-Y",strtotime($pricing['start_date'])); 
                    else 
                        $startDate = "";?>
                    <div class="col-10 mt-3"><label class="text-black-50">Start date</label>
                        <input type="text" class="form-control" id="sd" value="<?php echo $startDate; ?>" <?php echo $pricing['plantype'] == "0" ? "disabled": ""; //$pricing['id'] == 1 ? "disabled": ""; ?>/>
                    </div>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">App Text</label>
                        <textarea class="form-control" id="atxt"><?php echo $pricing['app_text']; ?></textarea>
                    </div>
                    <?php if($pricing['plantype'] == "0"){ //if($pricing['id'] == "1"){?>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">Subscription Validity</label>
                        <input type="text" class="form-control" id="sv"  value="<?php echo $pricing['subscription_validity']; ?>"/>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">First Renewal Discount</label>
                        <input type="text" class="form-control" id="frd" value="<?php echo $pricing['first_rdp']; ?>"/>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Complimentary Passwords</label>
                        <input type="text" class="form-control price" id="cp" value="<?php echo $pricing['no_of_comp_pwds']; ?>" disabled/>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Max Tales</label>
                        <input type="text" class="form-control price" id="md" value="<?php echo $pricing['maxdownloads']; ?>" />
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Performance Criterion Passwords</label>
                        <input type="text" class="form-control price" id="np" value="<?php echo $pricing['npc_passwords']; ?>" />
                    </div>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">GST</label>
                        <input type="text" class="form-control price" id="gst" value="<?php echo $pricing['GST']; ?>" />
                    </div>
                    <?php } ?>
                </div>
                <div class="col-6"> 
                    <div class="col-10 mt-3"><label class="text-black-50 text-capitalize">Price</label>
                        <input type="text" class="form-control" id="p" value="<?php echo $pricing['price']; ?>"/>
                    </div>
                    <div class="col-10 mt-3">
                    <?php 
                        if(!is_null($pricing['end_date']) && $pricing['end_date'] != "0000-00-00 00:00:00")
                            $endDate = date("d-m-Y",strtotime($pricing['end_date'])); 
                        else 
                            $endDate = ""; 
                    ?>
                        <label class="text-black-50">End date</label>
                        <input type="text" class="form-control" id="ed"  value="<?php  echo $endDate; ?>" <?php echo $pricing['plantype'] == "0" ? "disabled": ""; //$pricing['id'] == 1 ? "disabled": ""; ?>/>
                    </div>
                    <?php if($pricing['plantype'] == "0"){ 
                        if($pricing['id'] == "1"){?>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">Web Text</label>
                        <textarea class="form-control" id="wtxt"><?php echo $pricing['web_text']; ?></textarea>
                    </div>
                    <?php } ?>
                    <div class="col-10 mt-3">
                        <label class="text-black-50">Sponsor Password Validity</label>
                        <input type="text" class="form-control" id="spv"  value="<?php echo $pricing['sponsor_pwd_validity']; ?>"/>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Second Renewal Discount</label>
                        <input type="text" class="form-control" id="srd" value="<?php echo $pricing['second_rdp']; ?>"/>
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Sponsor Complimentary Passwords</label>
                        <input type="text" class="form-control price" id="scp" disabled value="<?php echo $pricing['sponsor_comp_pwds']; ?>" />
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Time Frame</label>
                        <input type="text" class="form-control price" id="tf" value="<?php echo $pricing['no_of_days']; ?>" />
                    </div>

                    <div class="col-10 mt-3">
                        <label class="text-black-50">Performance Criterion Days</label>
                        <input type="text" class="form-control price" id="nd" value="<?php echo $pricing['npc_days']; ?>" />
                    </div>
                    <?php } ?>
                </div>
            </div>
            <input type="hidden" id="pricing_id" value="<?php echo $pricing['id']; ?>">

            <div class="mt-3">
                <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="updatePricng">Submit</button></div>
            </div>
        </div>
    </div>
</div>