<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TA_Admin
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-ta.js?v=1.1"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header");?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/ta-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Edit TA</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                <div class="col-12">
                                        <label class="text-black-50">TA Name</label>
                                        <input type="text" class="form-control" id="taName" value="<?php echo $taDetails[0]['ta_name']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">TA Mobile</label>
                                        <input type="text" class="form-control" id="taMobile" value="<?php echo $taDetails[0]['ta_mobile']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">TA Email</label>
                                        <input type="text" class="form-control" id="taEmail" value="<?php echo $taDetails[0]['ta_email']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Name</label>
                                        <input type="text" class="form-control" id="aeName" value="<?php echo $taDetails[0]['ae_name']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Mobile</label>
                                        <input type="text" class="form-control" id="aeMobile" value="<?php echo $taDetails[0]['ae_mobile']; ?>"/>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">AE Email</label>
                                        <input type="text" class="form-control" id="aeEmail" value="<?php echo $taDetails[0]['ae_email']; ?>"/>
                                    </div>                                    
                                    <div class="col-12">
                                        <label class="text-black-50">TA Logo</label>
                                        <div class="position-relative w-100 image-upload-wrapper">
                                            <input type="file" class="image-upload" name="image-file" title=" ">
                                            <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath();?>/img/upload-img.svg"> </span>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="image-preview-wrapper row">
                                            <?php foreach($imageFiles as $image) { ?>
                                                <div class="col-sm-4 mt-2 position-relative image-preview overflow-hidden" data-id="<?php echo $image['tourism_file_id']; ?>">
                                                    <img src="<?php echo $imageUrl.$image['file_path']; ?>" style="width: 100%;height: 100%">
                                                    <span class="bg-white circle close-icon" data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1" >
                                                            <i class="fas fa-times position-absolute " data-id="<?php echo $image['tourism_file_id']; ?>"  data-edit="1"></i></span>
                                                </div>
                                            <?php } ?>
                                        </div>

                                    </div>
                                    <!-- <div class="col-12">                            
                                        <div class="image-preview-wrapper row">
                                            <?php //foreach($imageFiles as $image) { ?>
                                                <div class="col-sm-4 mt-2 position-relative image-preview overflow-hidden" data-id="<?php echo $taDetails['tourism_file_id']; ?>">
                                                    <img src="<?php echo $imageUrl.$taDetails['file_path']; ?>" style="width: 100%;height: 100%">
                                                    <span class="bg-white circle close-icon" data-id="<?php echo $taDetails['tourism_file_id']; ?>" data-edit="1">
                                                        <i class="fas fa-times position-absolute " data-id="<?php echo $taDetails['tourism_file_id']; ?>"  data-edit="1"></i></span>
                                                </div>
                                            <?php //} ?>
                                        </div>
                                    </div> -->
                                    <div class="col-12"><label class="text-black-50">STTSE Mobile</label>
                                        <input type="text" class="form-control" id="cMobile" value="<?php echo $taDetails[0]['cons_mobile']; ?>" readonly/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">STTSE Name</label>
                                        <input type="text" class="form-control" id="cName" value="<?php echo $taDetails[0]['cons_name']; ?>" readonly/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">TAC</label>
                                        <input type="text" class="form-control" id="tac" value="<?php echo $taDetails[0]['tac']; ?>"/>
                                    </div>  
                                </div>
                                <?php $taId = substr($_SERVER['REQUEST_URI'], strrpos($_SERVER['REQUEST_URI'], "/")+1);  ?>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="editTa">Submit</button></div>
                                    <input type="hidden" id="htaid" value="<?php echo $taId; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>