<?php
if (isset($audioFiles) && count($audioFiles))
{
    $rowNumber = 1;
    foreach ($audioFiles as $audio) {
        ?>
        <div class="file-uploads row" data-id="<?php echo $rowNumber ?>" data-edit="<?php echo $audio['tourism_file_id']; ?>">
            <div class="col-12"><label class="text-black-50">File name</label>
                <input type="text" class="form-control upload-file-name" data-id="<?php echo $rowNumber ?>" value="<?php echo $audio['file_name']; ?>">

            </div>
            <div class="col-12"><label class="text-black-50">Language </label>

                    <select class="form-control file-language mr-3" data-id="<?php echo $rowNumber ?>">
                        <option value="">--select language--</option>
                        <?php foreach ($languages as $language) { ?>
                            <option value="<?php echo $language['id']; ?>" <?php echo ($language['id'] == $audio['file_language_type'] ? "selected" : "") ?>><?php echo $language['name']; ?></option>
                        <?php } ?>
                    </select>
            </div>
            <div class="col-12">
                <label class="text-black-50">Upload </label>
                <div class="d-flex align-items-center">
                <div class="upload-div position-relative" data-id="<?php echo $rowNumber ?>">
                    <input type="file" class="upload-file" data-id="<?php echo $rowNumber ?>" accept=".mp3">
                    <span class="position-absolute file_name" data-id="<?php echo $rowNumber ?>">
                        <?php
                        $file = explode('/', $audio['file_path']);
                        echo $file[count($file) - 1];
                        ?>
                    </span>
                    <span class="position-absolute upload_btn">
                        <img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg">
                    </span>
                </div>
                    <div class="services-control mb-3" data-id="<?php echo $rowNumber ?>">
                        <div class="controls remove-control rounded-circle d-flex justify-content-center align-items-center bg-000" data-id="<?php echo $rowNumber ?>">
                            <img src="<?php echo $this->basePath(); ?>/img/minus.svg" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php
        $rowNumber++;
    }
 } else {
    ?>
    <div class="file-uploads" data-id="<?php echo $rowNumber ?>">
        <div class="row">
            <div class="col-12"><label class="text-black-50">File name</label>
                <input type="text" class="form-control upload-file-name" data-id="<?php echo $rowNumber ?>">

            </div>
            <div class="col-12">
                <label class="text-black-50">Language </label>

                    <select class="form-control file-language mr-3" data-id="<?php echo $rowNumber ?>">
                        <option value="">--select language--</option>
                        <?php foreach ($languages as $language) { ?>
                            <option value="<?php echo $language['id']; ?>">
                                <?php echo $language['name']; ?></option>
                        <?php } ?>
                    </select>


            </div>

            <div class="col-12"><label class="text-black-50">Upload </label>
                <div class="d-flex align-items-center">
                <div class="upload-div position-relative" data-id="<?php echo $rowNumber ?>">
                    <input type="file" class="upload-file" data-id="<?php echo $rowNumber ?>" accept=".mp3">
                    <div class="file_name" data-id="<?php echo $rowNumber ?>"></div>
                    <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                </div>
                    <div class="services-control mb-3" data-id="<?php echo $rowNumber ?>">
                        <div class="controls remove-control rounded-circle d-flex justify-content-center align-items-center bg-000" data-id="<?php echo $rowNumber ?>">
                            <img src="<?php echo $this->basePath(); ?>/img/minus.svg" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php } ?>