
<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="state" data-input="state">state
        </th>
        <th>Action</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($stateList))  {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($stateList as $state) { ?>
            <tr>
                <td><?php echo $i+1; ?></td>
                <td><?php echo $state['state_name']; ?></td>
                <td><div class="d-flex">
                        <a class="action-icon " href="<?php echo $this->basePath().'/a_dMin/edit-state/'.base64_encode('tourismPlaceId='.$state['id'])?>" >
                            <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid">
                        </a>
                        <div class="action-icon delete-place" data-id="<?php echo $state['id']; ?>">
                            <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >
                        </div>
                    </div></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="7">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php } ?>
