
<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="date" data-input="due_date">Date</th>
        <th data-placeholder="due amount" data-input="due_amount">Due Amount</th>
        <th data-placeholder="promoter" data-input="promoter_mobile">Promoter</th>
        <th data-placeholder="sponsor" data-input="sponsor_mobile">Sponsor</th>
        <th data-placeholder="bank a/c" data-input="account_no">Bank a/c</th>
        <th data-placeholder="ifsc code" data-input="ifsc_code">IFSC code</th>
        <th data-placeholder="paid date" data-input="paid_date">Paid Date</th>
        <th data-placeholder="paid amount" data-input="paid_amount">Paid Amount</th>
        <th data-placeholder="trans. ref" data-input="trans_ref">Trans. Ref</th>
        <th>Pay</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody class="pplist">
    <?php } ?>

    <?php if(count($promotersPayments))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }
        
        foreach ($promotersPayments as $payment) { ?>
            <?php $bgClr = "style='background-color:LightGray;'";
            if($payment['status'] == \Admin\Model\PromoterPayments::status_due){
                $bgClr = "style='background-color:PaleGreen;'";
            if($payment['redeem'] == "1")
                $bgClr = "style='background-color:Pink;'";
            } ?>
            <tr class="position-relative" <?php echo $bgClr; ?>>
                <td><?php echo $i+1; ?></td>
                <td><?php echo date("d-m-Y",strtotime($payment['due_date'])); ?></td>
                <td><?php echo $payment['due_amount']; ?></td>
                <td><?php echo $payment['ref_by'] . "<br>" . $payment['ref_mobile']; ?></td>
                <td id="spo<?php echo $payment['id']; ?>"><?php echo $payment['user_name'] . "<br>" . $payment['mobile']; ?></td>
                <td><?php echo $payment['bank_ac_no']; ?></td>
                <td><?php echo $payment['ifsc_code']; ?></td>
                <td><?php echo $payment['paid_date']; ?></td>
                <td><?php echo $payment['paid_amount']; ?></td>
                <td><?php echo $payment['trans_ref']; ?></td>
                <td><?php if($payment['status'] == \Admin\Model\PromoterPayments::status_due){?>
                    <div class="d-flex">
                        <div class="action-icon pay" data-id="<?php echo $payment['id']; ?>">
                            <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid" >
                        </div>
                    </div>
                    <?php } ?>
                </td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="11">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>
