<?php if(isset($type) && $type =='initialize') { ?>
    <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="Date Of registration" data-input="date_of_registration">Date Of registration</th>
        <th data-placeholder="Mobile Number" data-input="mobile">Mobile Number</th>
        <th data-placeholder="Activation" data-input="activation_date">Activation</th>
        <th data-placeholder="Duration" data-input="duartion">Duration</th>
        <th data-placeholder="tour Category" data-input="tour_type" data-type="select"  data-value='[{"value":"1","text":"india tour"},{"value":"2","text":"world tour"},{"value":"3","text":"city tour"},{"value":"4","text":"spiritual tour"},{"value":"5","text":"package"}]'>tour Category</th>
        <th data-placeholder="Places" data-input="place_name">Places</th>
        <th>Actions</th>
    </tr>
<?php } ?>

<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
<?php } ?>
<?php if(count($userList))
{
    $i=0;
    if(isset($offset))
    {
        $i=$offset;
    }

    foreach ($userList as $user) { ?>
        <tr class="position-relative">
            <td><?php echo $i+1; ?></td>
            <td ><?php echo date("d-m-Y",strtotime($user['created_at'])); ?></td>
            <td ><?php echo $user['mobile']; ?></td>
            <td class="text-capitalize "><?php echo date("d-m-Y",strtotime($user['tour_date'])); ?></td>
            <td class=""><?php echo isset($user['no_of_days'])?$user['no_of_days']:0; ?> Days</td>
            <td class="text-capitalize "><?php echo \Admin\Model\PlacePrices::tour_type[$user['tour_type']]; ?></td>
            <td class="text-capitalize "><?php echo $user['place_name']; ?></td>
            <td><div class="d-flex">
                    <a class="action-icon d-none" href="<?php echo $this->basePath().'/a_dMin/edit-country/'.base64_encode('tourismSpecialId='.$user['booking_id'])?>" >
                        <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid">
                    </a>
                    <div class="action-icon delete-place" data-id="<?php echo $user['booking_id']; ?>">
                        <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >
                    </div>
                </div></td>
        </tr>
        <?php $i++; } } else { ?>
    <tr ><td class="text-center" colspan="9">No data</td></tr>
<?php  } ?>
<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
<?php } ?>
<?php if(isset($type) && $type =='initialize') {?>

    </table>
    </div>
<?php } ?>