<?php if(isset($type) && $type =='initialize') { ?>
    <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="bookingListtable">
    <thead>
    <tr>
        <th>S.no</th>
       <!-- <th data-placeholder="booking id" data-input="booking_id">booking id</th>
        <th data-placeholder="booking data" data-input="booking_date">booking Date</th>
        <th data-placeholder="tour type" data-input="tour_type">tour type</th>
        <th data-placeholder="amount" data-input="amount">amount</th>
        <th data-placeholder="booked by" data-input="user">booked by</th>
        <th data-placeholder="activation date" data-input="activation_date">Activation Date</th>
        <th data-placeholder="expiry date" data-input="expiry_date">Expiry Date</th>
        <th data-placeholder="Members Count" data-input="members_count">Members Count</th>-->
        <th data-placeholder="booking id" data-input="booking_id">booking id</th>
        <th data-placeholder="booking date" data-input="booking_date">booking Date</th>
        <th data-placeholder="tour type" data-type="select" data-input="tour_type" data-value='[{"value":"1","text":"india tour"},{"value":"2","text":"world tour"},{"value":"3","text":"city tour"},{"value":"4","text":"spiritual tour"},{"value":"5","text":"package"}]'>Tour Type</th>
        <th data-placeholder="amount" data-input="amount">amount</th>
        <th data-placeholder="booked by" data-input="user">booked by</th>
        <th data-placeholder="mobile Number" data-input="mobile">Mobile Number</th>
        <th data-placeholder="Activation From" data-input="activation_date"> Password Validity Start Date</th>
        <th data-placeholder="Activation Till" data-input="expiry_date"> Password Validity End Date</th>
        <th data-placeholder="Users Count" data-input="members_count">Users Count</th>

    </tr>
<?php } ?>

<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
<?php } ?>
<?php if(count($bookingList)){
    $i=0;
    if(isset($offset))
    {
        $i=$offset;
    }

    foreach ($bookingList as $booking)
    { ?>
        <tr class="position-relative" data-id="<?php echo base64_encode("bookingDetials=".$booking['booking_id']); ?>">
            <td class="text-center"><?php echo $i+1; ?></td>
            <td class="text-center"><?php echo $booking['booking_id']; ?></td>
            <td class="text-center"><?php echo date("d-m-Y",strtotime($booking['created_at'])); ?></td>
            <td class="text-capitalize text-center"><?php echo \Admin\Model\PlacePrices::tour_type[$booking['tour_type']]; ?></td>
            <td class="text-center"><?php echo isset($booking['price'])?'₹'.$booking['price']:'₹0'; ?></td>
            <td class="text-center" data="<?php echo $booking['company_name']; ?>"><?php
                   /* if($booking['role']==\Admin\Model\User::Tour_Operator_role){
                       echo $booking['contact_person'].'('. $booking['company_name'].')';

                   }else if($booking['role']==\Admin\Model\User::Individual_role)
                   {
                       echo $booking['user_name'];
                   }else if($booking['role']==\Admin\Model\User::Tour_coordinator_role)
                   {
                       echo $booking['coordinator_name'].'('.  $booking['coordinator_company_name'].')';
                   } */
                   echo $booking['user_name'];
                 ?></td>
            <td class="text-center"><?php echo $booking['mobile']; ?></td>
            <td class="text-center"><?php echo date("d-m-Y",strtotime($booking['tour_date'])); ?></td>
            <td class="text-center"><?php echo date("d-m-Y",strtotime($booking['expiry_date'])); ?></td>
            <td class="text-center"><?php echo $booking['no_of_users']; ?></td>
        </tr>
        <?php $i++;
    }
} else { ?>
    <tr ><td class="text-center" colspan="9">No data</td></tr>
<?php  } ?>
<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
<?php } ?>
<?php if(isset($type) && $type =='initialize') {?>

    </table>
    </div>
<?php } ?>