
<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="promoter name" data-input="user_name">promoter name</th>
        <th data-placeholder="mobile" data-input="mobile">mobile</th>
        <th data-placeholder="successful sponsors" data-input="sponsors_successful">successful sponsors</th>
        <th data-placeholder="terminated sponsors" data-input="sponsors_terminated">terminated sponsors</th>
        <th data-placeholder="active sponsors" data-input="sponsors_active">active sponsors</th>
        <th data-placeholder="total passwords" data-input="total_passwords">total passwords</th>
        <th data-placeholder="amount due" data-input="amount_due">amount due</th>
        <th data-placeholder="amount paid" data-input="amount_paid">amount paid</th>
        <th>terminate promoter</th>
        <th data-placeholder="expiry date" data-input="subscription_end_date">expiry date</th>
        <th data-placeholder="state city" data_input="state_city">state / city</th>
        <th data-placeholder="perm address" data_input="permanent_addr">permanent address</th>
        <th data-placeholder="bank name" data_input="bank_name">bank name</th>
        <th data-placeholder="ifsc code" data_input="ifsc_code">ifsc code</th>
        <th data-placeholder="bank ac no" data_input="bank_ac_no">bank_ac_no</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($promotersList))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($promotersList as $promoter) { 
            $fontColor = "";
            if($promoter['is_promoter'] == \Admin\Model\User::Is_terminated_Promoter)
                $fontColor = "text-danger";?>
            <tr class="position-relative <?php echo $fontColor; ?>" data-id="<?php echo base64_encode("promoterid=".$promoter['user_id']); ?>">
                <td><?php echo $i+1; ?></td>
                <td><div id="div_<?php echo $promoter['user_id']; ?>"><?php echo $promoter['user_name']; ?></div></td>
                <td class="text-center"><?php echo "+".$promoter['mobile_country_code'].' '.$promoter['mobile']; ?></td>
                <td class="text-center"><?php echo $promoter['sponsors_successful']; ?></td>
                <td class="text-center"><?php echo $promoter['sponsors_terminated']; ?></td>
                <td class="text-center"><?php echo $promoter['sponsors_active']; ?></td>
                <td class="text-center"><?php echo $promoter['total_passwords']; ?></td>
                <td class="text-center"><?php echo $promoter['amount_due']; ?></td>
                <td class="text-center"><?php echo $promoter['amount_paid']; ?></td>
                <td class="text-center">
                    <input type="checkbox" id="tcb_<?php echo $promoter['user_id']; ?>" name="tcb_<?php echo $promoter['user_id']; ?>" value="<?php echo $promoter['user_id']; ?>" <?php echo $promoter['is_promoter'] == \Admin\Model\User::Is_terminated_Promoter ? "checked disabled" : "" ;?> onclick="event.stopPropagation();">
                    <?php //echo $promoter['is_promoter'];?>
                </td>
                <td class="text-center">
                    <?php 
                    if(!is_null($promoter['subscription_end_date']) && $promoter['subscription_end_date'] != "0000-00-00")
                        echo date("d-m-Y",strtotime($promoter['subscription_end_date'])); 
                    else 
                        echo "NA";?>
                </td>
                <td class="text-center"><?php echo $promoter['state_city']; ?></td>
                <td class="text-center"><?php echo $promoter['permanent_addr']; ?></td>
                <td class="text-center"><?php echo $promoter['bank_name']; ?></td>
                <td class="text-center"><?php echo $promoter['ifsc_code']; ?></td>
                <td class="text-center"><?php echo $promoter['bank_ac_no']; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="11">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>
