<?php if(isset($type) && $type =='initialize') { ?>
<style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="Name" data-input="name" class="text-center">Name</th>
        <th data-placeholder="Mobile" data-input="mobile" class="text-center">Mobile</th>
        <th data-placeholder="Email" data-input="email" class="text-center">Email</th>
        <th data-placeholder="Address" data-input="address" class="text-center">Address</th>
        <th data-placeholder="Bank name" data-input="bank_name" class="text-center">Bank name</th>
        <th data-placeholder="IFSC Code" data-input="ifsc_code" class="text-center">IFSC Code</th>
        <th data-placeholder="Bank Ac No" data-input="bank_ac_no" class="text-center">Bank Ac No</th>
        <th data-placeholder="PIC" data-input="pic" class="text-center">PIC</th>
        <th data-placeholder="Commission" data-input="commission" class="text-center">Commission</th>
        <th>Action</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($taCons))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($taCons as $tac) { ?>
            <tr class="position-relative" data-id="<?php echo base64_encode("pid=".$tac['id']);?>">
                <td><?php echo $i+1; ?></td>
                <td class="text-center"><?php echo $tac['name']; ?></td>
                <td class="text-center"><?php echo $tac['mobile']; ?></td>
                <td class="text-center"><?php echo $tac['email']; ?></td>
                <td class="text-center"><?php echo $tac['address']; ?></td>
                <td class="text-center"><?php echo $tac['bank_name']; ?></td>
                <td class="text-center"><?php echo $tac['ifsc_code']; ?></td>
                <td class="text-center"><?php echo $tac['bank_ac_no']; ?></td>
                <td class="text-center"><?php echo $tac['pic']; ?></td>
                <td class="text-center"><?php echo $tac['commission']; ?></td>
                <td><div class="d-flex">
                    <a class="action-icon" href="<?php echo $this->basePath().'/a_dMin/edit-ta-cons/'.base64_encode('tacId='.$tac['id'])?>" >
                        <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid">
                    </a>
                    <div class="action-icon delete-tac" data-id="<?php echo $tac['id']; ?>">
                        <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >
                    </div>
                </div></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="15">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>