<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="tour type" data-type="select" data-input="tour_type" data-value='[{"value":"1","text":"india tour"},{"value":"2","text":"world tour"},{"value":"3","text":"city tour"},{"value":"4","text":"spiritual tour"},{"value":"5","text":"festival tour"}]'>Tour Type</th>
        <th data-placeholder="month year">month year</th>
        <th data-placeholder="country" data-input="country">country</th>
        <th data-placeholder="state" data-input="state">state</th>
        <th data-placeholder="city" data-input="city">city</th>
        <th data-placeholder="place" data-input="place">place</th>
        <th data-placeholder="languages" data-input="languages">languages</th>
        <th>Action</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) { ?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>


    <?php if(count($upcomingList))  {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($upcomingList as $up) { 
            $udLangs = explode(',', $up['languages']);
            $langlist = "";
            foreach ($languagesList as $lang){
                $ll = in_array($lang['id'], $udLangs) ? $lang['name'] : "";
                if($ll != "")
                    if($langlist == "")
                        $langlist = $ll;
                    else
                        $langlist = $langlist .", ". $ll;
            }
            ?>
            <tr>
                <td><?php echo $i+1; ?></td>
                <td class="text-capitalize"><?php echo \Admin\Model\PlacePrices::tour_type[$up['tour_type']]; ?></td>
                <td><?php echo $up['month_year']; ?></td>
                <td><?php echo $up['country']; ?></td>
                <td><?php echo $up['state']; ?></td>
                <td><?php echo $up['city']; ?></td>
                <td><?php echo $up['place']; ?></td>
                <td><?php echo $langlist; /* $up['languages'] */ ?></td>
                <td><div class="d-flex">
                        <a class="action-icon" href="<?php echo $this->basePath().'/a_dMin/edit-upcoming/'.base64_encode('upcomingId='.$up['id'])?>" >
                            <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid">
                        </a>
                        <div class="action-icon delete-upcoming" data-id="<?php echo $up['id']; ?>">
                            <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >
                        </div>
                    </div></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="9">No data</td></tr>
    <?php  } ?>
<?php if(isset($type) && ($type =='initialize' || $type=="search") ) { ?>

    </tbody>
<?php } ?>
<?php if(isset($type) && $type =='initialize') { ?>

    </table>
<?php } ?>