
<?php if(isset($type) && $type =='initialize') { ?>
<style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="plan name" data-input="planname" class="calign">plan name</th>
        <th data-placeholder="price" data-input="price" class="calign">price</th>
        <th data-placeholder="sub validity" data-input="subscription_validity">sub validity</th>
        <th data-placeholder="pwd sub validity" data-input="pwd_subscription_validity">pwd sub validity</th>
        <th data-placeholder="start date" data-input="start_date" class="calign">start date</th>
        <th data-placeholder="end date" data-input="end_date" class="calign">end date</th>
        <th data-placeholder="sponsor pwd val" data-input="sponsor_pwd_validity">sponsor pwd val</th>
        <th data-placeholder="1st Renew Disc" data-input="first_rdp">1st Renew Disc</th>
        <th data-placeholder="2nd Renew Disc" data-input="second_rdp">2nd Renew Disc</th>
        <th data-placeholder="compl pwds" data-input="no_of_comp_pwds">compl pwds</th>
        <th data-placeholder="spsr compl pwds" data-input="sponsor_comp_pwds">spsr compl pwds</th>
        <th data-placeholder="Max Tale Limit" data-input="maxdownloads">Max Tale Limit</th>    
        <th data-placeholder="Time Frame" data-input="no_of_days">time frame</th>
        <th data-placeholder="perf pwds" data-input="npc_passwords"  class="calign">perf pwds</th>
        <th data-placeholder="perf pd" data-input="npc_days"  class="calign">perf pd</th>
        <th data-placeholder="GST" data-input="GST" class="calign">GST</th>
        <th data-placeholder="App Text" data-input="app_text">App Text</th>
        <th data-placeholder="Web Text" data-input="web_text">Web Text</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($pricingList))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($pricingList as $pricing) { ?>
            <tr class="position-relative" data-id="<?php echo base64_encode("pid=".$pricing['id']);?>">
                <td><?php echo $i+1; ?></td>
                <td class="text-center"><?php echo $pricing['planname']; ?></td>
                <td class="text-center"><?php echo $pricing['price']; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['subscription_validity'] : "NA"; //$pricing['id'] == "1" ? $pricing['subscription_validity'] : "NA" ; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['pwd_subscription_validity'] : "NA"; ?></td>
                <td class="text-center position-relative">
                    <?php 
                    if(!is_null($pricing['start_date']) && $pricing['start_date'] != "0000-00-00 00:00:00")
                        $startDate = date("d-m-Y",strtotime($pricing['start_date'])); 
                    else 
                        $startDate = "NA";
                    echo $startDate; ?>
                </td>
                <td class="text-center position-relative">
                    <?php 
                        if(!is_null($pricing['end_date']) && $pricing['end_date'] != "0000-00-00 00:00:00")
                            $endDate = date("d-m-Y",strtotime($pricing['end_date'])); 
                        else 
                            $endDate = "NA";
                        echo $endDate;   
                    ?>
                </td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['sponsor_pwd_validity'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['first_rdp'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['second_rdp'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['no_of_comp_pwds'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['sponsor_comp_pwds'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['maxdownloads'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['no_of_days'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['npc_passwords'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['npc_days'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['plantype'] == "0" ? $pricing['GST'] : "NA"; ?></td>
                <td><?php echo $pricing['app_text']; ?></td>
                <td><?php echo $pricing['id'] == "1" ? $pricing['web_text'] : "NA"; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="16">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>
<?php 
/* 
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['sponsor_pwd_validity'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['first_rdp'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['second_rdp'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['no_of_comp_pwds'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['sponsor_comp_pwds'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['maxdownloads'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['no_of_days'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['npc_passwords'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['npc_days'] : "NA"; ?></td>
                <td class="text-center"><?php echo $pricing['id'] == "1" ? $pricing['GST'] : "NA"; ?></td>
                <td><?php echo $pricing['app_text']; //echo $pricing['id'] == "1" ? $pricing['app_text'] : "NA"; ?></td>
                <td><?php echo $pricing['id'] == "1" ? $pricing['web_text'] : "NA"; ?></td>  */

?>