
<?php if(isset($type) && $type =='initialize') { ?>
<style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="ta name" data-input="ta_name" class="text-center">TA</th>
        <th data-placeholder="upc" data-input="upc" class="text-center">UPC</th>
        <th data-placeholder="dop" data-input="dop" class="text-center">dop</th>
        <th data-placeholder="doe" data-input="doe" class="text-center">doe</th>
        <th data-placeholder="se" data-input="name" class="text-center">SE</th>
        <th data-placeholder="plan cost" data-input="ta_plan_cost" class="text-center">Plan Cost</th>
        <th data-placeholder="mtc balance" data-input="tourists_count" class="text-center">MTC Balance</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($taPurchases))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($taPurchases as $p) { ?>
            <tr class="position-relative">
                <td><?php echo $i+1; ?></td>
                <td class="text-center"><?php echo $p['ta_name']; ?></td>
                <td class="text-center"><?php echo $p['upc']; ?></td>
                <td class="text-center"><?php echo date('d-m-Y', strtotime($p['dop'])); ?></td>
                <td class="text-center"><?php echo date('d-m-Y', strtotime($p['doe'])); ?></td>
                <td class="text-center"><?php echo $p['name']; ?></td>
                <td class="text-center"><?php echo "Rs ".$p['ta_plan_cost']. "/-"; ?></td>
                <td class="text-center"><?php echo $p['tourists_count']; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="7">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>