
<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="Language" data-input="language">Language
        </th>
        <th > Audio File </th>
        <th>Action</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($sampleAudioList))  {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($sampleAudioList as $audio) { ?>
            <tr>
                <td><?php echo $i+1; ?></td>
                <td><?php echo $audio['language_name']; ?></td>
                <td>
                <div class="d-flex align-items-center">
                   <!-- <img class="img-fluid play-icon" src="<?php /*echo $this->basePath().'/img/audio.svg'*/?>"/>-->
                    <audio controls controlsList="nodownload">
                        <source src="<?php echo $fileUrl.$audio['file_path']; ?>" >

                    </audio>
                    <?php echo $audio['file_name']; ?>
                </div>
                </td>
                <td><div class="d-flex">
                        <a class="action-icon d-none" href="<?php echo $this->basePath().'/a_dMin/edit-country/'.base64_encode('tourismAudioId='.$audio['tourism_file_id'])?>" >
                            <img src="<?php echo $this->basePath();?>/img/edit.png" class="img-fluid">
                        </a>
                        <div class="action-icon delete-place" data-id="<?php echo $audio['tourism_file_id']; ?>">
                            <img src="<?php echo $this->basePath();?>/img/delete.png" class="img-fluid" >
                        </div>
                    </div></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="7">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php } ?>
