<style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style>
<div class="row">
    <div class="col-md-6">
        <div class="table-responsive"><div class="main-heading pb-3">Indian parameters</div>
            <table class="table table-bordered table-hover table-striped" id="extTable">
                <tbody>
                    <?php if(count($parametersList))
                    { $i=0; ?>
                            <tr>
                                <th>S.no</th>
                                <th>Parameter</th>
                                <th>Value</th>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Regular Base Price for Annual Subscription (Rs)</td>
                                <td><?php echo $parametersList[0]['annual_price']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer Price for Annual Subscription (Rs)</td>
                                <td><?php echo $parametersList[0]['offer_price']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer Start Date</td>
                                <td>
                                    <?php 
                                        if(!is_null($parametersList[0]['offer_start_date']) && $parametersList[0]['offer_start_date'] != "0000-00-00 00:00:00")
                                            $startDate = date("d-m-Y",strtotime($parametersList[0]['offer_start_date'])); 
                                        else 
                                            $startDate = "NA";
                                        echo $startDate; ?>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer End Date</td>
                                <td>
                                    <?php 
                                        if(!is_null($parametersList[0]['offer_end_date']) && $parametersList[0]['offer_end_date'] != "0000-00-00 00:00:00")
                                            $endDate = date("d-m-Y",strtotime($parametersList[0]['offer_end_date'])); 
                                        else 
                                            $endDate = "NA";
                                        echo $endDate; ?>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Subscription Validity Period (days)</td>
                                <td><?php echo $parametersList[0]['subscription_validity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Max. tales that can be available on mobile at any given time</td>
                                <td><?php echo $parametersList[0]['maxdownloads']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Period after which the downloaded tale/s get auto-deleted (days)</td> 
                                <td><?php echo $parametersList[0]['no_of_days']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Max. passwords a Sponsor can buy in one transaaction</td>
                                <td><?php echo $parametersList[0]['maxquantity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Min. number of passwords to be purchased by the Sponsor to get bonus passwords</td>
                                <td><?php echo $parametersList[0]['sponsor_bonus_min']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>No. of bonus passwords, a Sponsor can get</td>
                                <td><?php echo $parametersList[0]['sponsor_comp_pwds']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Validity period of password from the date of purchase (days)</td>
                                <td><?php echo $parametersList[0]['sponsor_pwd_validity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Sponsor Performance Criterion: Min. passwords to be purchased by Sponsor in 'specified number' of days in order to maintain his discount status</td>
                                <td><?php echo $parametersList[0]['npc_passwords']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Sponsor Performance Criterion: Min. specified period within which Sponsor has to purchase the above no. of passwords (days)</td>
                                <td><?php echo $parametersList[0]['npc_days']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>First year discount for renewal</td>
                                <td><?php echo $parametersList[0]['first_rdp']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Second year onwards - discount for renewal</td>
                                <td><?php echo $parametersList[0]['second_rdp']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>GST</td>
                                <td><?php echo $parametersList[0]['GST']; ?></td>
                            </tr>
                            <?php } else { ?>
                        <tr ><td class="text-center" colspan="16">No data</td></tr>
                    <?php  } ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-md-6">
        <div class="table-responsive"><div class="main-heading  pb-3">Foriegn parameters</div>
            <table class="table table-bordered table-hover table-striped" id="extTable">
                <tbody>
                    <?php if(count($parametersList))
                    { $i=0; ?>
                            <tr>
                                <th>S.no</th>
                                <th>Parameter</th>
                                <th>Value</th>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Regular Base Price for Annual Subscription (USD)</td>
                                <td><?php echo $parametersList[1]['annual_price']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer Price for Annual Subscription (USD)</td>
                                <td><?php echo $parametersList[1]['offer_price']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer Start Date</td>
                                <td>
                                    <?php 
                                        if(!is_null($parametersList[1]['offer_start_date']) && $parametersList[1]['offer_start_date'] != "0000-00-00 00:00:00")
                                            $startDate = date("d-m-Y",strtotime($parametersList[1]['offer_start_date'])); 
                                        else 
                                            $startDate = "NA";
                                        echo $startDate; ?>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Current Offer End Date</td>
                                <td>
                                    <?php 
                                        if(!is_null($parametersList[1]['offer_end_date']) && $parametersList[1]['offer_end_date'] != "0000-00-00 00:00:00")
                                            $endDate = date("d-m-Y",strtotime($parametersList[1]['offer_end_date'])); 
                                        else 
                                            $endDate = "NA";
                                        echo $endDate; ?>
                                </td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Subscription Validity Period (days)</td>
                                <td><?php echo $parametersList[1]['subscription_validity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Max. tales that can be available on mobile at any given time</td>
                                <td><?php echo $parametersList[1]['maxdownloads']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Period after which the downloaded tale/s get auto-deleted (days)</td> 
                                <td><?php echo $parametersList[1]['no_of_days']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Max. passwords a Sponsor can buy in one transaaction</td>
                                <td><?php echo $parametersList[1]['maxquantity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Min. number of passwords to be purchased by the Sponsor to get bonus passwords</td>
                                <td><?php echo $parametersList[1]['sponsor_bonus_min']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>No. of bonus passwords, a Sponsor can get</td>
                                <td><?php echo $parametersList[1]['sponsor_comp_pwds']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Validity period of password from the date of purchase (days)</td>
                                <td><?php echo $parametersList[1]['sponsor_pwd_validity']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Sponsor Performance Criterion: Min. passwords to be purchased by Sponsor in 'specified number' of days in order to maintain his discount status</td>
                                <td><?php echo $parametersList[1]['npc_passwords']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Sponsor Performance Criterion: Min. specified period within which Sponsor has to purchase the above no. of passwords (days)</td>
                                <td><?php echo $parametersList[1]['npc_days']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>First year discount for renewal</td>
                                <td><?php echo $parametersList[1]['first_rdp']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>Second year onwards - discount for renewal</td>
                                <td><?php echo $parametersList[1]['second_rdp']; ?></td>
                            </tr>
                            <tr>
                                <td><?php echo $i+1; $i++;  ?></td>
                                <td>GST</td>
                                <td><?php echo $parametersList[1]['GST']; ?></td>
                            </tr>
                            <?php } else { ?>
                        <tr ><td class="text-center" colspan="16">No data</td></tr>
                    <?php  } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>