
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php
        echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::Tour_operator_list
        ));
        ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4" >
            <div class="d-flex justify-content-between mb-4"> 
                <div class="main-heading">
                    <a href="<?php echo $this->basePath() . '/a_dMin/payments'; ?>" class="text-dark"><img src="<?php echo $this->basePath(); ?>/img/left-arrow.svg" alt="back-arrow" class="img-fluid mr-2" width="24">
                        Payments single
                    </a>
                </div>
            </div>
            <div class="" id="recordsList">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-4">
                        <div class="border p-4">
                            <div class="row">
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Booking ID
                                    </label>
                                    <div class="text-capitalize">
                                        STT36
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Transaction ID
                                    </label>
                                    <div class="">
                                        STTP036
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Transaction date
                                    </label>
                                    <div class="">
                                        15/10/2019
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Company name
                                    </label>
                                    <div class="text-capitalize">
                                        Tvisha
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        User type
                                    </label>
                                    <div class="text-capitalize">
                                        Tour operator
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Tour type
                                    </label>
                                    <div class="text-capitalize">
                                        world tour
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Mobile number
                                    </label>
                                    <div class="">
                                        9494342226
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        No. of users
                                    </label>
                                    <div class="">
                                        10
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        Received Amount
                                    </label>
                                    <div class="">
                                        1300/-
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        payment status
                                    </label>
                                    <div class="text-capitalize">
                                        success
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        tax deducted
                                    </label>
                                    <div class="">
                                        200/-
                                    </div>
                                </div>
                                <div class="col-12 col-lg-6 mb-4">
                                    <label class="text-capitalize avant-md">
                                        final amount
                                    </label>
                                    <div class="">
                                        1100/-
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>