
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Samples_list
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4" >
            <div class="d-flex justify-content-between mb-4"> <div class="main-heading">Samples Audio</div> <a class="text-right" href="<?php echo $this->basePath().'/a_dMin/add-sample-audio'?>"><button type="button" class="btn add-btn">Add Sample Audio</button></a> </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-samples-list', array('sampleAudioList'=>$sampleAudioList,'totalCount'=>$totalCount,'type'=>'initialize'
               ,'fileUrl'=>$fileUrl )); ?>

            </div>
            <?php if($totalCount > 10)
            {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-right" id="listPager"></ul>
    <?php   } ?>
        </div>
    </div>
</div>
<div id="deletePlaceModal" class="modal" role="dialog">
    <div class="modal-dialog" style="width: 80% !important;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Sample</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div>Are You sure to Delete the Sample.?</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default delete-conform-button">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/samples-list.js'?>"></script>