
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TAC_Performance
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4" >
            <div class="d-flex justify-content-between mb-4"> <div class="main-heading">STTSE</div>  <a class="text-right" href="<?php echo $this->basePath().'/a_dMin/add-ta-cons'?>"><button type="button" class="btn add-btn">Add STTSE</button></a></div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-ta-cons', array('taCons'=>$taCons,'totalCount'=>$totalCount,'type'=>'initialize')); ?>
            </div>
            <?php
            if($totalCount > 10)
            {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-right" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<div id="deleteTACModal" class="modal" role="dialog">
    <div class="modal-dialog" style="width: 80% !important;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete STTSE</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div>Are You sure to Delete STTSE?</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default delete-conform-button">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/ta-cons.js?v=1.1'?>"></script>