
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TA_Admin
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4" >            
            <div class="d-flex justify-content-between mb-4"> <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/tbe-list/'.base64_encode('taid='.$pdArr['taId'])?>"><i class="fa fa-arrow-left mr-2"></i></a> Tourists added by <?php echo $pdArr['tbeName']; ?></div></div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-tbe-tourists', array('tList'=>$tList,'totalCount'=>$totalCount,'type'=>'initialize', 'tbeId'=>$pdArr['tbeId'])); ?>
            </div>
            <?php
            if($totalCount > 10)
            {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-right" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<input type="hidden" id="hid" value="<?php echo base64_encode("pid=".$pdArr['tbeId']);?>" />
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/tbe-tourists.js?v=1.0'?>"></script>