
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Tour_operator_list
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4" >
            <div class="d-flex justify-content-between mb-4"> <div class="main-heading">Tour Operator List</div>  </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-tour-operator-list', array('tourOperatorList'=>$tourOperatorList,'totalCount'=>$totalCount,'type'=>'initialize'
                )); ?>

            </div>
            <?php if($totalCount > 10)
              {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-right" id="listPager"></ul>
       <?php  } ?>
        </div>
    </div>
</div>
<div id="deletePlaceModal" class="modal" role="dialog">
    <div class="modal-dialog" style="width: 80% !important;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Country</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div>Are You sure to Delete the Country.?</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default delete-conform-button">Yes</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/tour-operator-list.js'?>"></script>