<div class="container-fluid px-0 faqs-banner mb-5">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            faqs
        </div>
    </div>
</div>

<div class="container-fluid my-5">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-8 mb-4 mb-lg-0">
                <h3 class="d-sm-block d-md-none text-uppercase blue">Faq's</h3>
                <div>
                    <div class="accordion" id="accordionExample">
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingOne">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseOne">
                                        What is the necessity of  STT when Information is widely available in media ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>
                                </div>
                            </div>

                            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                STT provides comprehensive but focussed;  detailed  but short  information in a lucid way in the  form of an interesting audio narration. The information available in media is scattered and not fully compiled in one pack.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwo">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwo">
                                        Is STT to be heard only while on tour ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Not necessarily.  You can use STT as you like.  Of course,  you must  use it  without fail, while on tour for maximum enjoyment and satisfaction.  You can also use STT  to  know about the places for deciding  what to see as per your interest and time. You can even  listen to STT at home and enjoy;  as most of us cannot see all the places in  life-time.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingThree">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseThree">
                                        Is internet required for listening to STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                No. Not for listening to the tales. But Internet connection is required for selecting and downloading the tales.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingFour">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseFour">
                                    How much time is required for down-loading ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                That depends on how many  tales  you want to download at a time. Tales of 30 places which is also maximum limit, take approximately 10 minutes. That again depends on the speed of the internet you are using. Downloading may preferably  be done under Wi Fi.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingFive">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseFive">
                                        Is there any limitation on the number of tales that I can download ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Yes. Max. 30 Tales can only reside in your mobile at any given time. This limitation is imposed to ensure the required  memory in your mobile.  For 30 tales about 700 MB memory is sufficient.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingSix">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseSix">
                                        Which memory is used by STT ? Core memory or external chip memory of the Mobile?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Core memory. Generally that amount of memory is available unless the phone is overstuffed with Apps and un-cleared data.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingSeven">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseSeven">
                                        Does STT work on all mobiles ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>
                                </div>
                            </div>

                            <div id="collapseSeven" class="collapse" aria-labelledby="headingSeven" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    As on now STT works on smart phones operating on Android OS. The Io/s version will be released later.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingEight">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseEight">
                                        Does STT work for all OS versions of Android ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseEight" class="collapse" aria-labelledby="headingEight" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    STT works for all OS versions of Android-6.0 and latter.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingNine">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseNine">
                                    Are Spiritual Tour Tales (ST) free ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseNine" class="collapse" aria-labelledby="headingNine" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Yes. For listening to Spiritual Tour Tales, you need not be a subscriber.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTen">
                                    Is there any validity for Subscription Password I buy from a Sponsor?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTen" class="collapse" aria-labelledby="headingTen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Yes. One year from the date of <b><u>his</u></b> purchasing it from STT. So immediately use it and become a Subscriber after buying it unless you are sure of its validity. 
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingEleven">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseEleven">
                                        Will STT intimate regarding the Sponsors ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseEleven" class="collapse" aria-labelledby="headingEleven" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    No. STT does not get into it. 
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwelve">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwelve">
                                        What if I lose my password before using it ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwelve" class="collapse" aria-labelledby="headingTwelve" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    You can only contact the Sponsor.  STT cannot help in this regard.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingThirteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseThirteen">
                                    What if I lose my password after using it ?.
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseThirteen" class="collapse" aria-labelledby="headingThirteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                There is no necessity of it and it becomes invalidated. The first used mobile gets locked as Subscriber’s mobile. Even after formatting the mobile, you remain as subscriber as long as Number is same. Of course within the Subscription period.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingFourteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseFourteen">
                                    Does every tale get presented in all 12 languages ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseFourteen" class="collapse" aria-labelledby="headingFourteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Not always. There is sometimes no necessity or relevance to present every tale  in every language. It is decided on the basis of the popularity of the place amongst different sections and regions of people. It is purely STT’s discretion. Languages are also introduced in progressive manner. Of course,  English and Hindi narrations are available for every article. 

                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingFifteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseFifteen">
                                    Is only one language to be selected for narration ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseFifteen" class="collapse" aria-labelledby="headingFifteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Yes. Either  English or Hindi or any regional language. If regional language is selected, one default language is always  to be selected.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingSixteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseSixteen">
                                    What is a default language, why should I select ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseSixteen" class="collapse" aria-labelledby="headingSixteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Default languages are English and Hindi. The purpose of selecting one of them, whenever  a regional language is selected is- to listen to the tales at least in default language in case they are not available in chosen  regional language.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingSeventeen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseSeventeen">
                                    Can I download the same tale in another language also ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseSeventeen" class="collapse" aria-labelledby="headingSeventeen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Yes. You can. But not simultaneously.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingEighteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseEighteen">
                                    When does the STT tales get erased ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseEighteen" class="collapse" aria-labelledby="headingEighteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Individual tale gets erased 15 days after its download. The pre-packaged  tales in case of CT and FT get downloaded or erased together.  At 1159 PM on  the last day, tales  get erased.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingNinteen">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseNinteen">
                                    Will there be any repetition of the passwords being issued by STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseNinteen" class="collapse" aria-labelledby="headingNinteen" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                There is no chance of any  password getting repeated.  The password given will be appended with many unique parameters internally. So there is no possibility.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwenty">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwenty">
                                    Can I contribute to STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwenty" class="collapse" aria-labelledby="headingTwenty" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Certainly. You can let us know about your interests to contribute as translators, narrators or picture providers. You can also be content advisors  to let us know about certain  local places of prominence near your area.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentyone">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentyone">
                                    At what frequency, STT Tales are added ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentyone" class="collapse show" aria-labelledby="headingTwentyone" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                Susri Tour Tales are added every month. The upcoming schedule is also announced for next three months and complied with.
                                </div>
                            </div>
                        </div>
                        <!-- <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentytwo">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentytwo">
                                        What is a default language, why should I select ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentytwo" class="collapse" aria-labelledby="headingTwentytwo" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Default languages are English and Hindi. The purpose of selecting one of them
                                    whenever a regional language is selected is- to make the tales available to the user
                                    in the selected default language in case they are not available in that regional
                                    language chosen.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentythree">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentythree">
                                        Can I not download in another language also; for single payment?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentythree" class="collapse" aria-labelledby="headingTwentythree" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Yes. You can. But not simultaneously. With the same password you can download
                                    number of times with different languages, but one at a time. All within the
                                    timeframe period.
                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentyfour">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentyfour">
                                        When does the STT tales get erased ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentyfour" class="collapse" aria-labelledby="headingTwentyfour" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    It depends on the period you have chosen at the time of booking, while selecting the
                                    time-frame. At 1159 PM of the last day, it gets erased.

                                </div>
                            </div>
                        </div>
                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentyFive">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentyFive">
                                        Does STT charge for ST tales , if they are packaged as part of CT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentyFive" class="collapse" aria-labelledby="headingTwentyFive" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Yes. STT charges for the ST Tales if they are selected as part of CT, IT and SS.
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentysix">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentysix">
                                        Can the duration of CT be extended ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentysix" class="collapse" aria-labelledby="headingTwentysix" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    No. STT judiciously fixes the duration. If that is not found sufficient, fresh booking
                                    may have to be done again.
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentyseven">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentyseven">
                                        Will there be any repetition of the passwords being issued by STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentyseven" class="collapse" aria-labelledby="headingTwentyseven" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    There is no chance of any password getting repeated. The password given will be
                                    appended with many unique parameters internally. So there is no possibility.
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentyeight">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentyeight">
                                        Will STT refund the money paid for erroneous booking ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentyeight" class="collapse" aria-labelledby="headingTwentyeight" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    No. Sorry.
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingTwentynine">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapseTwentynine">
                                        Can I contribute to STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapseTwentynine" class="collapse" aria-labelledby="headingTwentynine" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    Certainly. You can let us know about your interests to contribute as translators,
                                    picture providers or advisors to let us know about certain local places of prominence
                                    near your area etc.
                                </div>
                            </div>
                        </div>

                        <div class="card border-0 border-radius-10 mb-3 custom-shadow">
                            <div class="card-header border-0 bg-transparent p-3 p-md-4 m-0" id="headingthirty">
                                <div class="d-flex align-items-center">
                                    <a class="color-000 d-block accordion-headding flex-grow-1 avant-md" data-toggle="collapse" href="#collapsethirty">
                                        Are there any agents or Franchisers for STT ?
                                        <i class="fas fa-angle-down"></i>
                                    </a>

                                </div>
                            </div>

                            <div id="collapsethirty" class="collapse" aria-labelledby="headingthirty" data-parent="#accordionExample">
                                <div class="card-body pt-0">
                                    No. All the operations are on line. STT does not have any agents.
                                </div>
                            </div>
                        </div> -->

                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <div class="custom-shadow border-radius-10 bg-white p-4">
                    <div class="text-capitalize avant-md tour-headding color-000 mb-3">
                        Enquiry Form
                    </div>
                    <div class="mb-3">
                        <input type="text" placeholder="Name" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="name">
                    </div>
                    <div class="mb-3">
                        <input type="text" placeholder="Number" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="mobile">
                    </div>
                    <div class="mb-3">
                        <input type="email" placeholder="Email ID" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="email">
                    </div>
                    <div class="mb-3">
                        <textarea placeholder="Message" rows="4" class="form-control form-control-lg py-3 avant-md border-radius-10 custom-shadow" id="message"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="btn submit-btn text-capitalize px-4 py-3 text-white mt-3" id="submit">
                            submit
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="<?php echo $this->basePath();?>/js/faq.js"></script>