<div class="container-fluid">
    <div class="container">
        <div class="text-uppercase avant-md tour-headding color-000 mb-3 d-flex justify-content-between mt-3">
            <p class="mb-0"> Festival Tours </p>
        </div>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white">
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath()?>/">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Festival Tours</li>
            </ol>
        </nav>

        <div class="row mt-5">
            <?php if(count($seasonalSpecialslist)) {
                foreach ($seasonalSpecialslist as $seasonalSpecial) {
                    ?>
                    <div class="col-12 col-md-3 mb-3">
                        <div class="slider-box bg-white mb-3 position-relative">

                            <a href="<?php echo $this->basePath();?>/seasonal-places-list/<?php echo base64_encode("placesList=".$seasonalSpecial['seasonal_special_id'])?>" class="stretched-link"></a>
                            <div class="slider-image position-relative" style="background: #f5f5f5 url('<?php echo $imageUrl.$seasonalSpecial['file_path']; ?>') no-repeat center / cover">
                            </div>
                            <div class="p-3">
                                <div class="d-flex align-items-center">

                                    <div style=" min-width: 0">
                                        <div class="text-capitalize color-000 avant-bk tour-country text-truncate ">
                                            <?php echo $seasonalSpecial['seasonal_name']; ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                <?php } } ?>


        </div>



    </div>
</div>