<div class="container-fluid px-0 aboutus-banner mb-5">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            Terms
        </div>
    </div>
</div>

<div class="container-fluid my-5">
    <div class="container privacy-container">
        <div class="bg-white border-radius-10 custom-shadow p-4">
            <h4>
                Terms
            </h4>

            <ol class="terms_list">
                <li>Please read these “Terms” carefully before using the Mobile Application “Susri Tour
                Tales”, and the web site https://www.susritourtales.com, which are the &quot;Services&quot; operated by our company Susri Tour Tales Pvt Ltd (STT).</li>
                <li>Your access to and use of our Services is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Services of Susri Tour Tales Pvt Ltd (STT).</li>
                <li class="text-info"><strong>By accessing or using the Service itself, you are construed to be bound by these
                Terms. If you disagree with any part of the terms then you are not expected to access or use the Service.</strong></li>
                <li><strong class="text-info">Subscription</strong>
                    <ol>
                        <li>If you wish to install the App and use it either as Free user or become QUESTT or TWISTT subscriber - you need to provide your identity, phone number and email id (where required) and State/Country of residence as specified by the
                system.</li>
                        <li>Refusal to submit any of the details will not entitle you to get our services. You need to comply with the procedures, payments and service conditions specified as relevant to the service sought.</li>
                        <li>You cannot hold STT Pvt Ltd responsible for any technical snags in the channel, and connectivity and any hardware or software problems at your phone end</li>
                        <li>While logging in, subscribing and registering as TWISTT sponsor, permissions needed by the system are to be accepted by you. STT Pvt Ltd does not indulge in any sort of misusing your device resources. The permissions are needed for the App to perform its features.</li>
                        <li>In case you are a TWISTT Sponsor, you have the responsibility to do ethical business with your customers. If STT Pvt Ltd gets authentic proof of your cheating the customer with expired passwords, you are liable to be expelled as Sponsor.</li>
                        <li>STT Pvt Ltd does not hold any responsibility for any wrong operations by TWISTT Enablers while serving their tourist customers. STT Pvt Ltd does not hold any responsibility for the issues between TWISTT Enablers and Users.</li>
                    </ol>
                </li>
                <li><strong class="text-info">Content</strong>
                    <ol>
                        <li>All the text and audio content of the Tour Tales in all languages is proprietary of Susri Tour Tales Pvt Ltd and copying any part of it or whole in any form is violation of the copyrights and such acts are liable for legal action.</li>
                        <li>STT asserts that the compilation and the creation of the “tales” is the sole proprietary of STT with the information learnt from various sources.</li>
                        <li>The sources of information are very exhaustive and acknowledging every reference is impossible. STT respects all such acknowledged and unacknowledged sources. STT does not entertain any issue on this aspect.</li>
                        <li>STT Pvt Ltd has total independence in selecting the places and languages for the tales as well as their order of uploading into the app. Users can suggest their choices but cannot question it.</li>
                        <li>STT enjoys the right of expressing the facts and its own views about themonuments including the myths and legends existing in circulation. STT cannot be questioned on that.</li>
                        <li>The pictures and music presented in the app are obtained from licensed sourcesor from personally shot/played/permitted by STT personnel. Any resemblance isonly accidental and STT does not entertain any inquiries in this regard.</li>
                    </ol>
                </li>
                <li><strong class="text-info">Changes</strong>
                    <ol>
                        <li>STT Pvt Ltd reserves the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 20 days&#39; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</li>
                    </ol>
                </li>
                <li><strong class="text-info">Contact us if you have any questions about these terms on our e-mail.</strong></li>
            </ol>
        </div>
    </div>
</div>