<div class="container-fluid px-0 tours-banner mb-5">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
        Tour Tales Menu
        </div>
    </div>
</div>

<div class="container-fluid pb-5">
    <div class="container">
        <!--<div class="text-uppercase avant-md tour-headding color-000 mb-3">
            personal tour
        </div>-->
        <h3 class="d-sm-block d-md-none text-uppercase blue">Tour Tales Menu</h3>
        <a href="#avail-tours" class="btn btn-light btn-lg bg-info text-light my-3" role="button">Go to  ' TOURS AT A GLANCE '  section  <i class="fas fa-chevron-down"></i></a>
        <div class="row mx-n2">
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 mb-4 px-2">
                <a href="<?php echo $this->basePath() . '/state-list/spiritual-tour' ?>">
                    <div class="border-radius-10 overflow-hidden custom-shadow personal-tour-img mb-3" style="background: url('<?php echo $this->basePath(); ?>/img/user/spiritual-tour-main.png') no-repeat center / cover">
                    </div>
                    <div class="text-center text-uppercase avant-md tour-headding color-000 mb-3">
                        SPIRITUAL TOUR TALES (ST)
                    </div>
                    <div class="color-666">
                        <p>
                            ‘Spiritual Tour Tales’ category covers only  the ‘Tales’ of Spiritual places in India. They include  religious,   ancient and historical places of religious significance- as chosen by STT.  The Tales narrate the importance of the places as per scriptures and also popular beliefs.  The Spiritual Tour Tales are free,  if  only selected from ST Tales category. They can also be selected from IT, CT or FT categories  if you are a subscriber.
                        </p>
                        Selection Path: <b><i>State/Union Territory > City > Place</i></b>
                    </div>
                </a>

            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 mb-4 px-2">
                <a href="<?php echo $this->basePath() . '/state-list/india-tour' ?>">
                    <div class="border-radius-10 overflow-hidden custom-shadow mb-3 personal-tour-img mb-3" style="background: url('<?php echo $this->basePath(); ?>/img/user/india-tour.png') no-repeat center / cover">
                    </div>
                    <div class="text-center text-uppercase avant-md tour-headding color-000 mb-3">
                        INDIA TOUR TALES (IT)
                    </div>
                    <div class="color-666">
                        <p>
                            ‘India Tour Tales’ cover national, historical, religious, architectural, technological and geographical places of ‘tourism interest’,  besides-  museums, zoological parks, botanical gardens etc.  All those Indian places found in  ST, CT and FT are again included in IT. It is a  super set of all individual Indian Places.  
                        </p>
                        Selection Path: <b><i>State > City > Place</i></b>
                    </div>
                </a>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 mb-4 px-2">
                <a href="<?php echo $this->basePath() . '/country-list/world-tour' ?>">
                    <div class="border-radius-10 overflow-hidden custom-shadow mb-3 personal-tour-img mb-3" style="background: url('<?php echo $this->basePath(); ?>/img/user/world-tour-main.png') no-repeat center / cover">
                    </div>
                    <div class="text-center text-uppercase avant-md tour-headding color-000 mb-3">
                        WORLD TOUR TALES (WT)
                    </div>
                    <div class="color-666">
                        <p>
                            ‘World Tour Tales’ is similar to India Tour Tales covering the tales of the places of ‘Tourism Interest’ in different countries. World Tour Tales is also a  super set of the individual places packaged in  CT(World) and FT (World) .
                        </p>
                        Selection Path: <b><i>Country > City > Place</i></b>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid pb-5">
    <div class="container">
        <div class="row mx-n2">
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-4 px-2">
                <a href="<?php echo $this->basePath() . '/country-list/city-tour' ?>">
                    <div class="border-radius-10 overflow-hidden custom-shadow mb-3 seasonal-tour-img" style="background: url('<?php echo $this->basePath(); ?>/img/user/city-tour.png') no-repeat center / cover">
                    </div>
                    <div class="text-uppercase avant-md tour-headding color-000 mb-3">
                        CITY TOUR TALES (CT) 
                    </div>
                    <div class="color-666">
                        <p>
                            ‘City Tour Tales’  category is about the tales of the places within a city and nearby that city. Cities can be in India or abroad.  In this category, the tales of the places are pre-packaged. They cannot be individually downloaded or removed if selected from CT. If the user desires to download only particular places, it can be done from IT or WT.
                        </p>
                        <table>
                            <tr>
                                <td class="mx-2">Selection Path :</td>
                                <td class="mx-2 px-2"><b><i>Country > City</i></b></td>
                                <td class="mx-2 px-2">for download  and </td>
                            </tr>
                            <tr>
                                <td class="mx-2"></td>
                                <td class="mx-2 px-2"><b><i>Country > City > Place</i></b></td>
                                <td class="mx-2 px-2">for listening</td>
                            </tr>
                        </table>
                        <!-- <i>Selection Path :  Country >  City  </i> -->
                    </div>
                </a>
            </div>
            <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-4 px-2">
                <a href="<?php echo $this->basePath(); ?>/seasonal-specials">
                    <div class="border-radius-10 overflow-hidden custom-shadow mb-3 seasonal-tour-img" style="background: url('<?php echo $this->basePath(); ?>/img/user/seasonal-special.png') no-repeat center / cover">
                    </div>
                    <div class="text-uppercase avant-md tour-headding color-000 mb-3">
                        FESTIVAL TOUR TALES  (FT)
                    </div>
                    <div class="color-666">
                        <p>
                            ‘Festival Tour Tales’ is also like the City Tour Tales . It is also a set of pre-packaged  tales . The set   offered   under this category focuses on the tales pertaining to  a place  or group of places which is/are popular for a Festival/ Special Occasion and visited in large numbers during those times.  FTs can be both from India and abroad. 
                        </p>
                        <table>
                            <tr>
                                <td class="mx-2">Selection Path :</td>
                                <td class="mx-2 px-2"><b><i> Country >  FT Set</i></b></td>
                                <td class="mx-2 px-2">for download  and </td>
                            </tr>
                            <tr>
                                <td class="mx-2"></td>
                                <td class="mx-2 px-2"><b><i>Country >  FT Set > Place</i></b></td>
                                <td class="mx-2 px-2">for listening</td>
                            </tr>
                        </table>
                        <!-- <i>Selection Path :  Country >  Seasonal Special </i> -->
                    </div>
                </a>
            </div>
        </div>
        
        <div class="row mt-3">
            <div class="col-12 my-2">
                <h5>HOW TO USE STT APP  AS A SUBSCRIBER</h5>
                <ul>
                    <li>You can be a free user if interested in listening to only &ldquo;Spiritual Tour Tales&rdquo;.</li>
                    <li>You have to be a subscriber to listen to rest of the Tales.&nbsp;</li>
                    <li>You can subscribe by paying Rs 365/ by making online payment.&nbsp;</li>
                    <li>Special offers will also be running on Subscription amount for specific periods.&nbsp;</li>
                    <li>As subscriber you can&nbsp; download and listen to any number of tales throughout&nbsp; the year.</li>
                    <li>You can also become a &ldquo;Subscriber&rdquo; by entering a password given/sold to you by a Sponsor.</li>
                    <li>Such password is only valid for one year from the date of purchasing by the sponsor. This is to be ensured while taking it from sponsor.&nbsp;</li>
                    <li>Once you&nbsp; subscribe using a mobile, the subscription gets locked to that mobile for the rest of the year.&nbsp; Subscription cannot be transferred.</li>
                    <li>Tales downloaded will get auto-deleted after 15 days. You can download again.</li>
                    <li>Max. of 30 Tales will only be residing in your mobile at any point of time. In order to download more, you have to remove some. This is to avoid memory suffocation.</li>
                    <li>You can view your active download log and the history of past one month.</li>
                    <li>Renewal buttons will appear in 12<sup>th</sup> month prompting you to renew.</li>
                </ul>
            </div>
            <div class="col-12  my-2">
                <h5>HOW TO USE STT APP AS A SPONSOR</h5>
                <ul>
                    <li>You have to be an active Subscriber in order to register yourself as Sponsor.</li>
                    <li>You can register as a sponsor by activating a &ldquo;button&rdquo; in the Profile Menu.</li>
                    <li>Becoming a sponsor is at free of cost.</li>
                    <li>Soon after becoming a Sponsor, &ldquo;Buy Passwords&rdquo; button appears&nbsp; in Profile Menu.</li>
                    <li>Using &ldquo;Buy Passwords&rdquo; button, you can purchase&nbsp; passwords at discounted rate.</li>
                    <li>On successful payment, Passwords will be sent to your registered e-mail immediately.</li>
                    <li>On&nbsp; purchasing the first 10 passwords, you&nbsp; receive 5 complimentary passwords.</li>
                    <li>You can sell the passwords to interested persons at a profit, justifiable to the discount you got.</li>
                    <li>App shows you&nbsp; the history of your passwords purchased and also the date on which the purchaser redeemed it. Expired passwords are highlighted on your screen.</li>
                    <li>You can also enter sold/unsold status of your passwords. This facility helps you to enter &ldquo;sold status&rdquo; so that you do not resell them by mistake.</li>
                    <li>Based on your buying of passwords, your discount will be enhanced.</li>
                    <li>If you do not make&nbsp; minimum purchase of 20 passwords in 60 days, your discount will be reduced.</li>
                    <li>Passwords purchased during special offer period can also be used during no-offer period. Only one year validity is to be observed.</li>
                </ul>
            </div>
        </div>
        <div id="avail-tours" class="row mt-3" style="overflow:auto;max-height: 500px;">
            <div class="col-6 mt-2"><div class="text-uppercase avant-md tour-headding color-000 mb-3">Tours at a glance</div></div>
            <div class="col-6 mt-2 text-right text-uppercase avant-md color-000 mb-3">
            <!-- <input type="checkbox" data-toggle="toggle" id="cbUpc"> Upcoming -->
            <div class="form-check-inline">
                <label class="form-check-label" for="radio1">
                    <input type="radio" class="form-check-input" id="radio1" name="optradio" value="a" checked>Available
                </label>
            </div>
            <div class="form-check-inline">
                <label class="form-check-label" for="radio2">
                    <input type="radio" class="form-check-input" id="radio2" name="optradio" value="u">Upcoming
                </label>
            </div>
            </div>
            <div id="avlDiv" class="col-12 my-2">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#ST">ST</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#CT">CT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#FT">FT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#IT">IT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#WT">WT</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="ST" class="container tab-pane active"><br>
                        <h6 class="py-2">Available Spiritual Tours Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($AvlSTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="CT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Available City Tours Tales</h6>
                        <p><?php //print_r($AvlCTlist); ?></p>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Country</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($AvlCTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['country_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="FT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Available Festival Tours Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($AvlFTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="IT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Available India Tour Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($AvlITlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="WT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Available World Tour Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Country</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($AvlWTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['country_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div id="upcDiv" class="col-12 my-2">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#UST">ST</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#UCT">CT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#UFT">FT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#UIT">IT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#UWT">WT</a>
                    </li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="UST" class="container tab-pane active"><br>
                        <h6 class="py-2">Upcoming Spiritual Tours Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                                <th>Month-Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($UpcSTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                    <td><?php echo $row['month_year'];?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="UCT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Upcoming City Tours Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Country</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                                <th>Month-Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($UpcCTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['country_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                    <td><?php echo $row['month_year'];?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="UFT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Upcoming Festival Tours Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                                <th>Month-Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($UpcFTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                    <td><?php echo $row['month_year'];?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="UIT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Upcoming India Tour Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>State</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                                <th>Month-Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($UpcITlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['state_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                    <td><?php echo $row['month_year'];?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                    <div id="UWT" class="container tab-pane fade"><br>
                        <h6 class="py-2">Upcoming World Tour Tales</h6>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>Country</th>
                                <th>City</th>
                                <th>Place</th>
                                <th>Languages</th>
                                <th>Month-Year</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach($UpcWTlist as $row){
                                $strLangs = implode(', ',array_unique(explode(',', $row['language_name'])));?>
                                <tr>
                                    <td><?php echo $row['country_name'];?></td>
                                    <td><?php echo $row['city_name'];?></td>
                                    <td><?php echo $row['place_name'];?></td>
                                    <td><?php echo $strLangs;?></td>
                                    <td><?php echo $row['month_year'];?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function(){
                $('#upcDiv').hide();
                $('input[type=radio][name="optradio"]').change(function() {
                    if($('input[name="optradio"]:checked').val() == "u"){
                        $('#avlDiv').hide();
                        $('#upcDiv').show();
                    } else {
                        $('#upcDiv').hide();
                        $('#avlDiv').show();
                    }
                    /* if($(this).is(':checked')) {
                        $('#avlDiv').hide();
                        $('#upcDiv').show();
                    } else {
                        $('#upcDiv').hide();
                        $('#avlDiv').show();
                    } */
                });
            });
        </script>
    </div>
</div>