<div class="sidebar">
    <a href="<?php echo $this->basePath();?>/se-home" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTTSE_HOME_PAGE?'active':'');?>">TWISTT SE Dashboard</a>
    <a href="<?php echo $this->basePath();?>/twisttse-password" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_CHANGE_PASSWORD?'active':'');?>">Change Password</a> 
    <a href="<?php echo $this->basePath();?>/a_dMin/twisttse-logout">Logout</a>
</div>