<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Susri Tourtales</title>
    <meta name="keywords" content="Susri tour tales, Susritourtales, susritourtales, susritourtales.com">
    <?=
    $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?=
    $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.png'])
        ->prependStylesheet($this->basePath('css/style.css?v=1.0.2'))
        ->prependStylesheet($this->basePath('css/owl.carousel.min.css'))
        ->prependStylesheet($this->basePath('css/owl.theme.default.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap v5.2.3/bootstrap.min.css'))
        ->prependStylesheet($this->basePath() . '/css/vendor/fontAwesome/fontawesome-all.min.css')
        ->prependStylesheet($this->basePath() . '/css/vendor/fontAwesome/fontawesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/jquery.mCustomScrollbar.css')
    ?>

    <!-- Scripts -->
    <?=
    $this->headScript()
        ->prependFile($this->basePath('js/global.js?v=1.0.1'))
        ->prependFile($this->basePath('js/vendor/fontawesome-all.min.js'))
        ->prependFile($this->basePath('js/vendor/fontawesome.min.js'))
        ->prependFile($this->basePath('js/owl.carousel.min.js'))
        ->prependFile($this->basePath('js/bootstrap v5.2.3/bootstrap.min.js'))
        ->prependFile($this->basePath('js/popper.min.js'))
        ->prependFile($this->basePath('js/jquery.mCustomScrollbar.concat.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ?>

    <script>
        var BASE_URL = "<?php echo $this->basePath(); ?>";
    </script>
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-md bg-white navbar-shadow">
            <a class="navbar-brand" href="<?php echo $this->basePath(); ?>/"><img src="<?php echo $this->basePath(); ?>/img/user/logo.png" class="img-fluid" alt="logo"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-end" id="navbarTogglerDemo02">
                <ul class="list-unstyled navbar-nav">
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_HOME_PAGE ? 'active' : '') ?>">
                            home
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/about-us" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_ABOUT_PAGE ? 'active' : '') ?>">
                            about us
                        </a>
                    </li>
                    <!-- <li>
                        <a href="<?php echo $this->basePath(); ?>/tours" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_TOUR_TALES_PAGE ? 'active' : '') ?>">
                            Tour Tales Menu
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/twistt" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_TWISTT ? 'active' : '') ?>">
                            TWISTT
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/help" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_HELP_PAGE ? 'active' : '') ?>">
                            help
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/faqs" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_FAQ_PAGE ? 'active' : '') ?>">
                            faq's
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/acknowledgements" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_CREDIT_PAGE ? 'active' : '') ?>">
                            CREDITS
                        </a>
                    </li> -->
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/terms-privacy" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_CONTACT_PAGE ? 'active' : '') ?>">
                            Terms & Privacy
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->basePath(); ?>/contact" class="<?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_CONTACT_PAGE ? 'active' : '') ?>">
                            contact
                        </a>
                    </li>
                    <!-- <li>
                        <a href="<?php echo $this->basePath(); ?>/contributor" class="contributor-link <?php echo (isset($activeTab) && $activeTab == \Application\Constants\Constants::MAIN_SITE_CONTRIBUTOR_PAGE ? 'active' : '') ?>">
                            be a contributor
                        </a>
                    </li> -->
                </ul>
            </div>
        </nav>
    </div>
    <div class="flex-fill">
        <?php echo $this->content; ?>
    </div>
    <div class="container-fluid promotion-fluid py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-12 col-sm-12 col-md-6 mb-4 mb-md-0">
                    <div class="d-flex align-items-center">
                        <div class="p-2 p-md-4 bg-white my-md-n4">
                            <img src="<?php echo $this->basePath(); ?>/img/user/susri.png" class="img-fluid" alt="susri-img">
                        </div>
                        <div class="text-white avant-bk promotion-text ms-3">
                            Your pocket tour mate on the go...
                            <div>
                                Install app
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6">
                    <div class="text-md-right">
                        <a href="javascript:void(0);" target="_blank" class="d-inline-block mb-3 mb-md-0">
                            <img src="<?php echo $this->basePath(); ?>/img/user/play-store.png" class="img-fluid" alt="playstore-img">
                        </a>
                        <a href="javascript:void(0);" target="" class="d-inline-block ml-md-2">
                            <img src="<?php echo $this->basePath(); ?>/img/user/app-store.png" class="img-fluid" alt="playstore-img">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="bg-footer">
        <div class="container-fluid py-4">
            <div class="container">
                <div class="row align-items-center py-3 footer-section mb-3">
                    <div class="col-12 col-sm-12 col-md-6 mb-3 mb-md-0">
                        <ul class="list-unstyled footer-links mb-0">
                            <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/">
                                    home
                                </a>
                            </li>
                           <!--  <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/acknowledgements">
                                    credits
                                </a>
                            </li> -->
                            <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/terms-privacy">
                                    terms
                                </a>
                            </li>
                            <!-- <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/help">
                                    help
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/faqs">
                                    faq's
                                </a>
                            </li> -->
                            <li class="list-inline-item">
                                <a href="<?php echo $this->basePath(); ?>/contact">
                                    contact
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-12 col-sm-12 col-md-6">
                        <div class="d-flex align-items-center justify-content-md-end">
                            <span class="text-white text-uppercase mr-2">+91 90596 44412</span>
                            <ul class="list-unstyled m-0">
                                <li class="list-inline-item">
                                    <i class="fab fa-whatsapp" style="font-size:36px;color:#25D366"></i>
                                </li>
                            </ul>
                            <span class="text-white text-uppercase mx-3 ">follow us</span>
                            <ul class="list-unstyled m-0">
                                <li class="list-inline-item">
                                    <a href="https://www.facebook.com/Susri-Tour-Tales-105923254650552" target="_blank" class="social-icon icon-facebook">
                                        <i class="fab fa-facebook-f"></i>
                                    </a>
                                </li>
                                <li class="list-inline-item">
                                    <a href="https://youtu.be/JCbJSJjtHKM" target="_blank" class="social-icon icon-youtube">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row align-items-center">
                    <div class="col-12 col-sm-12 col-md-6 mb-3 mb-md-0 text-white">
                        2019 © All rights reserved. <a href="javascript:void(0);" class="text-white">www.susritourtales.com</a>
                    </div>
                    <div class="col-12 col-sm-12 col-md-6">
                        <div class="text-uppercase text-white text-md-right">
                            designed & developed by : <a href="https://www.tvisha.com" target="_blank"><img src="<?php echo $this->basePath(); ?>/img/user/tvisha-logo.png" class="img-fluid" alt="tvisha-logo"></a> and K.Manjary
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <div class="feedback-section" id="feedbackSection"><span></span></div>
    <?= $this->inlineScript() ?>
</body>

</html>