<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Promoters_List
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/select2.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/vendor/select2.full.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-promoter.js?v-1.0"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/promoters-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add Promoter</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12">
                                        <label class="text-black-50">Mobile</label>
                                        <input type="text" class="form-control" id="mobile"/>
                                    </div>
                                    <div class="col-12" id="state-wrapper"><label class="text-black-50">Name</label>
                                        <input type="text" class="form-control" id="name" readonly/>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="addPromoter" disabled>Submit</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>