<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::TA_Section,
            'activeTab'=>\Application\Constants\Constants::TA_Plans
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/add-ta-plan.js"></script>

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/ta-plans'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add TA Plan</div>
                <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12">
                                        <label class="text-black-50">Plan name</label>
                                        <input type="text" class="form-control" id="planName"/>
                                    </div>
                                    <div class="col-12" id="state-wrapper"><label class="text-black-50">MTC</label>
                                        <input type="text" class="form-control" id="mtc"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">Cost</label>
                                        <input type="text" class="form-control" id="cost"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">Duration</label>
                                        <input type="text" class="form-control" id="duration" value="15"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">Active</label>
                                    <input type="checkbox" id="active" name="active" value="0" checked/>
                                    </div>                                    
                                </div>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="addTaPlan">Submit</button></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>