<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::FT
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4 row">
            <div class="main-heading"><a class="me-3" href="<?php echo $this->basePath() . '/a_dMin/free-tour-list' ?>"><i class="fa fa-arrow-left mr-2"></i></a>Add/Edit Free Tour List</div> <a class="text-end" href="<?php echo $this->basePath() . '/a_dMin/add-free-tour/' . base64_encode('tt=' . $ttq) ?>"><button type="button" class="btn add-btn"><?php echo ($ttq == '1') ? 'Add/Edit Free India Tales' : 'Add/Edit Free World Tales';?></button></a>
            <input type="hidden" value="<?php echo $ttc; ?>" id="taletype">
            </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/add-free-tour-list', array(
                    'tourismList' => $placesList, 'totalCount' => $totalCount, 'type' => 'initialize','ttc' => $ttc
                )); ?>
            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<?php echo $this->partial('/admin/admin/deleteModal', ['entityName' => 'Free Tale']); ?>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/add-free-list.js?v=1.0.1' ?>"></script>