<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php
        echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Places
        ));
        ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<script src="<?php echo $this->basePath() ?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath() ?>/js/imageResize.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-place.js?v=1.0.8"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath() . '/a_dMin/places' ?>"><i class="fa fa-arrow-left mr-2"></i></a> Add Place</div>
            <div class="row">
                <div class="col-12 col-lg-10">
                    <div class="row adding-form">
                        <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                            <div class="row">
                                <div class="col-12">
                                    <label class="text-black-50">Country</label>
                                    <select class="form-control" id="country">
                                        <option value="">--select country--</option>
                                        <?php foreach ($countries as $country) { ?>
                                            <option value="<?php echo $country['id']; ?>"><?php echo $country['country_name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="col-12" id="state-wrapper"><label class="text-black-50" for="states">State</label>
                                    <select class="form-control" id="states">
                                        <option value=""></option>
                                    </select>
                                </div>
                                <div class="col-12"><label class="text-black-50">City</label>
                                    <select class="form-control" id="cities">
                                        <option value=""></option>
                                    </select>
                                </div>
                                <div class="col-12"><label class="text-black-50">Place Name</label>
                                    <input type="text" class="form-control" id="place-name" />
                                </div>
                                <div class="col-12">
                                    <label class="text-black-50">Description</label>
                                    <textarea class="form-control" id="description"></textarea>
                                </div>
                                <div class="col-12"><label class="text-black-50">Place Code</label>
                                    <input type="text" class="form-control upload-file-name" value="">
                                </div>
                                <div class="col-12">
                                    <label class="text-black-50">Image Files</label>
                                    <div class="position-relative w-100 image-upload-wrapper">
                                        <input type="file" class="image-upload" name="image-file" multiple>
                                        <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                                    </div>
                                    <div class="image-preview-wrapper row">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <label class="text-black-50">Thumbnail File</label>
                                    <div class="position-relative w-100 image-upload-wrapper">
                                        <input type="file" class="tn-upload" name="thumbnail" id="thumbnail">
                                        <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                                    </div>
                                    <div class="tn-preview-wrapper row">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="text-capitalize heading mb-3">Audio</div>
                            <div class="" id="file-upload-wrapper">
                                <?php echo $this->partial("/admin/admin/file-upload-row", array('languages' => $languages, 'numberOfrows' => 0, "rowNumber" => 1)); ?>
                            </div>
                            <div class="row">
                                <div class="col-12 text-right"> <a class="add-control"><i class="fas fa-plus-circle"></i>Add Audio</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-2">
                <div class="row">
                    <div class="col-sm-12 text-left"> <button type="button" class="btn submit-btn" id="addPlace">Submit</button></div>
                </div>
            </div>
        </div>

    </div>
</div>