
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Languages
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/sol.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/add-language.js';?>"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-4" >
            <!-- <div class="main-heading mb-3">Activate Language</div> -->
            <div class="row adding-form1">
                <div class="col-12 col-sm-12 col-md-12"">
                <div class="row mt-3">
                    <div class="col-4">
                        <div class="heading mb-3">Active Languages</div>
                        <div><ul><?php foreach($acldata as $lang){
                                echo "<li>" . $lang['name'] . "</li>";
                            }?></ul>
                        </div>
                    </div>
                    <div class="col">
                        <div class="heading mb-3">Available Languages</div>
                        <select  class="form-control" id="languages" name="languages" style="width:250px;">
                            <option value="">--select language--</option>
                            <?php foreach ($alldata as $lg ) { ?>
                            <option value="<?php echo $lg['id']; ?>"><?php echo $lg['name']; ?></option>
                            <?php } ?>
                        </select>
                        <button type="button" class="btn submit-btn mt-3" id="btnChange">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

