
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Slab_price_page
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">



<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-4" >
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/slab-price-list'?>"><!--<i class="fa fa-arrow-left mr-2"></i>--></a>  View/Edit Slab Prices</div>
              <div class="row adding-form1">
                     <div class="col-12 col-sm-12 col-md-4"">
                        <div class="text-decoration-underline my-3">Tour Type :IT</div>
                         <div class="row mt-3">
                             <div class="col-12 col-sm-12 col-md-6 col-lg-8">
                                 <div class="row mb-3">
                                     <div class="col-6 text-center"> <b>Slab Days</b></div>
                                     <div class="col-6 text-center"><b>Price (In INR)</b></div>
                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">5</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="5" value="<?php echo ((count($priceListIt)&& isset($priceListIt["5"]))?$priceListIt["5"]:"")?>"></div>

                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">10</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="10" value="<?php echo ((count($priceListIt)&& isset($priceListIt["10"]))?$priceListIt["10"]:"")?>"></div>

                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">15</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="15" value="<?php echo ((count($priceListIt)&& isset($priceListIt["15"]))?$priceListIt["15"]:"")?>"></div>

                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">20</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="20" value="<?php echo ((count($priceListIt)&& isset($priceListIt["20"]))?$priceListIt["20"]:"")?>"></div>

                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">25</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="25" value="<?php echo ((count($priceListIt)&& isset($priceListIt["25"]))?$priceListIt["25"]:"")?>"></div>

                                 </div>
                                 <div class="row mb-3 align-items-center">

                                     <div class="col-6 text-center">30</div>
                                     <div class="col-6 text-center"><input type="text" class="form-control price slab-price-it" data-id="30" value="<?php echo ((count($priceListIt)&& isset($priceListIt["30"]))?$priceListIt["30"]:"")?>"></div>

                                 </div>


                             </div>

                         </div>
                     </div>
                  <div class="col-12 col-sm-12 col-md-4"">
                      <div class="text-decoration-underline my-3">Tour Type :WT</div>
                      <div class="row mt-3">
                          <div class="col-12 col-sm-12 col-md-6 col-lg-8">
                              <div class="row mb-3">
                                  <div class="col-6 text-center"> <b>Slab Days</b></div>
                                  <div class="col-6 text-center"><b>Price (In INR)</b></div>
                                 </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">5</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="5" value="<?php echo ((count($priceListWt)&& isset($priceListWt["5"]))?$priceListWt["5"]:"")?>"></div>

                              </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">10</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="10" value="<?php echo ((count($priceListWt)&& isset($priceListWt["10"]))?$priceListWt["10"]:"")?>"></div>

                              </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">15</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="15" value="<?php echo ((count($priceListWt)&& isset($priceListWt["15"]))?$priceListWt["15"]:"")?>"></div>

                              </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">20</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="20" value="<?php echo ((count($priceListWt)&& isset($priceListWt["20"]))?$priceListWt["20"]:"")?>"></div>

                              </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">25</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="25" value="<?php echo ((count($priceListWt)&& isset($priceListWt["25"]))?$priceListWt["25"]:"")?>"></div>

                              </div>
                              <div class="row mb-3 align-items-center">

                                  <div class="col-6 text-center">30</div>
                                  <div class="col-6 text-center"><input type="text" class="form-control price slab-price-wt" data-id="30" value="<?php echo ((count($priceListWt)&& isset($priceListWt["30"]))?$priceListWt["30"]:"")?>"></div>

                              </div>


                          </div>

                      </div>
                  </div>
              </div>
            <div class="row mt-3">
                <div class="col-8 text-center"> <button type="button" class="btn submit-btn" id="addSlabPrice">Submit</button></div>
            </div>

        </div>
    </div>
</div>
<script src="<?php echo $this->basePath().'/js/admin/add-slab-price.js?v=1';?>"></script>

