<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Bunched_Tales
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="main-heading">Bunched Tour List</div> <a class="text-end" href="<?php echo $this->basePath() . '/a_dMin/add-bunched-tour' ?>"><button type="button" class="btn add-btn">Add Bunched Tour </button></a>
            </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-bunched-tour-list', array(
                    'tourismList' => $placesList, 'totalCount' => $totalCount, 'type' => 'initialize'
                )); ?>

            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<?php echo $this->partial('/admin/admin/deleteModal', ['entityName' => 'Bunched Tale']); ?>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/bunched-tour-list.js' ?>"></script>