<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::Change_Password
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/change-password.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3">Change Password
            </div>
            <div class="row">
                <div class="col-12 col-lg-10">
                    <div class="row adding-form">
                        <div class="col-12 col-md-6 mb-4">
                            <div class="row">
                                <div class="col-12 mb-3"><label class="text-black-50">Current Password</label>
                                    <input type="password" class="form-control" id="Y3VycmVudFBhc3N3b3Jk" />
                                </div>
                                <div class="col-12 mb-3"><label class="text-black-50">New Password</label>
                                    <input type="password" class="form-control" id="bmV3UGFzc3dvcmQ" />
                                </div>
                                <div class="col-12"><label class="text-black-50">Confirm Password</label>
                                    <input type="password" class="form-control" id="Y29uZmlybVBhc3N3b3Jk" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mt-3">
                <div class="row">
                    <div class="col-sm-11 text-left">
                        <button type="button" class="btn submit-btn" id="Y2hhbmdlUGFzc3dvcmQ">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>