<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::TEx_Dashboard
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="main-heading mb-3"><a href="<?php echo $this->basePath() . '/a_dMin/executives' ?>"><i class="fa fa-arrow-left mr-2"></i></a> Commissions & Payments</div>
            </div>
            <div class="overflow-auto" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-commissions-payments-list', array(
                    'transactions' => $transactions, 'totalCount' => $totalCount, 'type' => 'initialize'
                )); ?>
            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end mt-3" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
    <input type="hidden" id="hid" name="hid" value="<?php echo base64_encode("id=". $id);?>" />
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/transactions.js' ?>"></script>