<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::Downloads
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/download-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Download details
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-5 col-lg-5 mb-4 mb-md-0">
                    <table class="table table-bordered booking-details">
                        <thead>
                        <tr>
                            <th class="bg-transparent color-333">
                                S.No.
                            </th>
                            <th class="bg-transparent color-333">
                                Place
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $i=1;foreach ($bookingDetails['place_details'] as $details ) {?>
                        <tr>
                            <td>
                                <?php echo $i;?>
                            </td>
                            <td>
                                <div class="text-capitalize">
                                    <?php echo $details['place_name']; ?>
                                </div>
                                <div class="small">
                                    <?php echo $details['city_name']; ?>, <?php echo $details['country_name']; ?>
                                </div>
                            </td>
                            <!--<td>
                                <div class="text-center">
                                    0
                                </div>
                            </td>-->
                        </tr>
                        <?php $i++; } ?>
                        <!-- <tr>
                            <td colspan="2" class="p-0">
                                <table class="table w-100 m-0">
                                    <tbody>
                                    <tr>
                                        <td colspan="2">
                                            <div class="d-flex justify-content-end">
                                                <div class="booking-price-text ml-auto">
                                                    Price (in INR)
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <?php //echo round(($bookingDetails['price']-($bookingDetails['price']-($bookingDetails['price']/1.18))),2); ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <div class="d-flex justify-content-end">
                                                <div class="booking-price-text ml-auto">
                                                    Tax (in INR)
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <?php //echo '+'.round(($bookingDetails['price']-($bookingDetails['price']/1.18)),2); ?>
                                            </div>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td colspan="2" class="no-border">
                                            <div class="d-flex justify-content-end">
                                                <div class="booking-price-text ml-auto">
                                                    Total Price (in INR)
                                                </div>
                                            </div>
                                        </td>
                                        <td class="no-border">
                                            <div class="text-center">
                                                <?php //echo $bookingDetails['price']; ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php //if($bookingDetails['discount_percentage']!=0) { ?>
                                    <tr>
                                        <td colspan="2" class="no-border">
                                            <div class="d-flex justify-content-end">
                                                <div class="booking-price-text ml-auto">
                                                    Discount Price (in INR)
                                                </div>
                                            </div>
                                        </td>
                                        <td class="no-border">
                                            <div class="text-center">
                                                <?php //echo '-'.round((($bookingDetails['price']*$bookingDetails['discount_percentage'])/100),2); ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2" class="no-border">
                                            <div class="d-flex justify-content-end">
                                                <div class="booking-price-text ml-auto">
                                                    Paid Amount (in INR)
                                                </div>
                                            </div>
                                        </td>
                                        <td class="no-border">
                                            <div class="text-center">
                                                <?php //echo ($bookingDetails['price']-(($bookingDetails['price']*$bookingDetails['discount_percentage'])/100)) ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php //} ?>
                                    </tbody>
                                </table>
                            </td>
                        </tr>  -->
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-7 col-lg-7">
                    <div class="">
                        <div class="p-3 custom-radius mb-3">
                            <div class="mb-3 d-flex">
                                <div class="color-999">Download date :</div>
                                <div class="px-2"><?php echo date("d-m-Y",strtotime($bookingDetails['created_at']))?></div>
                            </div>
                            <div class="mb-3 d-flex">
                                <div class="color-999">Download Id:</div>
                                <div class="px-2">#<?php echo $bookingDetails['booking_id']?></div>
                            </div>
                            <!-- <div class="mb-3 d-flex hidden">
                                <div class="color-999">Booking date :</div>
                                <div class="px-2">10-10-2019</div>
                            </div> -->
                            <div class="mb-3 d-flex">
                                <div class="color-999">Activation From :</div>
                                <div class="px-2"><?php echo date("d-m-Y",strtotime($bookingDetails['tour_date']))?></div>
                            </div>
                            <div class="d-flex">
                                <div class="color-999">Activation Till :</div>
                                <div class="px-2"><?php echo date("d-m-Y",strtotime($bookingDetails['expiry_date']))?></div>
                            </div>
                        </div>
                        <div class="p-3 custom-radius mb-3">
                            <div class="color-999">Tour Type</div>
                            <div class="text-capitalize"><?php echo \Admin\Model\PlacePrices::tour_type[$bookingDetails['tour_type']];?></div>
                        </div>
                        <!-- <div class="p-3 custom-radius mb-3">
                            <div class="row">
                                <div class="col-6">
                                    <div>
                                        No. of Users
                                    </div>
                                    <div>
                                        <?php echo $bookingDetails['no_of_users']; ?>
                                    </div>
                                </div>
                                <div class="col-6 text-capitalize d-none">
                                    <div class="text-right">
                                        <div class="d-inline-block text-center">
                                            <div class="text-decoration-underline">
                                                view mobile
                                            </div>
                                            <div class="text-decoration-underline">
                                                view password
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="">
                            <table class="table custom-radius">
                                <thead>
                                <tr>
                                    <th class="bg-transparent color-333">
                                        S.No.
                                    </th>
                                    <th class="bg-transparent color-333">
                                        mobile
                                    </th>
                                     <th class="bg-transparent text-center color-333">
                                         Password
                                     </th><th class="bg-transparent text-center color-333">
                                         Downloaded <br/>Date
                                     </th><th class="bg-transparent text-center color-333">
                                       Downloaded file <br/> Expiry
                                       Downloaded file <br/> Expiry
                                       Downloaded file <br/> Expiry
                                     </th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php $i=1; if(count($bookingDetails['user_list'])){ foreach ($bookingDetails['user_list'] as $details ) {?>
                                    <tr>
                                        <td>
                                            <?php echo $i;?>
                                        </td>
                                        <td>
                                            <div class="text-capitalize">
                                                <?php echo $details['mobile']; ?>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <?php echo $details['password']; ?>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <?php echo date("d-m-Y",strtotime($details['password_first_used_date'])); ?>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-center">
                                                <?php echo date("d-m-Y",strtotime($details['password_expiry_date'])); ?>
                                            </div>
                                        </td>
                                    </tr>
                                    <?php $i++;} }else{ ?>
                                <tr>
                                    <td class="text-center" colspan="5">
                                        No User Added
                                    </td>
                                </tr>
                                <?php } ?>
                                </tbody>
                            </table>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>