<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Countries
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/vendor/selectize.default.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/selectize.js"></script>
<script src="<?php echo $this->basePath() ?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-country.js?v=1.0"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3">Edit Country</div>
            <div class="row adding-form">
                <div class="col-6 mt-5">
                    <div class="col-10"><label class="text-black-50">Country</label>
                        <select class="" id="country">
                            <option value="">--select country--</option>
                            <?php foreach ($countries as $country) { ?>
                                <option value="<?php echo strtoupper($country['country_name']); ?>" <?php echo (strtolower($country['country_name']) == strtolower($countryDetails['country_name']) ? "selected" : ""); ?>>
                                    <?php echo strtoupper($country['country_name']); ?>
                                </option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="col-10">
                        <label class="text-black-50">Image Files</label>
                        <div class="position-relative w-100 image-upload-wrapper">
                            <input type="file" class="image-upload" name="image-file" multiple>
                            <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="image-preview-wrapper row">
                            <?php foreach ($imageFiles as $image) { ?>
                                <div class="col-sm-4 mt-2 position-relative image-preview overflow-hidden" data-id="<?php echo $image['tourism_file_id']; ?>">
                                    <img src="<?php echo $imageUrl . $image['file_path']; ?>" style="width: 100%;height: 100%">
                                    <span class="bg-white circle close-icon" data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1">
                                        <i class="fas fa-times position-absolute " data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1"></i>
                                    </span>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
            <input type="hidden" value="<?php echo $countryDetails['country_id']; ?>" id="countryId">
            <div class="row mt-3">
                <div class="col-sm-9 text-right"> <button type="button" class="btn submit-btn" id="addPlace">Submit</button></div>
            </div>
        </div>
    </div>
</div>