<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Places
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<script src="<?php echo $this->basePath() ?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath() ?>/js/imageResize.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-place.js?v=1.0.15"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath() . '/a_dMin/places' ?>"><i class="fa fa-arrow-left mr-2"></i></a> Edit Place</div>
            <div class="row">
                <div class="col-12 col-lg-10">
                    <div class="row adding-form">
                        <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                            <div class="col-12">
                                <label class="text-black-50">Country</label>
                                <select class="form-control" id="country" disabled>
                                    <option value="">--select country--</option>
                                    <?php foreach ($countries as $country) { ?>
                                        <option value="<?php echo $country['id']; ?>" <?php echo ($country['id'] == $placeDetails['country_id'] ? "selected" : ""); ?>><?php echo $country['country_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-12 <?php echo (!count($stateList) ? "d-none" : "") ?>" id="state-wrapper"><label class="text-black-50">State</label>
                                <select class="form-control" id="states" disabled>
                                    <option value="">--Select State--</option>
                                    <?php foreach ($stateList as $state) { ?>
                                        <option value="<?php echo $state['id']; ?>" <?php echo ($state['id'] == $placeDetails['state_id'] ? "selected" : ""); ?>><?php echo $state['state_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-12"><label class="text-black-50">City</label>
                                <select class="form-control" id="cities" disabled>
                                    <option value="">--Select City--</option>
                                    <?php foreach ($cityList as $city) { ?>
                                        <option value="<?php echo $city['id']; ?>" <?php echo ($city['id'] == $placeDetails['city_id'] ? "selected" : ""); ?>><?php echo $city['city_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <div class="col-12"><label class="text-black-50">Place Name</label>
                                <input type="text" class="form-control" id="place-name" value="<?php echo $placeDetails['place_name']; ?>" />
                            </div>
                            <div class="col-12">
                                <label class="text-black-50">Description</label>
                                <textarea class="form-control" id="description"><?php echo $placeDetails['place_description']; ?></textarea>
                            </div>
                            <div class="col-12"><label class="text-black-50">File name</label>
                                <input type="text" class="form-control upload-file-name" value="<?php echo $audioFiles[0]['file_name']; ?>">
                            </div>
                            <div class="col-12">
                                <label class="text-black-50">Image Files</label>
                                <div class="position-relative w-100 image-upload-wrapper">
                                    <input type="file" class="image-upload" name="image-file" multiple>
                                    <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                                </div>
                                <div class="col-12 mb-3">
                                    <div class="image-preview-wrapper row">
                                        <?php foreach ($imageFiles as $image) { ?>
                                            <div class="col-sm-4 mt-2 position-relative image-preview overflow-hidden" data-id="<?php echo $image['tourism_file_id']; ?>">
                                                <img src="<?php echo $imageUrl . $image['file_path']; ?>" style="width: 100%;height: 100%">
                                                <span class="bg-white circle close-icon" data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1">
                                                    <i class="fas fa-times position-absolute " data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1"></i></span>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <label class="text-black-50">Thumbnail Files</label>
                                <div class="position-relative w-100 image-upload-wrapper">
                                    <input type="file" class="tn-upload" name="thumbnail" id="thumbnail">
                                    <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                                </div>
                                <div class="col-12">
                                    <div class="tn-preview-wrapper row">
                                        <?php if (!is_null($tnFiles)) {
                                            foreach ($tnFiles as $image) { ?>
                                                <div class="col-sm-4 mt-2 position-relative tn-preview overflow-hidden" data-id="<?php echo $image['tourism_file_id']; ?>">
                                                    <img src="<?php echo $imageUrl . $image['file_path']; ?>" style="width: 100%;height: 100%">
                                                    <span class="bg-white circle tn-close-icon" data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1">
                                                        <i class="fas fa-times position-absolute " data-id="<?php echo $image['tourism_file_id']; ?>" data-edit="1"></i></span>
                                                </div>
                                        <?php }
                                        } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="text-capitalize heading mb-3">Audio</div>
                            <div class="" id="file-upload-wrapper">
                                <?php echo $this->partial("/admin/admin/file-upload-row", array('languages' => $languages, 'audioFiles' => $audioFiles, 'numberOfrows' => 0, "rowNumber" => 1)); ?>
                            </div>
                            <div class="row">
                                <div class="col-sm-12 text-end"> <a class="add-control"><i class="fas fa-plus-circle"></i>Add Audio</a></div>
                            </div>

                        </div>

                        <input type="hidden" value="<?php echo $placeDetails['place_id']; ?>" id="placeId">

                    </div>
                </div>
            </div>
            <div class="mt-2">
                <div class="col-sm-12 text-left"> <button type="button" class="btn submit-btn" id="addPlace">Submit</button></div>
            </div>
        </div>

    </div>
</div>