<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Sponsors_List
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-notify.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php 
            $subDefaultText="Minimum performance not met";
            $smsDefaultText="You have not met the  minimum performance criterion of purchasing 20 subscription passwords in past 60 days.\nYour discount privilege has been brought down from XX % to YY %.";
            $emailDefaultText="You have not met the  minimum performance criterion of purchasing 20 subscription passwords in past 60 days.\nYour discount privilege has been brought down from XX % to YY %.\nYou are suggested to improve your performance to get back your hard earned Discount status.";

            echo $this->partial("/application/index/app-header"); 
        ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/sponsors-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Notify Sponsor</div>
            <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                                <div class="row">
                                    <div class="col-12">
                                    <label class="text-black-50">Name: <?php echo $user['user_name'];?><label>                                        
                                    </div>
                                    <div class="col-12">
                                    <label class="text-black-50">Email: <?php echo $user['email'];?><label>                                        
                                    </div>
                                    <div class="col-12">
                                    <label class="text-black-50">Mobile: <?php echo "+".$user['mobile_country_code'].' '.$user['mobile'];?><label>                                        
                                    </div>
                                    <div class="col-12 mt-3">
                                        <label class="text-black-50">Subject</label>
                                        <textarea class="form-control w-auto h-auto" id="subTxt" rows="1" cols="100"><?php echo $subDefaultText; ?></textarea>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Notification Text</label>
                                        <textarea class="form-control w-auto" id="smsTxt" cols="100"><?php echo $smsDefaultText; ?></textarea>
                                    </div>
                                    <div class="col-12">
                                        <label class="text-black-50">Email Text</label>
                                        <textarea class="form-control w-auto" id="emailTxt" cols="100"><?php echo $emailDefaultText; ?></textarea>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="editNotify">Submit</button></div>
                                    <input type="hidden" id="huid" value="<?php echo $user['user_id']; ?>"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>