<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Bunched_Tales
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/vendor/sol.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script src="<?php echo $this->basePath() ?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-bunched-tour.js?v=1.0.3"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/bunched-tour-list'?>"><i class="fa fa-arrow-left mr-2"></i></a> Edit Bunched Tale</div>
            <div class="row">
                <div class="col-12 col-lg-10">
                    <div class="row adding-form">
                        <div class="col-lg-6 col-12">
                            <div class="col-12 mb-3"><label class="text-black-50">Tale Type</label>
                                <select class="form-control" id="taletype">
                                    <option value="">--select tale type--</option>
                                    <option value="<?php echo \Admin\Model\TourTales::tour_type_World_tour; ?>">World Tales</option>
                                    <option value="<?php echo \Admin\Model\TourTales::tour_type_India_tour; ?>">India Tales</option>
                                </select>
                            </div>
                            <?php $places = explode(",",$tourDetails[0]["place_name"]);
                                $placeids = explode(",",$tourDetails[0]["place_id"]); 
                                $i=0;?>
                            <div class="col-12 mb-3"><label class="text-black-50 text-capitalize">tales</label>
                                <select class="form-control" id="tales" name="tales" multiple>
                                    <?php foreach ($places as $place) { ?>
                                        <option value="<?php echo $placeids[$i]; ?>" selected><?php echo $place; ?></option>
                                    <?php $i++;} ?>
                                </select>
                            </div>
                            <div class="col-12"><label class="text-black-50">Tale Name</label>
                                <input type="text" class="form-control" id="tname" value="<?php echo $tourDetails[0]["tale_name"]; ?>"/>
                            </div>
                            <div class="col-12">
                                <label class="text-black-50">Description</label>
                                <textarea class="form-control" id="description"><?php echo $tourDetails[0]["tale_description"]; ?></textarea>
                            </div>
                            <div class="col-12">
                                <label class="text-black-50">Image Files</label>
                                <div class="position-relative w-100 image-upload-wrapper">
                                    <input type="file" class="image-upload" name="image-file">
                                    <span class="position-absolute upload_btn"><img class="w-100" src="<?php echo $this->basePath(); ?>/img/upload-img.svg"> </span>
                                </div>
                                <div class="col-12 mb-3">
                                    <div class="image-preview-wrapper row">
                                        <div class="col-sm-4 mt-2 position-relative image-preview overflow-hidden" data-id="<?php echo $tourDetails[0]['tourism_file_id']; ?>">
                                            <img src="<?php echo $imageUrl . $tourDetails[0]['file_path']; ?>" style="width: 100%;height: 100%">
                                            <span class="bg-white circle close-icon" data-id="<?php echo $tourDetails[0]['tourism_file_id']; ?>" data-edit="1">
                                                <i class="fas fa-times position-absolute " data-id="<?php echo $tourDetails[0]['tourism_file_id']; ?>" data-edit="1"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" value="<?php echo $tourDetails[0]['id']; ?>" id="taleId">
            </div>
            <div class="mt-2">
                <div class="row">
                    <div class="col-sm-12 text-left"> <button type="button" class="btn submit-btn" id="editbt">Submit</button></div>
                </div>
                <?php var_dump($tourDetails); ?>
            </div>
        </div>
    </div>
</div>