<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::TWISTT_ENABLERS,
            'activeTab' => \Application\Constants\Constants::TE_Plans
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<script src="<?php echo $this->basePath() ?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/edit-enabler-plan.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath() . '/a_dMin/enabler-plans' ?>"><i class="fa fa-arrow-left mr-2"></i></a> Edit Enabler Plan</div>
            <div class="row">
                <div class="col-12 col-lg-10">
                    <div class="row adding-form">
                        <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                        <div class="row">
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">TWISTT Duration</label>
                                    <input type="text" class="form-control" id="pd" name="pp" onfocusout="setPlanName()" value="<?php echo $plan['duration'] ?>"/>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">Plan Type</label>
                                    <select class="form-control" id="pt" name="pt" onchange="setPlanName()">
                                        <option value="P" <?php echo $plan['plan_type'] == \Admin\Model\EnablerPlans::Paid_Plan ? "selected" : ""; ?>>Paid Plan</option>
                                        <option value="C" <?php echo $plan['plan_type'] == \Admin\Model\EnablerPlans::Complimentary_Plan ? "selected" : ""; ?>>Complimentary Plan</option>
                                    </select>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">MTL</label>
                                    <input type="text" class="form-control" id="pp" name="pp" onfocusout="setPlanName()" value="<?php echo $plan['mtl'] ?>"/>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">Plan Name</label>
                                    <input type="text" class="form-control" id="pn" name="pn" disabled value="<?php echo $plan['plan_name'] ?>"/>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">Plan Price INR</label>
                                    <input type="text" class="form-control" id="ppinr" name="ppinr" value="<?php echo $plan['price_inr'] ?>"/>
                                </div>
                                <div class="col-sm-12 col-md-6">
                                    <label class="text-black-50">Plan Price USD</label>
                                    <input type="text" class="form-control" id="ppusd" name="ppusd" value="<?php echo $plan['price_usd'] ?>"/>
                                </div>
                                <div class="col-sm-12 col-md-6 mt-3">
                                    <div class="col-sm-9"> <button type="button" class="btn submit-btn" id="editEnbPlan">Submit</button></div>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" value="<?php echo $plan['id']; ?>" id="planId">
                    </div>
                </div>
            </div>
        </div>
    </div>