<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::TWISTT_ENABLERS,
            'activeTab' => \Application\Constants\Constants::TE_Profiles
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="main-heading mb-3"><a href="<?php echo $this->basePath() . '/a_dMin/enabler-purchases/'. base64_encode("id=".$eDetails['id']) ?>"><i class="fa fa-arrow-left me-2"></i></a> <?php echo $eDetails['username'] . ' - (' . $eDetails['country_phone_code'] . ')' . $eDetails['mobile_number'] . " - Tourists Details (Total: $totalCount)";?></div>
            </div>
            <div class="overflow-auto" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-sales-list', array('sales' => $sales, 'totalCount' => $totalCount, 'type' => 'initialize')); ?>
            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/enabler-sales.js' ?>"></script>