<?php 
    
?>
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Financial_statements

        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/sol.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/vendor/bootstrap-datetimepicker.min.css"/>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/moment.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/financial-statements.js?v=1"></script>
<!-- <script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script> -->
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="main-heading mb-3">Financial Statements</div>

            <div class="row">
                <div class="col-12 col-lg-12">
                    <div class="row adding-form">
                        <div class="col-12 col-md-4 pt-md-5 mb-4 mt-n1">
                            <div class="row">
                                <div class="col-6">
                                    <label class="text-black-50">From</label>
                                    <input type="text" class="form-control" id="start_date" value=""/>
                                </div>
                                <div class="col-6">
                                    <label class="text-black-50">To</label>
                                    <input type="text" class="form-control" id="end_date" value=""/>
                                </div>
                            </div>
                            <div class="mt-3">
                                <div class="form-check-inline">
                                    <label class="form-check-label" for="radio1">
                                        <input type="radio" class="form-check-input" id="radio1" name="optType" value="i" checked>Indian
                                    </label>
                                </div>
                                <div class="form-check-inline">
                                    <label class="form-check-label" for="radio2">
                                        <input type="radio" class="form-check-input" id="radio2" name="optType" value="f">Foreign
                                    </label>
                                </div>
                            </div>
                            <div class="mt-3">
                                <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn" id="getFS">Submit</button></div>
                            </div>
                            <div class="mt-3">
                            <form id="frmExp" method="post" action="<?php echo $this->basePath().'/excel.php';?>">
                                <div class="col-sm-9 text-left"> <button type="button" class="btn submit-btn d-none" id="export">Export</button></div>
                                <input type="hidden" id="exp" name="exp" value=""/>
                                <input type="hidden" id="from" name="from" value=""/>
                                <input type="hidden" id="to" name="to" value=""/>
                            </form>
                                <input type="hidden" id="baseurl" value="<?php echo $this->basePath()?>"/>
                            </div>
                        </div>
                        <div class="col-12 col-md-8 mb-4">
                            <div>
                                <div class="d-flex justify-content-between mb-4"> <div class="main-heading"><!-- Financial Statement --></div> </div>
                                <div class="" id="recordsList">
                                    <?php echo $this->partial('/admin/admin/load-financial-statements', array('financialStatement'=>$financialStatement,'totalCount'=>$totalCount,'type'=>'initialize')); 
                                    ?>
                                </div>
                                
                                <?php if($totalCount > 10){
                                    $paginationCount = ceil($totalCount / 10); ?>
                                    <ul class="pagination float-right" id="listPager"></ul>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>