<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>1

        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/admin/add-places.css">
<script src="<?php echo $this->basePath(); ?>/js/vendor/tinymce/tinymce.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-places.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
<div class="row">
    <div class="col-sm-3"><label class="text-black-50">Country</label>
        <select  class="form-control" id="country">
            <option value="">--select country--</option>

        <?php foreach ($countries as $country ) {?>
            <option value="<?php echo $country['id']; ?>"><?php echo $country['name']; ?></option>

        <?php } ?>
        </select></div>
    <div class="col-sm-3 state-wrapper hidden">
        <label class="text-black-50">State</label>
        <select  class="form-control" id="states"><option value=""></option></select>
    </div>
    <div class="col-sm-3 city-wrapper hidden">
        <label class="text-black-50">City</label>
        <select  class="form-control" id="cities"><option value=""></option></select>
    </div>
</div>
            <div class="row mt-3">
                <div class="col-sm-9">
                <label class="text-black-50">Place Name</label>
                <input type="text" class="form-control" id="place-name">
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-sm-9">
                    <label class="text-black-50">Place Description</label>
     <textarea class="form-control" id="description"></textarea>
                </div>
            </div>
            <div class="row mt-3">
                   <div class="col-sm-9">
                       <label class="text-black-50">Image Files</label>
                       <div class="position-relative w-100 image-upload-wrapper">
                           <input type="file" class="image-upload" name="image-file" multiple>
                           <div class="position-absolute image-preview-wrapper row">

                           </div>
                       </div>
                   </div>
            </div>
            <div class="mt-3" id="file-upload-wrapper">
                <?php echo $this->partial("/admin/admin/file-upload-row",array('languages'=>$languages,'numberOfrows'=>0,"rowNumber"=>1)); ?>

            </div>
            <div class="row mt-3"><div class="col-sm-9 text-right"> <a  class="add-control"><i class="fas fa-plus-circle"></i>Add Audio</a></div></div>

            <div class="row mt-3">
<div class="col-sm-9 text-right"> <button type="button" class="btn submit-btn" id="addPlace">Submit</button></div>
            </div>
        </div>
    </div>
</div>