<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>
            S.No.
        </th>
        <th data-placeholder="Invoice ID" data-input="booking_id">
            Invoice ID
        </th>
        <th data-placeholder="Transaction ID" data-input="transaction_id">
            Transaction ID
        </th>
        <th data-placeholder="Transaction date" data-input="transaction_date">
            Transaction date
        </th>
        <th data-placeholder="Currency">
            Currency
        </th>
        <th data-placeholder="Amount">
             Amount
        </th>
        <th data-placeholder="GST">
            GST
        </th>
        <th data-placeholder="Total Amount" data-input="amount">
            Total Amount
        </th>

    </tr>
    </thead>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {

    ?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>
    <?php if(count($paymentList))
    {

    $i=0;
    if(isset($offset))
    {
        $i=$offset;
    }

    foreach ($paymentList as $payment)
    { ?>
    <tr>
        <td>
            <div>
        <?php echo $i+1; ?>
            </div>
        </td>
        <td>
            <div>
                <?php echo $payment['booking_id']; ?>
            </div>
        </td>
        <td>
            <div>
                <?php echo $payment['payment_request_id']; ?>
            </div>
        </td>
        <td>
            <div>
                <?php echo date("d-m-Y H:i",strtotime($payment['created_at'])); ?>
            </div>
        </td>
        <td>
            <div>
                <?php echo $payment['currency']; ?>
            </div>
        </td>
        <td>
            <div>
                <?php $actualAmt = round(($payment['amount']) / (1 + ($payment['GST']/100)),2);
                    echo $actualAmt; ?>/-
            </div>
        </td>
        <td>
            <div>
                <?php echo $payment['amount'] - $actualAmt; ?>/-
            </div>
        </td>
        <td>
            <div>
                <?php echo $payment['amount']; ?>/-
            </div>
        </td>
    </tr>
        <?php $i++;
    }
    } else
    { ?>
        <tr ><td class="text-center" colspan="8">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) { ?>

    </tbody>
<?php } ?>
    <?php if(isset($type) && $type =='initialize') { ?>

</table>
<?php } ?>
