<?php if(isset($type) && $type =='initialize') { ?>
    <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="bookingListtable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="user name" data-input="user">user name</th>
        <th data-placeholder="mobile Number" data-input="mobile">Mobile Number</th>
        <th data-placeholder="Res.State" data-input="res_state">Res.State</th>
        <th data-placeholder="download id" data-input="booking_id">Download id</th>
        <th data-placeholder="download date" data-input="booking_date">download date</th>
        <th data-placeholder="tour type" data-type="select" data-input="tour_type" data-value='[{"value":"1","text":"india tour"},{"value":"2","text":"world tour"},{"value":"3","text":"city tour"},{"value":"4","text":"spiritual tour"},{"value":"5","text":"festival tour"}]'>Tour Type</th>
        <th data-placeholder="Activation From" data-input="activation_date"> Password Validity Start Date</th>
        <th data-placeholder="Activation Till" data-input="expiry_date"> Password Validity End Date</th>

    </tr>
<?php } ?>

<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
<?php } ?>
<?php if(count($bookingList)){
    $i=0;
    if(isset($offset))
    {
        $i=$offset;
    }

    foreach ($bookingList as $booking)
    { ?>
        <tr class="position-relative" data-id="<?php echo base64_encode("bookingDetials=".$booking['booking_id']); ?>">
            <td><?php echo $i+1; ?></td>
            <td data="<?php echo $booking['user_name']; ?>"><?php
                   /* if($booking['role']==\Admin\Model\User::Tour_Operator_role){
                       echo $booking['contact_person'].'('. $booking['company_name'].')';

                   }else if($booking['role']==\Admin\Model\User::Individual_role)
                   {
                       echo $booking['user_name'];
                   }else if($booking['role']==\Admin\Model\User::Tour_coordinator_role)
                   {
                       echo $booking['coordinator_name'].'('.  $booking['coordinator_company_name'].')';
                   } */
                   echo $booking['user_name'];
                 ?></td>
            <td><?php echo "+" . $booking['mobile_country_code']. $booking['mobile']; ?></td>
            <td><?php echo $booking['res_state']; ?></td>
            <td><?php echo $booking['booking_id']; ?></td>
            <td><?php echo date("d-m-Y",strtotime($booking['created_at'])); ?></td>
            <td class="text-capitalize"><?php echo \Admin\Model\PlacePrices::tour_type[$booking['tour_type']]; ?></td>
            <td><?php echo date("d-m-Y",strtotime($booking['tour_date'])); ?></td>
            <td><?php echo date("d-m-Y",strtotime($booking['expiry_date'])); ?></td>
        </tr>
        <?php $i++;
    }
} else { ?>
    <tr ><td class="text-center" colspan="9">No data</td></tr>
<?php  } ?>
<?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
<?php } ?>
<?php if(isset($type) && $type =='initialize') {?>

    </table>
    </div>
<?php } ?>