<?php if (isset($type) && $type == 'initialize') { ?>
    <table class="table table-bordered table-hover table-striped" id="table">
        <thead>
            <tr>
                <th>S.no</th>
                <th data-placeholder="Plan Name" data-input="plan_name">Plan Name</th>
                <th data-placeholder="Plan Type" data-input="plan_type">Plan Type</th>
                <th data-placeholder="Price (INR)" data-input="price_inr">Price (INR)</th>
                <th data-placeholder="Price (USD)" data-input="price_usd">Price (USD)</th>
                <th data-placeholder="CD (INR)" data-input="coupon_disc_inr">Coupon Disc (INR)</th>
                <th data-placeholder="CD (USD)" data-input="coupon_disc_usd">Coupon Disc (USD)</th>
                <th data-placeholder="CC (INR)" data-input="coupon_comm_inr">Coupon Comm (INR)</th>
                <th data-placeholder="CC (USD)" data-input="coupon_comm_usd">Coupon Comm (USD)</th>
                <th>Action</th>
            </tr>
        <?php } ?>

        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>
            <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
        <tbody>
        <?php } ?>
        <?php if (count($plansList)) {
            $i = 0;
            if (isset($offset)) {
                $i = $offset;
            }
            foreach ($plansList as $plan) { ?>
                <tr>
                    <td class="text-center"><?php echo $i + 1; ?></td>
                    <td class="text-center"><?php echo $plan['plan_name']; ?></td>
                    <td class="text-center"><?php echo $plan['plan_type']; ?></td>
                    <td class="text-center"><?php echo $plan['price_inr']; ?></td>
                    <td class="text-center"><?php echo $plan['price_usd']; ?></td>
                    <td class="text-center"><?php echo $plan['coupon_disc_inr']; ?></td>
                    <td class="text-center"><?php echo $plan['coupon_disc_usd']; ?></td>
                    <td class="text-center"><?php echo $plan['coupon_comm_inr']; ?></td>
                    <td class="text-center"><?php echo $plan['coupon_comm_usd']; ?></td>
                    <td>
                        <div class="d-flex">
                            <a class="action-icon " href="<?php echo $this->basePath() . '/a_dMin/edit-enabler-plan/' . base64_encode('enablerPlanId=' . $plan['id']) ?>">
                                <img src="<?php echo $this->basePath(); ?>/img/edit.png" class="img-fluid">
                            </a>
                            <div class="action-icon delete-enabler-plan" data-id="<?php echo $plan['id']; ?>">
                                <img src="<?php echo $this->basePath(); ?>/img/delete.png" class="img-fluid">
                            </div>
                        </div>
                    </td>
                </tr>
            <?php $i++;
            }
        } else { ?>
            <tr>
                <td class="text-center" colspan="7">No data</td>
            </tr>
        <?php  } ?>
        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>

        </tbody>
    <?php } ?>
    <?php if (isset($type) && $type == 'initialize') { ?>

    </table>
<?php } ?>