<?php if (isset($type) && $type == 'initialize') { ?>
    <table class="table table-hover table-striped border" id="table">
        <thead>
            <tr>
                <th>S.No</th>
                <?php if($ftt == \Admin\Model\TourTales::tour_type_Free_World_tour){?>
                <th data-placeholder="country" data-input="country">Country</th>
                <?php } else { ?>
                <th data-placeholder="state" data-input="state">State</th>
                <?php } ?>
                <th data-placeholder="city" data-input="city">City</th>
                <th data-placeholder="place" data-input="place">Place</th>
            </tr>
        <?php } ?>
        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>
            <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
        <tbody>
        <?php } ?>
        <?php
        if (count($placesList)) {
            $i = 0;
            if (isset($offset)) {
                $i = $offset;
            }
            foreach ($placesList as $places) { ?>
                <tr>
                    <td><?php echo $i + 1; ?></td>
                    <?php if($ftt == \Admin\Model\TourTales::tour_type_Free_World_tour){ ?>
                    <td class="text-capitalize"><?php echo $places['country_name']; ?></td>
                    <?php } else { ?>
                    <td class="text-capitalize"><?php echo $places['state_name']; ?></td>
                    <?php } ?>
                    <td class="text-capitalize"><?php echo $places['city_name']; ?></td>
                    <td class="text-capitalize"><?php echo $places['place_name']; ?></td>
                </tr>
                <?php $i++;
            }
        } else { ?>
            <tr>
                <td class="text-center" colspan="7">No data</td>
            </tr>
        <?php } ?>
        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>

        </tbody>
    <?php } ?>
    <?php if (isset($type) && $type == 'initialize') { ?>

    </table>
<?php } ?>