
<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="date" data-input="created_at">date</th>
        <th data-placeholder="count" data-input="no_of_users">count</th>
        <th data-placeholder="unit price" data-input="price">unit price</th>
        <th data-placeholder="total price" data-input="discount_percentage">total price</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($sponsorPasswords))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($sponsorPasswords as $sp) { ?>
            <tr>
                <td><?php echo $i+1; ?></td>
                <td><?php echo date("d-m-Y",strtotime($sp['created_at'])); ?></td>
                <td><?php echo $sp['pcount']; //$sp['no_of_users']?></td>
                <td><?php echo round(($sp['price']/$sp['pcount']),2); ?></td>
                <td><?php echo round($sp['price'],2); ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="7">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php } ?>
