<?php if(isset($type) && $type =='initialize') { ?>
<style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
    <th>S.no</th>
        <th data-placeholder="name" data-input="tourist_name" class="text-center">Name</th>
        <th data-placeholder="mobile" data-input="tourist_mobile" class="text-center">Mobile</th>
        <th data-placeholder="travel date" data-input="travel_date" class="text-center">Travel date</th>
        <th data-placeholder="upc" data-input="upc" class="text-center">UPC</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($tList))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($tList as $tl) { ?>
            <tr class="position-relative">
              <td><?php echo $i+1; ?></td>
              <td class="text-center"><?php echo $tl['tourist_name']; ?></td>
              <td class="text-center"><?php echo $tl['tourist_mobile']; ?></td>
              <td class="text-center"><?php echo date('d-m-Y', strtotime($tl['travel_date'])); ?></td>
              <td class="text-center"><?php echo $tl['upc']; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="7">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
</div>
<?php } ?>