
<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="date" data-input="created_at">date</th>
        <th data-placeholder="tour type" data-type="select" data-input="tour_type" data-value='[{"value":"1","text":"india tour"},{"value":"2","text":"world tour"},{"value":"3","text":"city tour"},{"value":"4","text":"spiritual tour"},{"value":"5","text":"package"}]'>Tour Type</th>
        <th data-placeholder="count" data-input="count">count</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($userDownloads))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($userDownloads as $ud) { ?>
            <tr>
                <td><?php echo $i+1; ?></td>
                <td ><?php echo date("d-m-Y",strtotime($ud['created_at'])); ?></td>
                <td class="text-capitalize"><?php echo \Admin\Model\PlacePrices::tour_type[$ud['tour_type']]; ?></td>
                <td><?php echo $ud['Expression1']; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="4">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php } ?>
