
<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="extTable">
    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="users" data-input="user_name">user name</th>
        <th data-placeholder="mobile" data-input="mobile">mobile number</th>
        <th data-placeholder="email" data-input="email">email</th>
        <th data-placeholder="state" data-input="res_state">state</th>
        <th data-placeholder="subscribed on" data-input="subscription_start_date">subscribed on</th>
        <th data-placeholder="subscription type" data-type="select" data-input="subscription_type" data-value='[{"value":"0","text":"ST User"},{"value":"2","text":"QUESTT"},{"value":"5","text":"TWISTT"}]'>subscription type</th>
        <th data-placeholder="total downloads" data-input="bookings_count">total downloads</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($usersList))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($usersList as $user) { 
            $setColor = "bg-info text-white";
            if(!is_null($user['subscription_end_date']) && $user['subscription_end_date'] != "0000-00-00"){
                $today = date('Y-m-d');
                if($user['subscription_end_date'] < $today)
                    $setColor = "bg-danger text-white";
                else{
                    if((int)$user['role'] == \Admin\Model\User::Individual_role)
                        $setColor = "bg-info text-white";
                    else
                        $setColor = "bg-success text-white";
                }

            }?>
            <tr class="position-relative <?php echo $setColor; ?>" data-id="<?php echo base64_encode("userDetails=".$user['user_id']); ?>">
                <td><?php echo $i+1; ?></td>
                <td><?php echo $user['user_name']; ?></td>
                <td><?php echo "+".$user['mobile_country_code'].$user['mobile']; ?></td>
                <td><?php echo $user['email']; ?></td>
                <td><?php echo $user['res_state']; ?></td>
                <td style="text-align:center;">
                    <?php 
                    if(!is_null($user['subscription_start_date']) && $user['subscription_start_date'] != "0000-00-00")
                        echo date("d-m-Y",strtotime($user['subscription_start_date'])); 
                    else 
                        echo "NA";?></td>
                <td style="text-align:center;"><?php 
                    if($user['subscription_type'] == "1" || $user['subscription_type'] == "0")
                        echo "ST User" . $user['subscription_type'];
                    if($user['subscription_type'] == "2") 
                        echo "QUESTT" . $user['subscription_type'];     
                    elseif($user['subscription_type'] == "5")
                        echo "TWISTT" . $user['subscription_type']; ?>
                </td>
                <td style="text-align:center;"><?php echo $user['booking_count']; ?></td>
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="8">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
    </div>
<?php } ?>
