
<?php if(isset($type) && $type =='initialize') { ?>
<table class="table table-bordered table-hover table-striped" id="tourOperatorList">    <thead>
    <tr>
        <th>S.no</th>
        <th data-placeholder="Tour Operator Name" data-input="tour_operator_name">Tour Operator Name
        </th>
        <th data-placeholder="Email" data-input="email"> Email </th>
        <th data-placeholder="Contact Person" data-input="contact_person"> Contact Person </th>
        <th data-placeholder="Mobile Number" data-input="mobile_number"> Mobile Number </th>

        <th>Status</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>

    <?php if(count($tourOperatorList))
    {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($tourOperatorList as $operator) { ?>
            <tr data-id="<?php echo base64_encode("tourOperator=".$operator['tour_operator_id'])?>">
                <td><?php echo $i+1; ?></td>
                <td><?php echo $operator['company_name']; ?></td>
                <td><?php echo $operator['email_id']; ?></td>
                <td><?php echo $operator['contact_person']; ?></td>
                <td><?php echo $operator['mobile_country_code'].$operator['mobile']; ?></td>
                <td><?php echo \Admin\Model\TourOperatorDetails::status[$operator['status']]; ?></td>
                <!--<td><div class="d-flex">
                        <a class="action-icon d-none" href="<?php /*echo $this->basePath().'/edit-country/'.base64_encode('tourismPlaceId='.$operator['id'])*/?>" >
                            <img src="<?php /*echo $this->basePath();*/?>/img/edit.png" class="img-fluid">
                        </a>
                        <div class="action-icon delete-place" data-id="<?php /*echo $state['id']; */?>">
                            <img src="<?php /*echo $this->basePath();*/?>/img/delete.png" class="img-fluid" >
                        </div>
                    </div></td>-->
            </tr>
            <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="8">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php } ?>
