<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-bordered table-hover table-striped" id="table">
    <thead>
    <tr class="text-nowrap">
        <th>S.no</th>
        <th class="text-center" data-placeholder="Transaction Date" data-input="purchase_date">Purchase Date</th>
        <th class="text-center" data-placeholder="Plan Name" data-input="plan_name">Plan Name</th>
        <th class="text-center" data-placeholder="Plan Price" data-input="actual_price">Plan Price</th>
        <th class="text-center" data-placeholder="Amount Paid" data-input="price_after_disc">Amount Paid</th>
        <th class="text-center" data-placeholder="Coupon Code" data-input="coupon_code">Coupon Code</th>
        <th class="text-center" data-placeholder="Exec Name" data-input="executive_name">Exec Name</th>
        <th class="text-center" data-placeholder="Exec Mobile" data-input="executive_mobile">Exec Mobile</th>
        <th class="text-center" data-placeholder="Invoice" data-input="invoice">Invoice</th>
        <th class="text-center" data-placeholder="Receipt" data-input="receipt">Receipt</th>
        <th class="text-center" data-placeholder="Licenses Bal" data-input="lic_bal">Licenses Bal</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>
    
    <?php if(count($purchases))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($purchases as $pur) { ?>
          <tr>
              <td><?php echo $i+1; ?></td>
              <td class="text-center"><?php echo date("d-m-Y",strtotime($pur['purchase_date'])); ?></td>
              <td class="text-center"><?php echo $pur['plan_name']; ?></td>
              <td class="text-center"><?php echo $pur['actual_price'] . " " .  $pur['currency']; ?></td>
              <td class="text-center"><?php echo $pur['price_after_disc'] . " " .  $pur['currency']; ?></td>
              <td class="text-center"><?php echo $pur['coupon_code']; ?></td>
              <td class="text-center"><?php echo $pur['executive_name']; ?></td>
              <td class="text-center"><?php echo $pur['executive_mobile']; ?></td>
              <td class="text-center"><a href="/a_dMin/enabler/invoice/<?php echo base64_encode('prId=' . $pur['prid']) ?>" target="_blank"><?php echo $pur['invoice']; ?></a></td>
              <td class="text-center"><a href="/a_dMin/enabler/receipt/<?php echo base64_encode('pid=' . $pur['prid']) ?>" target="_blank"><?php echo $pur['receipt']; ?></a></td>
              <td class="text-center"><a href="/a_dMin/enabler-sales/<?php echo base64_encode('id=' . $pur['id']) ?>"><?php echo $pur['lic_bal']; ?></a></td>
          </tr>
          <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="15">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<input id="eid" name="eid" type="hidden" value="<?php echo base64_encode('id='.$pur['enabler_id']) ?>">
</div>
<?php } ?>