<?php if (isset($type) && $type == 'initialize') { ?>
    <style>
        .table-condensed thead tr th {
            color: unset !important;
        }

        .calign input {
            text-align: center !important;
        }
    </style>
    
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped" id="extTable">
            <thead>
                <tr>
                    <th scope="col" class="sticky">Parameters</th>
                    <?php foreach ($splansList as $pricing){ ?>
                    <th scope="col" data-id="<?php echo base64_encode("pid=" . $pricing['id']); ?>"><?php echo $pricing['plan_name']; ?></th>
                    <?php } ?>
                </tr>
            </thead>
            <tbody>
            <?php $parameterNames = [
                'id'=> 'id',
                'plan_name' => 'Plan Name',
                'qsp_inr' => 'QUESTT Subscription (INR)',
                'qsp_usd' => 'QUESTT Subscription (US$)',
                'sqsp_inr' => 'Seasonal Price on QUESTT Subscription – INR',
                'sqsp_usd' => 'Seasonal Price on QUESTT Subscription – US$',
                'sqs_start_date' => 'Seasonal Price on QUESTT Subscription - Start Date',
                'sqs_end_date' => 'Seasonal Price on QUESTT Subscription - End Date',
                'qrp_inr' => 'QUESTT RENEWAL PRICE (INR)',
                'qrp_usd' => 'QUESTT RENEWAL PRICE (US$)',
                'questt_duration' => 'QUESTT Duration',
                'twistt_duration' => 'TWISTT Duration',
                'topp_inr' => 'TWISTT on-line purchase price (INR)',
                'topp_usd' => 'TWISTT on-line purchase price (US$)',
                'stsp_inr' => 'Seasonal Price of TWISTT Subscription - INR',
                'stsp_usd' => 'Seasonal Price of TWISTT Subscription - US$',
                'sts_start_date' => 'Seasonal Price on TWISTT Subscription - Start Date',
                'sts_end_date' => 'Seasonal Price on TWISTT Subscription - End Date',
                'tppp_inr' => 'TWISTT PW Purchase price (INR)',
                'tppp_usd' => 'TWISTT PW Purchase price (US$)',
                'max_pwds' => 'Max. Number of PWs to be entered for future ‘redeem’',
                'dp_inr' => 'Price of one discount coupon (INR)',
                'dp_usd' => 'Price of one discount coupon (US$)',
                'ccp_inr' => 'Price of one complementary coupon (INR)',
                'ccp_usd'=> 'Price of one complimentary coupon (US$)',
                'tax' => 'Taxes (%) on payable amount',
                'app_text' => 'App Text',
                'web_text' => 'Web Text',
                'cd_percentage' => 'Discount offered against Coupon on Price Amount',
                'active' => 'Active'
            ];
            $plancCount = count($splansList);
            foreach ($parameterNames as $key => $value) { ?>
                <tr>
                    <th scope="row" class="sticky bg-white"><?php echo $parameterNames[$key];?></th>
                <?php for ($i = 0; $i < $plancCount; $i++) { ?>
                    <td><?php echo $splansList[$i][$key];?></td>
                <?php } ?>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
<?php } ?>