<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-hover" id="extTable">
    <thead>
    <tr class="text-nowrap">
        <th>S.no</th>
        <th class="text-center" data-placeholder="Transaction Date">Redemption Date</th>
        <th class="text-center" data-placeholder="Coupon Code">Coupon Code</th>
        <th class="text-center" data-placeholder="Redeemer Name">Redeemer Name</th>
        <th class="text-center" data-placeholder="Redeemer Mobile">Redeemer Mobile</th>
        <th class="text-center" data-placeholder="Redeemer Paid">Redeemer Paid</th>
        <th class="text-center" data-placeholder="Comm. earned">Comm. earned</th>
        <th class="text-center" data-placeholder="Total Comm. earned">Total Comm. earned</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>
    
    <?php if(count($transactions))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($transactions as $tx) { 
          $color = "table-danger text-nowrap";
          ?>
          <tr class="<?php echo $color; ?>">
              <td><?php echo $i+1; ?></td>
              <td class="text-center"><?php echo date("d-m-Y",strtotime($tx['redeemed_on'])); ?></td>
              <td class="text-center"><?php echo $tx['coupon_code']; ?></td>
              <td class="text-center"><?php echo $tx['redeemer_name']; ?></td>
              <td class="text-center"><?php echo $tx['redeemer_mobile']; ?></td>
              <td class="text-center"><?php echo $tx['redeemer_paid']; ?></td>
              <td class="text-center"><?php echo $tx['commission_receivable']; ?></td>
              <td class="text-center"><?php echo $tx['total_earnings']; ?></td>
          </tr>
          <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="10">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>
</table>
</div>
<?php } ?>