<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::App_parameters
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-4">
            <div class="main-heading mb-3">Set App Parameters</div>
            <div class="row adding-form1">
                <div class="col-12 col-sm-12 col-md-4"">
                <div class=" row mt-3 align-items-center">
                    <div class="col-10">Total subscriber count: </div>
                    <div class="col-2 text-left"><?php echo $count; ?></div>
                </div>
                <div class="row mt-3 align-items-center">
                    <div class="col-10">Show subscriber count on splash screen</div>
                    <div class="col-2 text-left">
                        <input type="checkbox" id="ssc" name="ssc" value="0" <?php echo $parameters['SSC'] == "1" ? "checked" : ""; ?>>
                    </div>
                </div>
                <div class="row mt-3 align-items-center">
                    <div class="col-10">ADP</div>
                    <div class="col-2 text-left">
                        <input type="text" id="adp" name="adp" placeholder="Enter text here" value="<?php echo $parameters['ADP']; ?>" class="form-control">
                    </div>
                </div>
                <div class="row mt-3 align-items-center">
                    <div class="col-10">MTL</div>
                    <div class="col-2 text-left">
                        <input type="text" id="mtl" name="mtl" placeholder="Enter text here" value="<?php echo $parameters['MTL']; ?>" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-8 text-left"> <button type="button" class="btn submit-btn" id="btnChange">Submit</button></div>
        </div>
    </div>
</div>
</div>
<script src="<?php echo $this->basePath() . '/js/admin/parameters.js'; ?>"></script>