
<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab'=>\Application\Constants\Constants::Promoters_List
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">

<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
       
        <div class="main-container p-lg-4" >
        <div class="main-heading mb-3"><a class="goback" href="#" onclick="window.history.go(-1);"><i class="fa fa-arrow-left mr-2"></i></a> Transaction details of <?php echo $sponsorName['user_name']; ?></div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-sponsors-transactions', array('sponsorTransactions'=>$sponsorTransactions,'totalCount'=>$totalCount,'type'=>'initialize')); ?>
            </div>
            <?php if($totalCount > 10)
               {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-right" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<input type="hidden" class="records" value="<?php echo $totalCount; ?>">
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath().'/js/admin/sponsors-transactions.js?v=1.1'?>"></script>