<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'activeTab' => \Application\Constants\Constants::Subscription_plans
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>

        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="main-heading">Subscription Parameters</div>
            </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-subscription-plans', array(
                    'splansList' => $splansList, 'totalCount' => $totalCount, 'type' => 'initialize'
                )); ?>

            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/subscription-plans.js' ?>"></script>