<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab'=>\Application\Constants\Constants::Tales,
            'activeTab'=>\Application\Constants\Constants::Languages
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/selectize.default.css">


<script src="<?php echo $this->basePath(); ?>/js/vendor/selectize.js"></script>
<script src="<?php echo $this->basePath()?>/js/radialIndicator.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/add-language.js"></script>
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="main-heading mb-3"><a href="<?php echo $this->basePath().'/a_dMin/languages'?>"><i class="fa fa-arrow-left mr-2"></i></a> Add Language</div>
            <div class="row">
              <div class="col-12 col-lg-10">
                <div class="row adding-form">
                  <div class="col-12 col-md-6 pt-md-5 mb-4 mt-n1">
                    <div class="row">
                      <div class="col-12"><label class="text-black-50 mb-3">Language</label>
                        <select class="" id="language" >
                            <option value="">--select language--</option>
                            <?php foreach ($languageList as $language ) : 
                                $encodedID = base64_encode('languageId='.$language['id']);?>
                                <option value="<?php echo $encodedID; ?>"><?php echo strtoupper($language['language_name']); ?></option>
                            <?php endforeach; ?>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>        
            <div class="row mt-2">
                <div class="col-sm-12 text-left"> <button type="button" class="btn submit-btn" id="addLanguage">Submit</button></div>
            </div>
        </div>
    </div>
</div>