<?php if (isset($type) && $type == 'initialize') { ?>
    <table class="table table-bordered table-hover table-striped" id="table">
        <thead>
            <tr>
                <th>S.no</th>
                <th data-placeholder="country" data-input="country">Country</th>
                <th>Action</th>
            </tr>
        <?php } ?>

        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) {

        ?>
            <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
        <tbody>
        <?php } ?>

        <?php if (count($countryList)) {
            $i = 0;
            if (isset($offset)) {
                $i = $offset;
            }

            foreach ($countryList as $country) : ?>
                <tr>
                    <td><?= $i + 1 ?></td>
                    <td><?= $this->escapeHtml($country['country_name']) ?></td>
                    <td>
                        <div class="d-flex">
                            <!-- <a class="action-icon" href="<?php //echo $this->basePath() . '/a_dMin/edit-country/' . base64_encode('tourismCountryId=' . $country['id']) 
                                                                ?>" >
                        <img src="<?php //echo $this->basePath(); 
                                    ?>/img/edit.png" class="img-fluid">
                    </a> -->
                            <div class="action-icon delete-country" data-id="<?php echo $country['id']; ?>">
                                <img src="<?php echo $this->basePath(); ?>/img/delete.png" class="img-fluid">
                            </div>
                        </div>
                    </td>
                </tr>
            <?php $i++;
            endforeach;
        } else { ?>
            <tr>
                <td class="text-center" colspan="7">No data</td>
            </tr>
        <?php  } ?>
        <?php if (isset($type) && ($type == 'initialize' || $type == "search")) { ?>

        </tbody>
    <?php } ?>
    <?php if (isset($type) && $type == 'initialize') { ?>

    </table>
<?php } ?>