<div class="sidebar">
    <div class="side-panel" id="collapsibleNavbar">
        <?php echo $this->partial('/application/index/left-menu', array(
            'mainActiveTab' => \Application\Constants\Constants::Tales,
            'activeTab' => \Application\Constants\Constants::Places
        )); ?>
    </div>
</div>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<div class="wrapper">
    <div class="main-panel ">
        <?php echo $this->partial("/application/index/app-header"); ?>
        <div class="main-container p-lg-4">
            <div class="d-flex justify-content-between mb-4">
                <div class="main-heading">Places</div> <a class="text-end" href="<?php echo $this->basePath() . '/a_dMin/add-place' ?>"><button type="button" class="btn add-btn">Add Place</button></a>
            </div>
            <div class="" id="recordsList">
                <?php echo $this->partial('/admin/admin/load-places-list', array(
                    'tourismList' => $tourismList, 'totalCount' => $totalCount, 'type' => 'initialize'
                )); ?>
            </div>
            <?php if ($totalCount > 10) {
                $paginationCount = ceil($totalCount / 10); ?>
                <ul class="pagination float-end" id="listPager"></ul>
            <?php } ?>
        </div>
    </div>
</div>
<?php echo $this->partial('/admin/admin/deleteModal', ['entityName' => 'Place']); ?>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath() . '/js/admin/place-list.js' ?>"></script>