<?php


       if($status==1)
       {
           ?>
           <img src="<?php echo $this->basePath();?>/img/success.png"/>
           <div>Success ! Your Transaction Id is <?php echo $payment_id; ?></div>
       <?php }else {?>
           <img src="<?php echo $this->basePath();?>/img/fail.png"/>
           <div>Failed </div>
<?php } ?>
<script>
    var Base_url='<?php echo $this->basePath();?>';
    var status='<?php echo $status;?>';
    setTimeout(function(){
              window.location.href=Base_url+'/application/andriod-redirect?status='+status;
    },2000);
</script>
