<?php

$tbody='';
$discountPrice="";
$tpasswordbody='';
$pwdBody = '';
$i=0;
/* echo "<pre>";
print_r($data);
echo "</pre>"; */
if(!is_null($data['passwords'])){
  foreach ($data['passwords'] as $password) {
      $i++;
      if($data['bonus_flag']){
          if($i == count($data['passwords'])-4){
              $tpasswordbody .= '<tr><td colspan="2" style="padding:10px 3px;background:#20437b;color:#fff;text-align:center;">Bonus Passwords</td></tr>';
          }
      }
        if(count($data['passwords'])==$i)
        {
            $style='padding:8px 3px;border-right: solid 1px #999;text-align:center;';
            $userNamestyle='padding:8px 3px;text-align:center;';

        }else{
            $style='padding:8px 3px;border-right: solid 1px #999;border-bottom: solid 1px  #999;text-align:center;';
            $userNamestyle='padding:8px 3px;border-bottom: solid 1px  #999;text-align:center;';
        }
        $tpasswordbody .= '
        <tr style="text-align:center; ">
      <td style="'.$style.'">'.$i.'</td>
      <td style="'.$userNamestyle.'">STT / Booking Number : '.$data['booking_id'].' / Booking Date : '.date("d-m-Y",strtotime($data['created_at'])).' / Password Validity : '.date("d-m-Y",strtotime($data["expiry_date"])).' / Sponsor : '.$user_name.' / Password : '.$password.'</td>
    </tr>
      ';
      /* $tpasswordbody .= '
        <tr style="text-align:center; ">
      <td style="'.$style.'">'.$i.'</td>
      <td style="'.$userNamestyle.'">STT / '.\Admin\Model\PlacePrices::tour_type_pdf[$data["tour_type"]].' / Booking Number : '.$data['booking_id'].' / Booking Date : '.date("d-m-Y",strtotime($data['created_at'])).' / Password Validity : '.date("d-m-Y",strtotime($data["expiry_date"])).' / Sponsor : '.$user_name.' / Password : '.$password.'</td>
    </tr>
      '; */
  }
  $pwdBody = '<tr style="text-align:center;background:#20437b;color:#fff;">
  <td style="padding:10px 3px;background:#20437b;color:#fff;border-right: solid 1px #999;text-align:center;">SNo</td>
  <td style="padding:10px 3px;background:#20437b;color:#fff;text-align:center;">Booking And Password</td>
  </tr>'.$tpasswordbody;
}
/* else{
  $pwdBody = '<tr style="text-align:center;background:#20437b;color:#fff;">
  <td colspan="2" style="padding:10px 3px;background:#20437b;color:#fff;text-align:center;">STT Sponsorship details</td>
  </tr>
  <tr>
    <td colspan="2" style="padding:10px 30px;text-align:justify;">
    <div>Congratulations '. $data['user_name'] .' !!! </div><div>You have successfully registered as STT Sponsor.
    </div><div>Your sponsorship validity ends on '. date("d-m-Y",strtotime($data['subscription_end_date'])) .'
    </div></td>
  </tr>
  '; 
} */
echo   $tableHTml = '
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<table width="800" style="border:none;outline:none; font-family:verdana;font-size:13px;border:solid 1px #999;margin:0 auto;">
  <tr style="text-align:center;">
    <td colspan="2">
      <img src="https://www.susritourtales.com/img/user/logo.png" alt="susri Tour Tales" style="padding:10px 0;">
    </td>  
  </tr>'
  . $pwdBody .'
</table>
</body>
</html>';