
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
            <title>Susri Tour Tales Mail</title>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    font-size: 13px;
                }
                .container {
                    width: 100%;
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 20px;
                    border: 1px solid #ddd;
                }
                .header {
                    background-color: #eee;
                    color: white;
                    padding: 10px;
                    text-align: center;
                }
                .content {
                    margin: 20px 0;
                }
                .footer {
                    text-align: center;
                    color: #666;
                    font-size: 12px;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <img src="https://www.susritourtales.com/img/user/logo.png"/>
                </div>
                <div class="content">
                    <?php if($action == 'TEn_Registration_Otp'){ ?>
                        <div>Otp to verify your email for TWISTT Enabler registration is - <?php echo $data;?></div>
                    <?php } elseif($action == 'TEn_Password_Reset_Otp'){ ?>
                        <div>Otp to reset your password for TWISTT Enabler login is - <?php echo $data;?></div>
                    <?php } elseif($action == 'TEx_Registration_Mail'){ ?>
                        <p>Dear <?php echo $data['username']; ?></p>
                        <p>Your TWISTT Executive Registration is under processing by the Susri Tour Tales Admin.</p>
                        <p>You will recieve an approval email from us with login credentials after the processing is done.</p>
                    <?php } elseif($action == 'TEx_Registration_Approval'){ ?>
                        <p>Dear <?php echo $data['username']; ?></p>
                        <p>Your TWISTT Executive Registration is Approved.</p>
                        <p>Your login credentials for TWISTT Executive Portal are.</p>
                        <p>Username : <?php echo $data['user_login_id'] ?></p>
                        <p>Password : <?php echo $data['user_login_id'] ?></p>
                        <p>Do not forget to change your password immediately after you login.</p>
                    <?php } elseif($action == 'TEx_Banned'){ ?>
                        <p>Dear <?php echo $data['username']; ?></p>
                        <p>Your TWISTT Executive Registration (login in: <?php echo $data['user_login_id'] ?>) is banned by the Susri Tour Tales Admin.</p>
                        <p>Please contact the Admin for further details.</p>
                    <?php } elseif($action == 'TEx_unBanned'){ ?>
                        <p>Dear <?php echo $data['username']; ?></p>
                        <p>Your TWISTT Executive Registration (login in: <?php echo $data['user_login_id'] ?>) is revived by the Susri Tour Tales Admin.</p>
                        <p>You may login and reusme your services as TWISTT Executive.</p>
                    <?php } elseif($action == 'TWISTT_Enabled'){ ?>
                        <p>Dear <?php echo $data['tourist_name']; ?></p>
                        <p>M/s <?php echo $data['display_name']; ?> has sponsored free TWISTT subscription from <?php echo date('d-m-Y', strtotime($data['twistt_start_date'])); ?> to <?php echo date('d-m-Y', strtotime($data['twistt_end_date'])); ?>. Please install the app to avail the offer.</p>
                    <?php } ?>
                </div>
                <div class="m-3">
                    <p class="mt-3">Thank you</p>
                    <p>Susri Tour Tales</p>
                    <p>+91 90596 44412</p>
                    <p>www.susritourtales.com/</p>
                </div>
                <div class="footer">
                    <p>Susri Tour Tales &copy; 2019</p>
                </div>
            </div>
        </body>
    </html>
