<div class="container-fluid p-0 aboutus-banner">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            about us
        </div>
    </div>
</div>

<div class="container-fluid py-5 bg-white">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                <div class="mb-2">
                    <h3 class="d-sm-block d-md-none text-uppercase blue">about us</h3>
                    <div class="mission-caption color-000 mb-3">
                        If you are going on a tour... This is the first site to visit
                    </div>
                </div>
                <div class="color-000">
                    <p>
                        Susri Tour Tales is the creation by a group of like-minded educated individuals of different professions with common passion for undertaking creative and societal projects.
                    </p>
                    <div class="color-000 mission-text avant-md">
                        Susri Tour Tales (STT)
                    </div>
                    <div class="mb-2">
                        STT modestly desires to contribute its mite to 
                    </div>

                    <ul class="p-0 bullet-points">
                        <li>
                            highlight  the heritage of India
                        </li>

                        <li>
                            promote the tourism within  India
                        </li>
                        <li>
                            help the foriegn tourists to appreciate India better.
                        </li>
                        <li>
                            help the Indian tourists to appreciate the World better.
                        </li>
                        <li>
                            help any enterprising Indian to earn by spreading the App.
                        </li>
                    </ul> 
                </div>
            </div>
        </div>
    </div>
</div>

<div class="pt-5">
    <div class="container-fluid pb-5">
        <div class="container">
            <div class="row mx-n2">
                <div class="col-12 col-sm-12 col-md-6 mb-3 mb-md-0 px-2">
                    <div class="d-flex align-items-center justify-content-center border-radius-10 custom-shadow font-22 bg-white p-4 text-center font-italic avant-md color-000 h-100">
                        You can listen in English or Hindi or in your regional language.
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-6 px-2">
                    <div class="border-radius-10 custom-shadow bg-white d-flex flex-wrap p-3">
                        <!-- <button class="btn color-333 language-box">
                            Assamese
                        </button> -->
                        <button class="btn color-333 language-box">
                            bengali
                        </button>
                        <button class="btn color-333 language-box">
                            gujarathi
                        </button>

                        <button class="btn color-333 language-box">
                            kannada
                        </button>

                        <button class="btn color-333 language-box">
                            malayalam
                        </button>
                        <button class="btn color-333 language-box">
                            marathi
                        </button>
                        <button class="btn color-333 language-box">
                            Odiya
                        </button>
                        <button class="btn color-333 language-box">
                            punjabi
                        </button>
                        <button class="btn color-333 language-box">
                            tamil
                        </button>
                        <button class="btn color-333 language-box">
                            telugu
                        </button>
                        <button class="btn color-333 language-box">
                            urdu
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--<div class="container-fluid hear-fluid pb-5">
        <div class="container">
            <div class="text-uppercase avant-md tour-headding color-000 mb-3">
                Acknowledgements
            </div>
            <div class="owl-carousel" id="acknowledgements-slider">

                <div class="slider-box bg-white p-3">
                    <div class="color-333">
                        Susri Tour Tales express their gratitude to <b>Dr. Madhuri Devi</b> , Veena artist, <b>Shri Aravind Bharghav</b>, Mandolin artist and <b>Ms Mantha Sri Ramya</b> Violin artist,  for gracefully accepting and permitting us to  use their musical renderings in our App. 
                        We also acknowledge the services we have taken from freemusicarchives.org .
                    </div>
                </div>

                <div class="slider-box bg-white p-3">
                    <div class="color-333">
                        We appreciate  the services by the world wide <b>shutterstock.com</b>,   the doyen in   providing ‘Royalty Free pictures and music’  and  we thank them for the pictures that we have taken from their Albums. 
                    </div>
                </div>

                <div class="slider-box bg-white p-3">
                    <div class="color-333">
                        Susri Tour Tales  immensely thank  <b>Master Sri Hari, Smt Sanjana, Smt Vyjayanthi and Shri Raghuveer and Shri Subodh</b> for providing invaluable support in the software planning and development, recordings, post processing and many other technical and  logistic aspects of the Project.
                    </div>
                </div>

                <div class="slider-box bg-white p-3">
                    <div class="color-333">
                        Last but not the least, this Project would not have seen the light without the relentless efforts by <b>Shri Abhilash and his Team of M/s Tvisha Technologies, Hyderabad </b> who had  given this beautiful shape to the concept of <b>STT</b>. We are ever grateful to M/s Tvisha Technologies. 
                    </div>
                </div>

            </div>
        </div>
    </div>-->
</div>

<script>
    $(document).ready(function () {
        $('#acknowledgements-slider').owlCarousel({
            loop: true,
            dots: false,
            responsive: {
                0: {
                    items: 1
                },
                576: {
                    items: 2,
                    margin: 15
                },
                768: {
                    items: 3,
                    margin: 15
                },
                992: {
                    items: 3,
                    margin: 15
                }
            }
        });
    });
</script> 