<style>
    th {
        position: sticky;
        top: -1px;
        z-index: 1;
        background: #fff;
    }
</style>

<div class="container-fluid p-0 credits-banner">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            acknowledgements
        </div>
    </div>
</div>

<div class="container-fluid hear-fluid py-5">
    <div class="container">
        <!--<div class="text-uppercase tour-headding color-000 mb-3">
            Acknowledgements
        </div>-->
        <h3 class="d-sm-block d-md-none text-uppercase blue">Acknowledgements</h3>
        <div class="p-3 bg-white rounded mb-4 shadow-sm">
            <div class="mb-3 color-333">
                <b>The creators, authors and publishers</b> of the following sources of information are respectfully credited for  making available the knowledge base for the Project STT through their works. They are so large in number to be acknowledged individually. Our grateful salutations are offered to all of them.
            </div>
            <div class="mb-3 color-333">
                <b>Print sources</b> like – Scriptures, Encyclopaedia, Literature, Reference Books, Journals, Periodicals, Magazines, Media Publications, Travelogues , Official Brochures of Monuments etc; and  
            </div>
            <div class="color-333">
                <b>Electronic media sources</b> like- Official Websites of Monuments, Wikipedia, Tourism based Web Sites, UNESCO sites, Television programs, You Tube videos etc.
            </div>
        </div>
        <div class="p-3 bg-white rounded mb-4 shadow-sm">
            <div class="color-333 mb-3">
                Susri Tour Tales profusely thank the <b>translators and narrators</b> who are chiefly responsible for making this Project realisable and for their commitment, patience and enthusiasm. 
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div class="">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                            <th>
                                Translators
                            </th>
                            <th>
                                Narrators
                            </th>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        English
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            The original Scripts
                                            by
                                            Susri Tour Tales
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Subhadra
                                        </div>
                                        <div>
                                            Jesintha
                                        </div>
                                        <div>
                                            Kavya
                                        </div>
                                        <div>
                                            Sravani
                                        </div>
                                        <div>
                                            Tejaswani
                                        </div>
                                        <div>
                                            Srinath
                                        </div>
                                    </td>
                                </tr>
                                <!-- <tr>
                                    <td colspan="2" class="avant-md">
                                        ASSAMESE
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Rahman
                                        </div>
                                    </td>
                                    <td>
                                        <div>

                                        </div>
                                    </td>
                                </tr> -->
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        BENGALI
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Babita  Chakraborty
                                        </div>
                                        <div>
                                            Solanki Chakraborty
                                        </div>
                                        <div>
                                            Neelanjan
                                        </div>
                                        <div>
                                            Sharmila
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Subhamitra
                                        </div>
                                        <div>
                                            Sharmila
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        GUJARATHI
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Asha Patel
                                        </div>
                                        <div>
                                            Devyani Patel
                                        </div>
                                        <div>
                                            Jalpa
                                        </div>
                                        <div>
                                            Jigeesha
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Jalpa
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        HINDI
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Rimka
                                        </div>
                                        <div>
                                            Shaili
                                        </div>
                                        <div>
                                            Kavitha
                                        </div>
                                        <div>
                                            Suman
                                        </div>
                                        <div>
                                            Alka
                                        </div>
                                        <div>
                                            Sharada
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Rimka
                                        </div>
                                        <div>
                                            Shaili
                                        </div>
                                        <div>
                                            Suman
                                        </div>
                                        <div>
                                            Bhavana
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        KANNADA
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Aparna
                                        </div>
                                        <div>
                                            Rajesh
                                        </div>
                                        <div>
                                            Dr Shilpa
                                        </div>
                                        <div>
                                            Madhavi
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Aparna
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        MALAYALAM
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Aswathi
                                        </div>
                                        <div>
                                            Lekshmy
                                        </div>
                                        <div>
                                            Aiswaraya
                                        </div>
                                        <div>
                                            Krishna Sazi
                                        </div>
                                        <div>
                                            Nizamuddin
                                        </div>
                                        <div>
                                            Praveen
                                        </div>
                                        <div>
                                            Ragasri
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Veena
                                        </div>
                                        <div>
                                            Sony George
                                        </div>
                                        <div>
                                            Elizabeth
                                        </div>
                                        <div>
                                            Nizamuddin
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        MARATHI
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Maithilee
                                        </div>
                                        <div>
                                            Snehal
                                        </div>
                                        <div>
                                            Anuja
                                        </div>
                                        <div>
                                            Priya
                                        </div>
                                        <div>
                                            Manisha
                                        </div>
                                        <div>
                                            Jalpa
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Manisha
                                        </div>
                                        <div>
                                            Kanchan
                                        </div>
                                        <div>
                                            Ratna
                                        </div>
                                        <div>
                                            Vijayalakshmi
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        ODIYA
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Sabitri
                                        </div>
                                        <div>
                                            Monalisa
                                        </div>
                                        <div>
                                            Biroja
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Venkat
                                        </div>
                                        <div>
                                            Rekha
                                        </div>
                                        <div>
                                            Tanwin
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        PUNJABI
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Durgadass
                                        </div>
                                        <div>
                                            Sunaina
                                        </div>
                                        <div>
                                            Armaan
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Aarzoo
                                        </div>
                                        <div>
                                            Kunal
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        TAMIL
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Jesintha
                                        </div>
                                        <div>
                                            Gayatri
                                        </div>
                                        <div>
                                            Vaishnavi
                                        </div>
                                        <div>
                                            Varadarajan
                                        </div>
                                        <div>
                                            Leelashri
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Jesintha
                                        </div>
                                        <div>
                                            Gayatri
                                        </div>
                                        <div>
                                            Suguna
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        TELUGU
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Jyothi
                                        </div>
                                        <div>
                                            JB Nageswara Rao
                                        </div>
                                        <div>
                                            Subhadra
                                        </div>
                                        <div>
                                            Krishna Kanth
                                        </div>
                                        <div>
                                            MRK Murthy
                                        </div>
                                        <div>
                                            Jagannath
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            JB Nageswara Rao
                                        </div>
                                        <div>
                                            Ramakrishna
                                        </div>
                                        <div>
                                            Chaitanya
                                        </div>
                                        <div>
                                            Satyavani
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="avant-md">
                                        URDU
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div>
                                            Rukhsana
                                        </div>
                                        <div>
                                            Naheed
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            Ruksana
                                        </div>
                                        <div>
                                            Naheed
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-12 col-sm-12 col-md-6 mb-4">
                <div class="slider-box bg-white mb-2 p-4">
                    <div class="color-333">
                    Susri Tour Tales express their gratitude to <b>Dr. Madhuri Devi</b> , Veena artist, <b>Shri Aravind Bharghav</b>, Mandolin artist and <b>Smt Mantha Sri Ramya</b> Violin artist, for gracefully accepting and permitting us to use their musical renderings in our App. We also acknowledge the services we have taken from freemusicarchives.org .
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 mb-4">
                <div class="slider-box bg-white mb-2 p-4">
                    <div class="color-333">
                        We appreciate  the services by the world wide <b>shutterstock.com</b>, the doyen in providing ‘Royalty Free pictures and music’ and we thank them for the pictures that we have procured  from their Albums. 
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 mb-4">
                <div class="slider-box bg-white mb-2 p-4">
                    <div class="color-333">
                        Susri Tour Tales  immensely thank  <b>Master Sri Hari, Smt Sanjana, Smt Vyjayanthi , Shri Raghuveer and Shri Subodh </b> for providing invaluable support in the software planning and development, recordings, post processing and many other technical and  logistic aspects of the Project.
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-6 mb-4">
                <div class="slider-box bg-white mb-2 p-4">
                    <div class="color-333">
                        Last but not the least, this Project would not have seen the light without the relentless efforts by <b>Shri Abhilash and his Team at M/s Tvisha Technologies, Hyderabad and a Freelance Mobile App Developer Smt K. Manjary-</b> who had given this beautiful shape to the concept of <b>STT</b>. We are ever grateful to them. 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>