<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css">
<script src="<?php echo $this->basePath(); ?>/js/user/twistt-change-password.js?v=1.0.3"></script>
<div class="container-fluid my-5">
    <div class="container">
    <?php 
            $logoutUrl = $this->basePath() . '/twistt/executive/logout';
            if($adapters){ 
                if($userDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($userDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($userDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/exec-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_CHANGE_PASSWORD, 'logoutUrl'=>$logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5><?php echo "Change Password"; ?></h5>
                </div>
                <div>
                    <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 mb-4">
                                <div class="row">
                                    <div class="col-12 mb-3"><label class="text-black-50">Current Password</label>
                                        <input type="password" class="form-control" id="Y3VycmVudFBhc3N3b3Jk" />
                                    </div>
                                    <div class="col-12 mb-3"><label class="text-black-50">New Password</label>
                                        <input type="password" class="form-control" id="bmV3UGFzc3dvcmQ"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">Confirm Password</label>
                                        <input type="password" class="form-control" id="Y29uZmlybVBhc3N3b3Jk"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="mt-3">
                    <div class="row">
                        <div class="col-sm-11 text-left">
                            <button type="button" class="btn submit-btn text-white" id="Y2hhbmdlUGFzc3dvcmQ">Submit</button>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>