<div class="container-fluid">
    <div class="container">
        <div class="text-uppercase avant-md tour-headding color-000 mb-3 d-flex justify-content-between mt-3">
            <p class="mb-0"><?php echo \Admin\Model\PlacePrices::tour_type[$tourType]; ?></p>
        </div>




        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white">
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath();?>/">Home</a></li>
               <?php if($tourType==\Admin\Model\PlacePrices::tour_type_India_tour || $tourType== \Admin\Model\PlacePrices::tour_type_Spiritual_tour){ ?>
                   <li class="breadcrumb-item"><a href="<?php echo $this->basePath().'/state-list/'.\Admin\Model\PlacePrices::tour_type_url[$tourType];?>"><?php echo $countryName?></a></li>
               <?php } else{?>
                   <li class="breadcrumb-item"><a href="<?php echo $this->basePath().'/country-list/'.\Admin\Model\PlacePrices::tour_type_url[$tourType];?>"><?php echo $countryName; ?></a></li>
                <?php }?>
                <li class="breadcrumb-item active" aria-current="page">City</li>
            </ol>
        </nav>

        <div class="row mt-5">

                 <?php if($citiesList) {
                     foreach ($citiesList as $city) {
                     ?>
            <div class="col-12 col-md-3 mb-4">
                <div class="slider-box bg-white mb-3 position-relative">
                    <a href="<?php echo $this->basePath();?>/places-list/<?php echo \Admin\Model\PlacePrices::tour_type_url[$tourType];?>/<?php echo str_replace(" ","-",strtolower($city['city_name']))?>" class="stretched-link"></a>
                    <div class="slider-image position-relative" style="background: #f5f5f5 url('<?php echo $imageUrl.$city['file_path']; ?>') no-repeat center / cover">
                    </div>
                    <div class="p-3">
                        <div class="d-flex align-items-center">

                            <div style=" min-width: 0">
                                <div class="text-capitalize color-000 avant-bk tour-country text-truncate ">
                                    <?php echo $city['city_name']; ?>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

           <?php } } ?>



        </div>



    </div>
</div>