<div class="container-fluid p-0 contributor-banner">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            Be a Contributor
        </div>
    </div>
</div>
<div class="container-fluid my-4">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-8 mb-4 mb-lg-0">
                <div class="mb-2">
                    <h3 class="d-sm-block d-md-none text-uppercase blue">Be a Contributor</h3>
                    <div class="mission-caption color-000 mb-3">
                        WELCOME TO THE FAMILY OF SUSRI TOUR TALES.
                    </div>
                </div>
                <div class="color-000">
                    <p>
                    You can also be a member in this Mission of Monumental Awareness Programme of Indian Heritage...
                    </p>

                    <div class="mb-2 text-danger">
                    You can be a Translator...
                    </div>
                    <ul class="p-0 bullet-points">
                        <li>
                            In your mother tongue only.
                        </li>
                        <li>
                        With good proficiency in English & your mother tongue.
                        </li>
                        <li>
                        With freelance translation as a hobby.
                        </li>
                        <li>
                        With Liking for this Project and Commitment
                        </li>
                    </ul>

                    <div class="mb-2 text-danger">You can be a Narrator...</div>
                    <ul class="p-0 bullet-points">
                        <li>You need to be in Hyderabad for Live recording; <b>Foreigners can record and send.</b></li>
                        <li>Need to be fluent in reading your language.</li>
                        <li>Need to have clear voice, diction and expression.</li>
                        <li>Experience in voice over dubbing, radio channels etc preferable.</li>
                    </ul>
                    <div class="mb-2 text-danger">You can contribute Photographs...</div>
                    <ul class="p-0 bullet-points">
                        <li>Willing to share photos with Royalty free copy rights.</li>
                        <li>Personally shot photographs only.</li>
                        <li>Good quality and high resolution.</li>
                    </ul>
                    <div class="mb-2 text-danger">You can advise the places and share content...</div>
                    <ul class="p-0 bullet-points">
                    <li>You can suggest any locally popular places for inclusion.</li>
                    <li>You can share the popular legends and facts of the places.</li>
                    </ul>

                    <div class="mb-2 text-danger">Note:</div>
                    <ul class="p-0 bullet-points">
                        <li>Contributions are received subjected to their suitability to STT.</li>
                        <li>Being a contributor for STT is not a regular job.</li>
                        <li>It is only a past time hobby with nominal honorarium.</li>
                    </ul>
                    <!-- <p>Please mail to us at <a href="mailto:name@email.com">susritourtales@gmail.com</a>  with the subject  title as “Contributor”, for further information and screening.</p> -->
                    <p class="text-danger">FOREIGN LANGUAGE TRANSLATORS AND NARRATORS WILL BE ABLE TO HELP THEIR CITIZENS UNDERSTAND INDIA BETTER AND ENJOY THEIR VISIT.</p>
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <div class="custom-shadow border-radius-10 bg-white p-4">
                    <div class="text-capitalize avant-md tour-headding color-000 mb-3">
                        Contributor Form
                    </div>
                    <div class="mb-3">
                        <input type="text" placeholder="Name" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="name">
                    </div>
                    <div class="mb-3">
                        <input type="number" placeholder="Number" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="mobile">
                    </div>
                    <div class="mb-3">
                        <input type="email" placeholder="Email ID" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="email">
                    </div>
                    <div class="mb-3">
                        <textarea placeholder="Message" rows="4" class="form-control form-control-lg py-3 avant-md border-radius-10 custom-shadow" id="message"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="btn submit-btn text-capitalize px-4 py-3 text-white mt-3" id="submit">
                            submit
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath();?>/js/contributor.js"></script>