<div class="container-fluid my-4">
    <div class="container">
        <div class="row">
            <!-- <div class="col-12 col-sm-12 col-md-12 col-lg-8 mb-4 mb-lg-0"> -->
            <div class="col-12 text-center">
                <div class="custom-shadow border-radius-10 bg-white contact-bg position-relative overflow-hidden d-flex justify-content-center">
                    <img src="<?php echo $this->basePath(); ?>/img/user/contactus.jpg" class="img-fluid mx-auto">
                    <div class="contactus-text position-absolute bottom-0">
                        <div class="contact-text">
                            <strong>Thanks for visiting us .. please write your concerns and feedback here to serve you better</strong>
                        </div>
                        <div>
                            <strong>Email id: <a href="mailto:susritourtales@gmail.com">susritourtales@gmail.com</a></strong>
                        </div>
                    </div>
                </div>
            </div>
            <!-- <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <div class="custom-shadow border-radius-10 bg-white p-4">
                    <div class="text-capitalize avant-md tour-headding color-000 mb-3">
                        Enquiry Form
                    </div>
                    <div class="mb-3">
                        <input type="text" placeholder="Name" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="name">
                    </div>
                    <div class="mb-3">
                        <input type="number" placeholder="Number" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="mobile">
                    </div>
                    <div class="mb-3">
                        <input type="email" placeholder="Email ID" class="form-control form-control-lg py-4 avant-md border-radius-10 custom-shadow" id="email">
                    </div>
                    <div class="mb-3">
                        <textarea placeholder="Message" rows="4" class="form-control form-control-lg py-3 avant-md border-radius-10 custom-shadow" id="message"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="btn submit-btn text-capitalize px-4 py-3 text-white mt-3" id="submit">
                            submit
                        </button>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath();?>/js/faq.js"></script>