<section class="py-3 py-md-5 py-xl-8">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="mb-5">
          <h2 class="fw-bold text-center">TWISTT Enabler Login Error</h2>
          <h4 class="text-center m-3 fw-bold text-danger">
            <?php if(isset($message) && !empty($message)) 
                echo $message;
              else
                echo "Unknown Error !!!";
            ?>
          </h4>
          <p class="text-center m-2">Don't have an account? <a href="/twistt/enabler/register">Register as TWISTT Enabler</a></p>
          <p class="text-center m-2">Already have an account? <a href="/twistt/enabler/login">Login as TWISTT Enabler</a></p>
        </div>
      </div>
    </div>
  </div>
</section>