<?php
include 'vendor/autoload.php';

use Hybridauth\Hybridauth;

$hybridauth = new Hybridauth($config);
$adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.2">
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<style>
    body {
        background-color: #f5f5f5 !important;
        font-size: 14px !important;
    }

    .navbar-brand {
        justify-content: left;
    }

    .iti {
        display: block;
    }

    .hide {
        display: none;
    }
</style>
<div class="container-fluid my-5">
    <div class="container">
        <?php
        $logoutUrl = $this->basePath() . '/twistt/enabler/logout';
        if ($adapters) {
            if ($enablerDetails['oauth_provider'] == 'g') {
                $logoutUrl = $config['callback'] . "?logout=Google";
            } elseif ($enablerDetails['oauth_provider'] == 'f') {
                $logoutUrl = $config['callback'] . "?logout=Facebook";
            } elseif ($enablerDetails['oauth_provider'] == 'a') {
                $logoutUrl = $config['callback'] . "?logout=Apple";
            }
        }
        echo $this->partial('/enb-sidebar', array('activeTab' => \Application\Constants\Constants::TWISTT_TRACK_PLANS, 'logoutUrl' => $logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333">
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5>TWISTT Enabling</h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase"><u>TWISTT Enabler Details</u></h6>
                    <div class="row">
                        <div class="col-8">
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Name: " . $enablerDetails['username']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Company Name: " . $enablerDetails['company_name']; ?></div>
                            </div>
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Mobile: (" . $enablerDetails['country_phone_code'] . ")" . $enablerDetails['mobile_number']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Email: " . $enablerDetails['email']; ?></div>
                            </div>
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Spl Discount: " . $enablerDetails['stt_disc'] . "%"; ?></div>
                                <div class="col-sm-12 col-md-6"></div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="row pt-1"><img src="<?php echo $imageUrl . $enablerDetails['photo_url']; ?>" style="width:100px !important;"></div>
                        </div>
                    </div>
                </div>
                <div class="border-radius-10 custom-shadow p-4 color-333 my-3" style="background-color:#d1e7dd;">
                    <h5 class="font-weight-bold text-uppercase primary-text"><u>Sell TWISTT Subscriptions</u></h5>
                    <form id="sellForm" enctype="multipart/form-data" novalidate>
                        <div class="row pt-3">
                            <div class="col-sm-12 col-md-6">
                                <label for="selPlan" class="form-label">Select Plan</label>
                                <select class="form-control" id="selPlan" name="selPlan" required>
                                    <?php foreach ($epl as $e) { ?>
                                        <option value="<?php echo $e['id']; ?>"><?php echo $e['plan_name'] . "-" . $e['id'] . " (" . $e['lic_bal'] . ")"; ?></option>
                                    <?php } ?>
                                </select>
                                <div class="invalid-feedback">Please select plan.</div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <label for="tname" class="form-label">Tourist Name</label>
                                <input type="text" class="form-control w-100" id="tname" name="tname" value="" required>
                                <div class="invalid-feedback">Please provide tourist name.</div>
                            </div>
                        </div>
                        <div class="row pt-3">
                            <div class="col-sm-12 col-md-6">
                                <label for="mobile" class="form-label">Tourist Mobile</label>
                                <div class="form-floating mb-2">
                                    <input type="tel" class="form-control mb-1" id="mobile" name="mobile" placeholder="Mobile Number" autocomplete="username">
                                    <div id="valid-msg" class="hide text-success mt-2">✓ Valid</div>
                                    <div id="error-msg" class="hide text-danger mt-2"></div>
                                    <input type="hidden" id="country">
                                </div>
                            </div>
                            <div id="divEmail" class="col-sm-12 col-md-6">
                                <label for="email" class="form-label">Tourist Email</label>
                                <input type="text" class="form-control w-100" id="email" name="email" value="">
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <label for="datepicker" class="form-label">Tour Date</label>
                                <input type="text" class="form-control" id="datepicker" name="datepicker" required>
                                <div class="invalid-feedback">Please provide tour date.</div>
                            </div>
                            <div class="col-sm-12 col-md-6 mt-3">
                                <button type="submit" class="btn primary-btn mt-3" id="btn" name="btn">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="bg-white border-radius-10 custom-shadow p-4 color-333 my-3">
                    <div class="" id="recordsList">
                        <?php echo $this->partial("/load-sales-list", array('sales' => $sales, 'totalCount' => $totalCount, 'type' => 'initialize')); ?>
                    </div>
                    <?php if ($totalCount > 10) {
                        $paginationCount = ceil($totalCount / 10); ?>
                        <ul class="pagination justify-content-end mt-3" id="listPager"></ul>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/track-plans.js?v=1.0.2"></script>