<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css?v=1.0.1">
<style>
    body{
        background-color: #f5f5f5 !important;
        font-size: 14px !important;
    }
    .navbar-brand{
        justify-content: left;
    }
</style>
<div class="container-fluid my-5">
    <div class="container">
        <?php 
            $logoutUrl = $this->basePath() . '/twistt/enabler/logout';
            if($adapters){ 
                if($enablerDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($enablerDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($enablerDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/enb-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_TRACK_PURCHASES, 'logoutUrl'=>$logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5>Track Plans</h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase"><u>TWISTT Enabler Details</u></h6>
                    <div class="row">
                        <div class="col-8">
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Name: " . $enablerDetails['username']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Company Name: " . $enablerDetails['company_name']; ?></div>
                            </div>
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Mobile: (" . $enablerDetails['country_phone_code'] . ")" . $enablerDetails['mobile_number']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Email: " . $enablerDetails['email']; ?></div>
                            </div>
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Spl Discount: " . $enablerDetails['stt_disc'] . "%"; ?></div>
                                <div class="col-sm-12 col-md-6"></div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="row pt-1"><img src="<?php echo $imageUrl.$enablerDetails['photo_url']; ?>" style="width:100px !important;"></div>
                        </div>
                    </div>
                </div>
                <div class="bg-white border-radius-10 custom-shadow p-4 color-333 my-3">
                    <div class="" id="recordsList">
                        <?php echo $this->partial("/load-purchases-list", array('purchases'=>$purchases,'totalCount'=>$totalCount,'type'=>'initialize')); ?>
                    </div>
                    <?php if($totalCount > 10){
                        $paginationCount = ceil($totalCount / 10); ?>
                        <ul class="pagination justify-content-end mt-3" id="listPager"></ul>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-transactions.js"></script>