<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/login.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.3">
<style>
  .iti{
    display: block;
  }
  .hide{
    display: none;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js"></script>
<div class="container my-5">
  <h1 class="text-center">TWISTT Enabler Registration Form</h1>
  <p class="text-center mb-5">Already have an account? <a href="/twistt/enabler/login">Login as TWISTT Enabler</a></p>
  <form id="registrationForm" enctype="multipart/form-data" novalidate>
   <div class="row g-3" id="userDetails">
      <div class="col-md-6 udetails">
        <label for="name" class="form-label">Name*</label>
        <input type="text" class="form-control" id="name" name="name" required>
        <div class="invalid-feedback">Please provide your name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="cname" class="form-label">Sponsoring Company Name</label>
        <input type="text" class="form-control" id="cname" name="cname">
      </div>
      <div class="col-md-6 udetails">
        <label for="country" class="form-label">Country / State *</label>
        <input type="text" class="form-control" id="country" name="country" required>
        <div class="invalid-feedback">Please provide a valid Country name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="city" class="form-label">City / Town *</label>
        <input type="text" class="form-control" id="city" name="city" required>
        <div class="invalid-feedback">Please provide City name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="photo" class="form-label">Logo of Sponsoring Company / Profile Pic of TWISTT Enabler *</label>
        <input type="file" class="form-control mb-3" id="photo" name="photo" required>
        <img id="preview" alt="Photo Preview" height="100" width="100">
        <div class="invalid-feedback">Please upload your photo.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="email" class="form-label">Email* <span class="text-danger" style="font-size:10px;">(all communication will be sent to this email)</span></label>
        <input type="email" class="form-control" id="email" name="email" required>
        <div class="invalid-feedback">Please provide a valid email address.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="mobile" class="form-label">Mobile*</label>
        <input type="tel" class="form-control" id="mobile" name="mobile" pattern="[0-9]*" required>
        <input type="hidden" id="country">
        <div class="invalid-feedback">Please provide valid mobile number.</div>
      </div>
      <div class="col-md-6 udetails">
        <div id="divBtn" class="pt-3 text-start">
            <button type="button" class="btn primary-btn mt-3" id="btnOtp" name="btnOtp">Send Otp</button>
            <div id="valid-msg" class="hide text-success">✓ Valid</div>
            <div id="error-msg" class="hide text-danger"></div>
        </div>
      </div>
      <div id="divOtp" class="col-md-6">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-9">
            <label for="otp" class="form-label">Enter Otp</label>
            <input type="text" class="form-control" id="otp" name="otp">
          </div>
          <div class="col-sm-12 col-md-12 col-lg-3 pt-3">
            <button type="button" class="btn primary-btn mt-3" id="btnVerify" name="btnVerify">Verify Otp</button>
          </div>
        </div>
      </div>
      <div class="col-md-12 udetails">
        <input type="checkbox" id="cbtnc" name="cbtnc" disabled><span class="ms-3">I read and accept the terms and conditions</span>
      </div>
    </div>
    <button type="submit" class="btn submit-btn mt-5" id="register" disabled>Register</button>
  </form>
</div>
<div class="login-bg"></div>
<script src="<?php echo $this->basePath(); ?>/js/user/add-enabler.js?v=1.0.4"></script>