<div class="sidebar">
    <a href="<?php echo $this->basePath();?>/twistt/enabler/buy-plans" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_BUY_PLANS?'active':'');?>">Buy Plans</a>
    <a href="<?php echo $this->basePath();?>/twistt/enabler/track-purchases" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_PURCHASES?'active':'');?>">Track Plans</a>
    <a href="<?php echo $this->basePath();?>/twistt/enabler/track-plans" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_PLANS?'active':'');?>">TWISTT Enabling</a>
    <a href="<?php echo $this->basePath();?>/twistt/enabler/profile" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EN_PROFILE?'active':'');?>">Check/EditProfile</a>
    <a href="<?php echo $this->basePath();?>/twistt/enabler/change-password" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EN_CHANGE_PASSWORD?'active':'');?>">Change Password</a>
    <a href="<?php echo $this->basePath();?>/twistt/enabler/terms" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EN_TERMS?'active':'');?>">Terms</a> 
    <a href="<?php echo $logoutUrl;?>" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EN_LOGOUT?'active':'');?>">Logout</a>
</div>