<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath() ?>/css/main.css">
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css?v=1.0.2">
<style>
    body{
        background-color: #f5f5f5 !important;
        font-size: 14px !important;
    }
</style>
<div class="container-fluid my-5">
    <div class="container">
        <?php 
            $logoutUrl = $this->basePath() . '/twistt/executive/logout';
            if($adapters){ 
                if($userDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($userDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($userDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/exec-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_TRACK_COUPONS, 'logoutUrl'=>$logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5><?php echo "TWISTT Executive Track Coupons"; ?></h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase p-2"><u>TWISTT Executive Details</u></h6>
                    <div class="row">
                        <div class="col-12">
                            <div class="row pt-1">
                            <div class="col-sm-12 col-md-6"><?php echo "Name: " . $userDetails['username']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Mobile: (" . $userDetails['country_phone_code'] . ")" . $userDetails['mobile_number']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "QUESTT Expires on: " . $qed; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Commission: " . $bankDetails['commission_percentage'] . "%"; ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bg-white border-radius-10 custom-shadow p-4 color-333 my-3">
                    <div class="" id="recordsList">
                        <?php echo $this->partial("/load-coupons-list", array('coupons'=>$coupons,'totalCount'=>$totalCount,'type'=>'initialize')); ?>
                    </div>
                    <?php if($totalCount > 10){
                        $paginationCount = ceil($totalCount / 10); ?>
                        <ul class="pagination justify-content-end mt-3" id="listPager"></ul>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/pagination.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-track-coupons.js"></script>