<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.2">
<section class="py-3 py-md-5 py-xl-8">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="mb-5">
            <h2 class="fw-bold text-center">TWISTT Executive Terms and Conditions</h2>
            <div class="text-center mb-3 text-danger" style="font-weight:900;">Please accept the Terms mentioned below to proceed to Register as TWISTT Executive</div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <ol>
            <li>The active subscription status as QUESTT member is the necessary condition for you to function as TWISTT Executive at any point of time.</li>
            <li>Both the ‘complimentary coupons’ and ‘discount coupons’ purchased by you as TEx should be redeemed by the TWISTT Enablers before the QUESTT expiry date.</li>
            <li>The validity of coupons gets extended if you renew your QUESTT subscription in time.</li>
            <li>The onus of responsibility of giving/updating your profile particulars correctly, including the bank account details- lies with you.</li>
            <li>The commission amount will be remitted to you only after the accumulated amount crosses certain threshold, which will be informed to you by mail after successful registration. Requests for part payments will not be entertained.</li>
            <li>No requests will be entertained on the ‘% commission’ granted to you and about the subsequent increments given by STT.</li>
            <li>In case it is noticed that you are repeatedly issuing invalid coupons to your TWISTT Enablers, your services are liable to be discontinued.</li>
            <li>Similarly, if you repeatedly issue ‘complimentary coupons’ without leading to any business, your services are liable to be discontinued.</li>
            <li>You are entitled to receive your pending commission in full even if STT discontinues your services as TWISTT Executive.</li>
        </ol>
      </div>
      <div class="col-1"></div>
    </div>
    <div class="row">
        <div class="col-12 text-end">
            <a class="btn primary-btn text-white" href="/twistt/executive/register">Accept and Proceed</a>
        </div>
    </div>
  </div>
</section>