<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/login.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.2">
<style>
  .iti{
    display: block;
  }
  .hide{
    display: none;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js"></script>
<div class="container my-5">
  <h1 class="text-center">TWISTT Executive Registration Form</h1>
  <p class="text-center mb-5">Already have an account? <a href="/twistt/executive/login">Login as TWISTT Executive</a></p>
  <form id="registrationForm" enctype="multipart/form-data" novalidate>
    <div class="row g-3 mb-3" id="loginType">
      <div id="divLoginId" class="col-md-6">
        <label for="lid" class="form-label" id="lblLid">Enter your login id (that you use to login into STT app)</label>
        <p class="text-danger" style="font-size:10px;">(If your login id is mobile number, it should be entered along with country code)</p>
        <input type="text" class="form-control" id="lid" name="lid">
        <button type="button" class="btn primary-btn mt-3" id="btnQUESTT" name="btnQUESTT">Check</button>
      </div>
    </div>
    <div class="row g-3" id="userDetails">
      <div id="divMobile" class="col-md-6">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-9">
            <label for="mobile" class="form-label">Mobile*</label>
            <input type="tel" class="form-control" id="mobile" name="mobile" pattern="[0-9]*" required>
            <input type="hidden" id="country">
            <div class="invalid-feedback">Please provide valid mobile number.</div>
          </div>
          <div class="col-sm-12 col-md-12 col-lg-3">
            <div id="divBtn" class="pt-3 text-end">
              <button type="button" class="btn primary-btn mt-3" id="btnOtp" name="btnOtp">Send Otp</button>
              <div id="valid-msg" class="hide text-success">✓ Valid</div>
              <div id="error-msg" class="hide text-danger"></div>
            </div>
            <div id="divCM" class="pt-3 text-end">
              <button type="button" class="btn primary-btn mt-3" id="changeMobile" name="changeMobile">Edit Mobile</button>
            </div>
          </div>
        </div>
      </div>
      <div id="divOtp" class="col-md-6">
        <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-9">
            <label for="otp" class="form-label">Otp</label>
            <input type="text" class="form-control" id="otp" name="otp">
          </div>
          <div class="col-sm-12 col-md-12 col-lg-3 pt-3">
            <button type="button" class="btn primary-btn mt-3" id="btnVerify" name="btnVerify">Verify Otp</button>
          </div>
        </div>
      </div>
      <div class="col-md-6 udetails">
        <label for="email" class="form-label">Email* <span class="text-danger" style="font-size:10px;">(all communication will be sent to this email)</span></label>
        <input type="email" class="form-control" id="email" name="email" required>
        <div class="invalid-feedback">Please provide a valid email address.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="name" class="form-label">Name*</label>
        <input type="text" class="form-control" id="name" name="name" required>
        <div class="invalid-feedback">Please provide your name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="gender" class="form-label">Gender</label>
        <select class="form-select" id="gender" name="gender">
          <option value="">Select...</option>
          <option value="male">Male</option>
          <option value="female">Female</option>
          <option value="other">Other</option>
        </select>
      </div>
      <div class="col-md-6 udetails">
        <label for="city" class="form-label">City*</label>
        <input type="text" class="form-control" id="city" name="city" required>
        <div class="invalid-feedback">Please provide City name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="state" class="form-label">State*</label>
        <input type="text" class="form-control" id="state" name="state" required>
        <div class="invalid-feedback">Please provide State name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="country" class="form-label">Country*</label>
        <input type="text" class="form-control" id="country" name="country" required>
        <div class="invalid-feedback">Please provide a valid Country name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="ifsc" class="form-label">Bank Name*</label>
        <input type="text" class="form-control" id="bankName" name="bankName" required>
        <div class="invalid-feedback">Please provide a valid Bank Name.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="bankAccount" class="form-label">Bank Account*</label>
        <input type="password" class="form-control" id="bankAccountConf" name="bankAccountConf" required>
        <div class="invalid-feedback">Please provide bank account number.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="bankAccount" class="form-label">Confirm Bank Account*</label>
        <input type="text" class="form-control" id="bankAccount" name="bankAccount" required>
        <div class="invalid-feedback">Please provide bank account number.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="ifsc" class="form-label">IFSC*</label>
        <input type="text" class="form-control" id="ifsc" name="ifsc" required>
        <div class="invalid-feedback">Please provide a valid IFSC code.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="photo" class="form-label">Passport Size Photo*</label>
        <input type="file" class="form-control mb-3" id="photo" name="photo" required>
        <img id="preview" alt="Photo Preview" height="100" width="100">
        <div class="invalid-feedback">Please upload your photo.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="aadhar" class="form-label">Aadhar*</label>
        <input type="file" class="form-control mb-3" id="aadhar" name="aadhar" required>
        <img id="apreview" alt="Adhar Preview" height="150" width="200">
        <div class="invalid-feedback">Please upload your aadhar scan.</div>
      </div>
      <div class="col-md-6 udetails">
        <label for="pan" class="form-label">Pan card*</label>
        <input type="file" class="form-control mb-3" id="pan" name="pan" required>
        <img id="ppreview" alt="Pan Preview" height="150" width="200">
        <div class="invalid-feedback">Please upload your pan card scan.</div>
      </div>
    </div>
    <button type="submit" class="btn submit-btn mt-5" id="register">Register</button>
  </form>
</div>
<div class="login-bg"></div>
<script src="<?php echo $this->basePath(); ?>/js/user/add-executive.js?v=1.0.17"></script>