<div class="sidebar">
    <a href="<?php echo $this->basePath();?>/twistt/executive/home" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_HOME_PAGE?'active':'');?>">TWISTT Executive Details</a>
    <a href="<?php echo $this->basePath();?>/twistt/change-password" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_CHANGE_PASSWORD?'active':'');?>">Change Password</a> 
    <a href="<?php echo $this->basePath();?>/twistt/executive/logout">Logout</a>
</div>