<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css?v=1.0.1">
<div class="container-fluid my-5">
    <div class="container">
        <?php 
            $logoutUrl = $this->basePath() . '/twistt/executive/logout';
            if($adapters){ 
                if($userDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($userDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($userDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/exec-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_EXEC_PROFILE, 'logoutUrl'=>$logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5>TWISTT Executive Dashboard</h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase"><u>TWISTT Executive Details</u></h6>
                    <div class="row">
                        <div class="col-12">
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-4"><?php echo "Mobile: (" . $userDetails['country_phone_code'] . ")" . $userDetails['mobile_number']; ?></div>
                                <div class="col-sm-12 col-md-4"><?php echo "QUESTT Expires on: dd/mm/yyyy"; ?></div>
                                <div class="col-sm-12 col-md-4"><?php echo "Commission: " . $bankDetails['commission_percentage'] . "%"; ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <form id="profileForm" enctype="multipart/form-data" novalidate>
                    <div class="bg-white border-radius-10 custom-shadow p-4 color-333 my-3">
                        <h6 id="hdr" class="font-weight-bold border-radius-10 text-uppercase my-3 p-2 stt-bg-light my-3"><u>Edit Profile</u></h6>
                        <div class="row">
                            <div class="col">
                                <div class="row pt-1">
                                    <div class="col-sm-12 col-md-6">
                                        <label for="name" class="form-label">Name*</label>
                                        <input type="text" class="form-control" id="name" name="name" required value="<?php echo $userDetails['username']; ?>">
                                        <div class="invalid-feedback">Please provide your name.</div>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label for="city" class="form-label">City*</label>
                                        <input type="text" class="form-control" id="city" name="city" required value="<?php echo $userDetails['city']; ?>">
                                        <div class="invalid-feedback">Please provide City name.</div>
                                    </div>
                                </div>
                                <div class="row pt-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label for="state" class="form-label">State*</label>
                                        <input type="text" class="form-control" id="state" name="state" required value="<?php echo $userDetails['state']; ?>">
                                        <div class="invalid-feedback">Please provide State name.</div>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label for="country" class="form-label">Country*</label>
                                        <input type="text" class="form-control" id="country" name="country" required value="<?php echo $userDetails['country']; ?>">
                                        <div class="invalid-feedback">Please provide a valid Country name.</div>
                                    </div>
                                </div>
                                <div class="row pt-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label for="ifsc" class="form-label">Bank Name*</label>
                                        <input type="text" class="form-control" id="bankName" name="bankName" required value="<?php echo $bankDetails['bank_name']; ?>">
                                        <div class="invalid-feedback">Please provide a valid Bank Name.</div>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label for="ifsc" class="form-label">IFSC*</label>
                                        <input type="text" class="form-control" id="ifsc" name="ifsc" required value="<?php echo $bankDetails['ifsc_code']; ?>">
                                        <div class="invalid-feedback">Please provide a valid IFSC code.</div>
                                    </div>
                                </div>
                                <div class="row pt-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label for="bankAccount" class="form-label">Bank Account*</label>
                                        <input type="password" class="form-control" id="bankAccountConf" name="bankAccountConf" required value="<?php echo $bankDetails['bank_account_no']; ?>">
                                        <div class="invalid-feedback">Please provide bank account number.</div>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label for="bankAccount" class="form-label">Confirm Bank Account*</label>
                                        <input type="text" class="form-control" id="bankAccount" name="bankAccount" required value="<?php echo $bankDetails['bank_account_no']; ?>">
                                        <div class="invalid-feedback">Please provide bank account number.</div>
                                    </div>
                                </div>
                                <div class="row pt-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label for="gender" class="form-label">Gender</label>
                                            <select class="form-select" id="gender" name="gender">
                                            <option value="">Select...</option>
                                            <option value="male" <?php echo $userDetails['gender']== 'male' ? 'selected' : '' ?>>Male</option>
                                            <option value="female" <?php echo $userDetails['gender']== 'female' ? 'selected' : '' ?>>Female</option>
                                            <option value="other" <?php echo $userDetails['gender']== 'other' ? 'selected' : '' ?>>Other</option>
                                        </select>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label for="email" class="form-label">Email* <span class="text-danger" style="font-size:10px;">(all communication will be sent to this email)</span></label>
                                        <input type="email" class="form-control" id="email" name="email" required value="<?php echo $userDetails['email']; ?>">
                                        <div class="invalid-feedback">Please provide a valid email address.</div>
                                    </div>
                                </div>
                                <div class="row pt-3 my-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label class="form-label text-start">Aadhar*</label>
                                        <div><img src="<?php echo $imageUrl . $userDetails['aadhar_url']; ?>" id="apreview" alt="Aadhar Preview" height="150" width="250"></div>
                                        <?php if($bankDetails['verified'] == '0'){ ?>
                                        <input type="file" class="form-control my-3" id="aadhar" name="aadhar">
                                        <?php } ?>
                                        <div class="invalid-feedback text-white">Please upload your aadhar.</div>
                                    </div>
                                    <div class="col-sm-12 col-md-6">
                                        <label class="form-label text-start">Pan Card*</label>
                                        <div><img src="<?php echo $imageUrl . $userDetails['pan_url']; ?>" id="ppreview" alt="Pan Preview" height="150" width="250"></div>
                                        <?php if($bankDetails['verified'] == '0'){ ?>
                                        <input type="file" class="form-control my-3" id="pan" name="pan">
                                         <?php } ?>
                                        <div class="invalid-feedback text-white">Please upload your pan card.</div>
                                    </div>
                                </div>
                                <div class="row pt-3 my-3">
                                    <div class="col-sm-12 col-md-6">
                                        <label class="form-label text-start">Profile Pic*</label>
                                        <div><img src="<?php echo $imageUrl . $userDetails['photo_url']; ?>" id="preview" alt="Image Preview" height="150" width="150"></div>
                                        <?php if($bankDetails['verified'] == '0'){ ?>
                                        <input type="file" class="form-control my-3" id="photo" name="photo">
                                        <?php } ?>
                                        <div class="invalid-feedback text-white">Please upload your photo.</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn primary-btn text-white" id="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-profile.js?v=1.0.3"></script>
