<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css?v=1.0.1">
<div class="container-fluid my-5">
    <div class="container">
        <?php 
            $logoutUrl = $this->basePath() . '/twistt/executive/logout';
            if($adapters){ 
                if($userDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($userDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($userDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/exec-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_BUY_COUPONS, 'logoutUrl'=>$logoutUrl)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333" style="min-height:400px;">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5><?php echo "Buy Coupons"; ?></h5>
                </div>
                <?php if($isQUESTTValid) {?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="dc" class="form-label">No. of Discount Coupons</label>
                        <input type="number" class="form-control w-100" id="dc" name="dc" value="0" min="0" required>
                    </div>
                </div>
                <?php if($bankDetails['banned'] == '0') {?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="cc" class="form-label">No. of Complimentary Coupons</label>
                        <input type="number" class="form-control w-100" id="cc" name="cc" value="0" min="0" required>
                    </div>
                </div>
                <?php } else {?>
                    <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <input type="hidden" id="cc" name="cc" value="0">
                    </div>
                </div>
                <?php } ?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="amt" class="form-label">Amount: </label>
                        <label class="form-label" id="amt" name="amt"></label>
                        <input type="hidden" id="udcp" name="udcp" value="<?php echo $udcp;?>">
                        <input type="hidden" id="uccp" name="uccp" value="<?php echo $uccp;?>">
                        <input type="hidden" id="username" name="username" value="<?php echo $userDetails['username'];?>">
                        <input type="hidden" id="mobile" name="mobile" value="<?php echo "(" . $userDetails['country_phone_code'] . ")" . $userDetails['mobile_number'];;?>">
                        <input type="hidden" id="email" name="email" value="<?php echo $userDetails['email'];?>">
                        <input type="hidden" id="city" name="city" value="<?php echo $userDetails['city'];?>">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 pt-3">
                        <button type="button" class="btn primary-btn mt-3" id="btnBuy" name="btnBuy">Buy</button>
                    </div>
                </div>
                <?php } else {?>
                    <div class="row">
                    <div class="col-12 pt-3">
                        <h6 class="text-danger"><?php echo "Your QUESTT validity expired." ?></h6>
                        <h6 class="text-danger"><?php echo "Please renew your QUESTT to purchase coupons." ?></h6>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-buy-coupons.js?v=1.0.1"></script>