<?php
    include 'vendor/autoload.php';
    use Hybridauth\Hybridauth;
    $hybridauth = new Hybridauth($config);
    $adapters = $hybridauth->getConnectedAdapters();
?>
<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css?v=1.0.1">
<div class="container-fluid my-5">
    <div class="container">
        <?php 
            $logoutUrl = $this->basePath() . '/twistt/executive/logout';
            if($adapters){ 
                if($userDetails['oauth_provider'] == 'g'){
                    $logoutUrl = $config['callback'] . "?logout=Google";
                }elseif($userDetails['oauth_provider'] == 'f'){
                    $logoutUrl = $config['callback'] . "?logout=Facebook";
                }elseif($userDetails['oauth_provider'] == 'a'){
                    $logoutUrl = $config['callback'] . "?logout=Apple";
                }
            }
            echo $this->partial('/exec-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_BUY_COUPONS, 'logoutUrl'=>$logoutUrl)); 
        if($bankDetails['verified'] == '1' && $bankDetails['banned'] == '0'){ ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333" style="min-height:400px;">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5>Buy Coupons</h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase"><u>TWISTT Executive Details</u></h6>
                    <div class="row">
                        <div class="col-12">
                            <div class="row pt-1">
                                <div class="col-sm-12 col-md-6"><?php echo "Name: " . $userDetails['username']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Mobile: (" . $userDetails['country_phone_code'] . ")" . $userDetails['mobile_number']; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "QUESTT Expires on: " . $qed; ?></div>
                                <div class="col-sm-12 col-md-6"><?php echo "Commission: " . $bankDetails['commission_percentage'] . "%"; ?></div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if($isQUESTTValid) {?>
                    <?php   $selectedDate = date('Y-m-d', strtotime($qed));
                        $selectedDateTime = new DateTime($selectedDate);
                        $today = new DateTime();
                        $interval = $today->diff($selectedDateTime);
                        if ($interval->days <= 30 && $selectedDateTime >= $today) { ?>
                            <div class="row mt-3 p-2 border-radius-10 bg-danger">
                                <div class="col text-white">Your QUESTT subscription is about to expire.. Please renew..</div>
                            </div>
                <?php }?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="dc" class="form-label">No. of Discount Coupons</label>
                        <input type="number" class="form-control w-100" id="dc" name="dc" value="0" min="0" onfocusout="updateAmt()" required>
                    </div>
                </div>
                <?php if($bankDetails['banned'] == '0') {?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="cc" class="form-label">No. of Complimentary Coupons</label>
                        <input type="number" class="form-control w-100" id="cc" name="cc" value="0" min="0"  onfocusout="updateAmt()" required>
                    </div>
                </div>
                <?php } else {?>
                    <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <input type="hidden" id="cc" name="cc" value="0">
                    </div>
                </div>
                <?php } ?>
                <div class="row">
                    <div class="col col-lg-4 pt-3">
                        <label for="amt" class="form-label">Amount: </label>
                        <label class="form-label" id="amt" name="amt"></label>
                        <input type="hidden" id="udcp" name="udcp" value="<?php echo $udcp;?>">
                        <input type="hidden" id="uccp" name="uccp" value="<?php echo $uccp;?>">
                        <input type="hidden" id="username" name="username" value="<?php echo $userDetails['username'];?>">
                        <input type="hidden" id="mobile" name="mobile" value="<?php echo "(" . $userDetails['country_phone_code'] . ")" . $userDetails['mobile_number'];;?>">
                        <input type="hidden" id="email" name="email" value="<?php echo $userDetails['email'];?>">
                        <input type="hidden" id="city" name="city" value="<?php echo $userDetails['city'];?>">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 pt-3">
                        <button type="button" class="btn primary-btn mt-3" id="btnBuy" name="btnBuy">Buy</button>
                    </div>
                </div>
                <?php } else {?>
                    <div class="row">
                    <div class="col-12 pt-3">
                        <h6 class="text-danger"><?php echo "Your QUESTT validity expired." ?></h6>
                        <h6 class="text-danger"><?php echo "Please renew your QUESTT to purchase coupons." ?></h6>
                    </div>
                </div>
                <?php } ?>
            </div>
        </div>
        <?php } elseif($bankDetails['verified'] == '0'){ ?>
            <div class="content bg-white custom-shadow p-4 color-333"> 
                <div class="bg-light border-radius-10 custom-shadow p-4 color-333" style="min-height:400px;">
                    <div class="user-page-name text-uppercase avant-md pb-3 text-danger">
                        <h5>Executive registration not verified by Admin..</h5>
                    </div>
                </div>
            </div>
        <?php } elseif($bankDetails['banned'] == '1'){ ?>
            <div class="content bg-white custom-shadow p-4 color-333"> 
                <div class="bg-light border-radius-10 custom-shadow p-4 color-333" style="min-height:400px;">
                    <div class="user-page-name text-uppercase avant-md pb-3 text-danger">
                        <h5>Executive Banned by Admin..</h5>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-buy-coupons.js?v=1.0.5"></script>