<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/login.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.1">
<style>
  .iti{
    display: block;
  }
  .hide{
    display: none;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/add-executive.js?v=1.0.9"></script>
<div class="container my-5">
  <h1 class="text-center mb-5">TWISTT Executive Registration Form</h1>
  <form id="registrationForm" enctype="multipart/form-data" novalidate>
    <div class="row g-3 mb-3">
      <div id="divMobile" class="col-md-6">
        <label for="mobile" class="form-label">Mobile*</label>
        <input type="tel" class="form-control" id="mobile" name="mobile" pattern="[0-9]*" required>
        <input type="hidden" id="country">
        <div class="invalid-feedback">Please provide valid mobile number.</div>
      </div>
      <div id="divOtp" class="col-md-6">
        <label for="otp" class="form-label">Otp</label>
        <input type="text" class="form-control" id="otp" name="otp">
        <button type="button" class="btn primary-btn mt-3" id="btnVerify" name="btnVerify">Verify Otp</button>
      </div>
      <div id="divBtn" class="col-md-6 pt-3">
        <button type="button" class="btn primary-btn mt-3" id="btnOtp" name="btnOtp">Send Otp</button>
        <div id="valid-msg" class="hide text-success">✓ Valid</div>
        <div id="error-msg" class="hide text-danger"></div>
      </div>
    </div>
    <div class="row g-3" id="userDetails">
      <div class="col-md-6">
        <label for="name" class="form-label">Name*</label>
        <input type="text" class="form-control" id="name" name="name" required>
        <div class="invalid-feedback">Please provide your name.</div>
      </div>
      <div class="col-md-6">
        <label for="gender" class="form-label">Gender</label>
        <select class="form-select" id="gender" name="gender">
          <option value="">Select...</option>
          <option value="male">Male</option>
          <option value="female">Female</option>
          <option value="other">Other</option>
        </select>
      </div>
      <div class="col-md-6">
        <label for="email" class="form-label">Email*</label>
        <input type="email" class="form-control" id="email" name="email" required>
        <div class="invalid-feedback">Please provide a valid email address.</div>
      </div>
      <div class="col-md-6">
        <label for="age" class="form-label">Age*</label>
        <input type="number" class="form-control" id="age" name="age" required>
        <div class="invalid-feedback">Please provide your age.</div>
      </div>
      <div class="col-md-6">
        <label for="education" class="form-label">Education</label>
        <input type="text" class="form-control" id="education" name="education">
      </div>
      <div class="col-md-6">
        <label for="occupation" class="form-label">Occupation</label>
        <input type="text" class="form-control" id="occupation" name="occupation">
      </div>
      <div class="col-md-6">
        <label for="address" class="form-label">Address*</label>
        <input type="text" class="form-control" id="address" name="address" required>
        <div class="invalid-feedback">Please provide a valid Address.</div>
      </div>
      <div class="col-md-6">
        <label for="city" class="form-label">City*</label>
        <input type="text" class="form-control" id="city" name="city" required>
        <div class="invalid-feedback">Please provide City name.</div>
      </div>
      <div class="col-md-6">
        <label for="state" class="form-label">State*</label>
        <input type="text" class="form-control" id="state" name="state" required>
        <div class="invalid-feedback">Please provide State name.</div>
      </div>
    </div>
    <div class="row g-3 mt-3" id="bankDetails">
      <div class="col-md-6">
        <label for="ifsc" class="form-label">Bank Name*</label>
        <input type="text" class="form-control" id="bankName" name="bankName" required>
        <div class="invalid-feedback">Please provide a valid Bank Name.</div>
      </div>
      <div class="col-md-6">
        <label for="ifsc" class="form-label">IFSC*</label>
        <input type="text" class="form-control" id="ifsc" name="ifsc" required>
        <div class="invalid-feedback">Please provide a valid IFSC code.</div>
      </div><div class="col-md-6">
        <label for="bankAccount" class="form-label">Bank Account*</label>
        <input type="password" class="form-control" id="bankAccountConf" name="bankAccountConf" required>
        <div class="invalid-feedback">Please provide bank account number.</div>
      </div>
      <div class="col-md-6">
        <label for="bankAccount" class="form-label">Confirm Bank Account*</label>
        <input type="text" class="form-control" id="bankAccount" name="bankAccount" required>
        <div class="invalid-feedback">Please provide bank account number.</div>
      </div>
      <div class="col-md-6">
        <label for="photo" class="form-label">Passport Size Photo*</label>
        <input type="file" class="form-control mb-3" id="photo" name="photo">
        <img id="preview" alt="Image Preview" height="100">
        <div class="invalid-feedback">Please upload your photo.</div>
      </div>
    </div>
    <button type="submit" class="btn submit-btn mt-5" id="register">Register</button>
  </form>
</div>

<script>
  
</script>

<div class="login-bg"></div>