<?php
/* if($_SESSION['Laminas_Auth']->storage['suser_name']){
    header("Location: " . $this->basePath() . "/se-home"); 
    exit();
} */
include 'vendor/autoload.php';
//include 'config.php';
?>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/login.css?v=1.0.1">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/twistt.css?v=1.0.2">
<link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/css/intlTelInput.css">
<style>
  .iti{
    display: block;
  }
  .hide{
    display: none;
  }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.13/js/intlTelInput.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/user/executive-login.js?v=1.0.1"></script>
<section class="py-3 py-md-5 py-xl-8">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="mb-5">
          <!-- <div class="d-flex justify-content-center mb-5">
            <img src="<?php //echo $this->basePath(); ?>/img/susri.png" class="logo">
          </div> -->
          <h2 class="display-6 fw-bold text-center">TWISTT Executive Login</h2>
          <p class="text-center m-0">Don't have an account? <a href="/twistt/executive/terms">Register as TWISTT Executive</a></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">
        <div class="row justify-content-center">
          <div class="col-12">
            <div class="row gy-5 justify-content-center">
              <div class="col-12">
                <form>
                  <div class="row gy-3 overflow-hidden">
                    <div class="col-12" id="divMobile">
                      <div class="form-floating mb-2">
                        <input type="tel" class="form-control border-0 border-bottom rounded-0 mb-1" id="mobile" name="mobile" placeholder="Mobile Number" autocomplete="username">
                        <div id="valid-msg" class="hide text-success mt-2">✓ Valid</div>
                        <div id="error-msg" class="hide text-danger mt-2"></div>
                        <input type="hidden" id="country">
                      </div>
                    </div>
                    <div class="col-12" id="divMail">
                      <div class="mb-3">
                        <input type="text" class="form-control border-0 border-bottom rounded-0" name="email" id="email"  placeholder="name@example.com" autocomplete="username">
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="mb-3">
                        <input type="password" class="form-control border-0 border-bottom rounded-0" name="password" id="password" placeholder="Password" autocomplete="current-password">
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="row justify-content-between">
                        <div class="col-6">
                          <a href="#!" id="loginType">Login with Email id</a>
                        </div>
                        <div class="col-6">
                          <div class="text-end">
                            <a href="/twistt/forgot-password" class="link-secondary text-decoration-none">Forgot password?</a>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="d-grid">
                        <button type="button" class="btn primary-btn btn-lg text-white" id="btnLogin">Log in</button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            <!--  <div class="col-12 col-lg-2 d-flex align-items-center justify-content-center gap-3 flex-lg-column">
                <div class="bg-dark h-100 d-none d-lg-block" style="width: 1px; --bs-bg-opacity: .1;"></div>
                <div class="bg-dark w-100 d-lg-none" style="height: 1px; --bs-bg-opacity: .1;"></div>
                <div>or</div>
                <div class="bg-dark h-100 d-none d-lg-block" style="width: 1px; --bs-bg-opacity: .1;"></div>
                <div class="bg-dark w-100 d-lg-none" style="height: 1px; --bs-bg-opacity: .1;"></div>
              </div> -->
              <div class="col-12 d-flex align-items-center justify-content-center gap-3">
                <div class="bg-dark" style="height: 1px; width: 100%; --bs-bg-opacity: .1;"></div>
                <div class="mx-2">or</div>
                <div class="bg-dark" style="height: 1px; width: 100%; --bs-bg-opacity: .1;"></div>
              </div>
              <div class="col-12 d-flex align-items-center mb-5">
                <div class="d-flex gap-3 flex-column w-100 ">
                  <!-- <a href="#<?php //print $callbackUrl . "?provider=Google"; ?>" onclick="javascript:auth_popup('Google');" class="btn btn-lg btn-danger" id="Google"> -->
                  <a href="<?php echo $callbackUrl . "?provider=Google"; ?>" class="btn btn-lg btn-danger" id="Google">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                      <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" /></svg>
                    <span class="ms-2 fs-6">Sign in with Google</span>
                  </a>
                  <a href="<?php echo $callbackUrl . "?provider=Facebook"; ?>" class="btn btn-lg btn-primary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                      <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" /></svg>
                    <span class="ms-2 fs-6">Sign in with Facebook</span>
                  </a>
                  <a href="#!" class="btn btn-lg btn-dark">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-apple" viewBox="0 0 16 16">
                      <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" />
                      <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516.024.034 1.52.087 2.475-1.258.955-1.345.762-2.391.728-2.43Zm3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422.212-2.189 1.675-2.789 1.698-2.854.023-.065-.597-.79-1.254-1.157a3.692 3.692 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56.244.729.625 1.924 1.273 2.796.576.984 1.34 1.667 1.659 1.899.319.232 1.219.386 1.843.067.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758.347-.79.505-1.217.473-1.282Z" /></svg>
                    <span class="ms-2 fs-6">Sign in with Apple</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-1 d-none d-lg-block align-items-center justify-content-center">
        <div class="d-flex" style="height: 550px;">
          <div class="vr mx-auto"></div>
        </div>
      </div>
      <div class="col-12 col-md-7">
        <div data-mdb-input-init class="form-outline w-100">
        <label class="form-label text-success" for="why"><b>Why become TWISTT Executive?</b></label>
          <textarea class="form-control bg-light" id="why" rows="20">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum necessitatibus qui ipsa atque voluptate porro, aut odio hic magnam aperiam culpa sint ipsam iure ea ab suscipit nostrum commodi! Enim nihil modi pariatur laborum soluta? Labore, nostrum fugiat architecto tempore deleniti rerum a necessitatibus officia ea at, tenetur adipisci maiores.
          </textarea>
        </div>
      </div>
    </div>
    
  </div>
</section>
<!-- <div class="module-container">
  <div class="module-wrapper">
    <div class="display-table">
      <div class="display-table-cell">
         <div class="form-wrapper login-fields">
          <div class="d-flex justify-content-center">
            <img src="<?php //echo $this->basePath(); ?>/img/susri.png" class="logo">
          </div>
          <div class="d-flex justify-content-center mt-3 mb-3">
            <h4 class="login-txt">TWISTT Executive Login</h4>
          </div>
          <div class="form-group">
            <div class="input-group mb-3 form-control">
              <input type="tel" class="" id="mobile" placeholder="Phone Number">
              <input type="hidden" id="country">
            </div>
          </div>
          <div class="form-group">
            <input type="password" placeholder="Password" class="form-control " id="password">
          </div>
          <div class="row my-3 d-flex">
            <div class="col align-items-start">
              <div class="mb-3"><a href="/twistt/executive/register">Register as TWISTT Executive</a></div>
              <div><a href="/twistt/executive/forgot-password">Forgot Password</a></div>
            </div>
            <div class="col float-end text-end">
              <button type="button" class="btn submit-btn">Login</button>
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div>
</div> -->
<div class="login-bg"></div>