<div class="sidebar">
    <a href="<?php echo $this->basePath();?>/twistt/executive/buy-coupons" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_BUY_COUPONS?'active':'');?>">Buy Coupons</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/track-coupons" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COUPONS?'active':'');?>">Track Coupons</a>
    <!-- <a href="<?php echo $this->basePath();?>/twistt/executive/track-commissions" class="<?php //echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COMMISSION?'active':'');?>">Track Commission</a> -->
    <a href="<?php echo $this->basePath();?>/twistt/executive/track-commissions-earned" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COMMISSION_EARNED?'active':'');?>">Track Commission Earned</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/track-commissions-received" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COMMISSION_RECEIVED?'active':'');?>">Track Commission Received</a>
    <a href="<?php echo $this->basePath();?>/twistt/plans-discounts" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_PLANS_DISCOUNTS?'active':'');?>">Plans & Discounts</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/profile" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_PROFILE?'active':'');?>">Check/Edit Profile</a>
    <a href="<?php echo $this->basePath();?>/twistt/change-password" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_CHANGE_PASSWORD?'active':'');?>">Change Password</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive-terms" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_TERMS?'active':'');?>">Terms</a> 
    <a href="<?php echo $logoutUrl;?>" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_LOGOUT?'active':'');?>">Logout</a>
</div>