<div class="sidebar">
    <a href="<?php echo $this->basePath();?>/twistt/executive/buy-coupons" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_BUY_COUPONS?'active':'');?>">Buy Coupons</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/track-coupons" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COUPONS?'active':'');?>">Track Coupons</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/track-commissions" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_TRACK_COMMISSION?'active':'');?>">Track Commission</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive/home" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_PROFILE?'active':'');?>">Profile</a>
    <a href="<?php echo $this->basePath();?>/twistt/change-password" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_CHANGE_PASSWORD?'active':'');?>">Change Password</a>
    <a href="<?php echo $this->basePath();?>/twistt/executive-terms" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_TERMS?'active':'');?>">Terms</a> 
    <a href="<?php echo $logoutUrl;?>" class="<?php echo ($activeTab==\Application\Constants\Constants::TWISTT_EXEC_LOGOUT?'active':'');?>">Logout</a>
</div>