<div class="container-fluid px-0 help-banner mb-5">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            HELP
        </div>
    </div>
</div>

<div class="container-fluid my-5">
    <div class="container help-container">
        <h3 class="d-sm-block d-md-none text-uppercase blue">Help</h3>
        <div class="bg-white border-radius-10 custom-shadow p-4 color-333">
            <div class="tales">
                <h5>To listen to tales… </h5>
                <ol>
                    <li> Install the “Susri Tour Tales” App from Google Playstore.</li>
                    <li> Log-in</li>
                    <li> Become a QUESTT annual Subscriber by on-line payment.</li>
                    <li> OR become a TWISTT Short Duration Subscriber (15 days) by (i) using a password given/sold by QUESTT Subscriber or (ii) by activation through an Agency.</li>
                    <li> Select the Tales</li>
                    <li> Choose the language</li>
                    <li> Download</li>
                    <li> Listen</li>
                    <br>***<br>
                    <li> If you are a QUESTT Subscriber, register as a TWISTT Sponsor if interested.</li>
                    <li> Buy the “TWISTT Subscription Passwords” at discounted rate.</li>
                    <li> Gift or Sell to the interested tourists and make marginal profits.</li>
                </ol>
                <!-- <p class="pb-4">Please check the video for detailed instructions <a href="https://youtu.be/FnnfJy3G0lg" target="_blank" class="social-icon icon-youtube"><i class="fab fa-youtube"></i></a></p> -->
            </div>
            <!-- <div>
                <h5>Select</h5>
                <div class="select">
                    <p class="position-relative ml-3">Purchasing the tales of your choice for your mobile library.</p>
                </div>
            </div> -->
            <div class="operations">
                <!-- <h6><i>Operations</i></h6> -->
                <h5>Operations</h5>
                <ol class="operation-list">
                    <li> Selection of the Tales for downloading can be done from one category at a time.</li>
                    <li class="sub-item"> Procedure of Selection for  Spiritual Tour (ST), India Tour (IT) and World Tour (WT) Tales-
                        <ol class="sub-list">
                            <li> Select category ST or IT or WT.</li>
                            <li> Select State in case of ST or  IT and  Country for WT.</li>
                            <li> Select City/Town.</li>
                            <li> Select desired places from that city/town.</li>
                            <li> Repeat 2.2 to 2.4 till your selection is over.</li>
                        </ol>
                    </li>
                    <li class="sub-item">Procedure of Selection for City Tour and Festival Tour Tales.
                        <ol class="sub-list">
                            <li> Select category CT or FT.</li>
                            <li> Select City or Festival Tour Tale Set, as per the case.</li>
                            <li> Repeat 3.1 to 3.2 till selection is over.</li>
                        </ol>
                    </li>
                    <li> Verify the list of places you selected, edit if required and continue to download.</li>
                    <li> Select the language of choice before downloading.</li>
                    <li> Download preferably in Wi Fi Environment.</li>
                    <li> Select the desired Tour Tale from Library and listen using Headphones.</li>
                </ol>
            </div>
            <div class="margin-lt">
                <h6>Note</h6>
                <ol>
                    <li> QUESTT Subscription is valid for one year.</li>
                    <!-- <li> Renewals can be done at discounted rates in 12th month.</li> -->
                    <!-- <li> 1<sup>st</sup> year renewal is 75% of prevailing Subscription price and further renewals are at 50%.</li> -->
                    <!-- <li> There will be discounts on renewals as indicated in Parameters Table in App Menu.</li> -->
                    <li> &quot;TWISTT Subscription Password&quot; is valid for one year from the date of purchase.</li>
                    <li> Make sure of the validity while purchasing the TWISTT passwords.</li>
                    <!-- <li> Max. of 30 Tales only can be available in Mobile at any given instant.</li> -->
                    <li> Maximum number of tales that can be available at any given time is 40.</li>
                    <li> Remove excess Tales to accommodate new downloads.</li>
                    <li> Tales downloaded get auto-deleted after 15 days. You can download again.</li>
                    <!-- <li> Tales downloaded get auto-deleted after 15 days. You can download again.</li> -->
                    <li> If you select a regional language for listening, you need to select one of the default languages English or Hindi.</li>
                    <li> You will hear the Tale in selected default language, if it is not available in the selected regional language.</li>
                    <li> Spiritual Tour Tales can be heard without any Subscription.</li>
                </ol>
            </div>
            <!-- <div>
                <h5>Download</h5>
                <div class="select">
                    <p class="position-relative ml-3 font-italic"> To transfer the selected audio's from STT server to your Mobile memory. Use the password mailed to you or given to you by your Tour Leader/Tour Operator. If you are operating the mobile from which the booking is made, then you can download directly from the App itself. You can use "download" option in appropriate booking reference reflected in Booking History of App Menu.</p>
                </div>
            </div>
            <div class="margin-lt">
                <h6><i>Operations</i></h6>
                <ol>
                    <li> Select the tour category which you booked or for which you have received the valid password.</li>
                    <li> If the booking is done from the same device, select the appropriate booking in Booking reference and download.</li>
                    <li> Alternately, select download option, enter the password received on e-mail or given by your Tour Operator and download.</li>
                    <li> Team leader also can download from Booking History page for his own device. The first password will be expended for him.</li>
                    <li> Select the Regional Language and Default language and Continue.</li>
                    <li> Wait till all the files are downloaded.</li>
                    <li> Listen as and when you like within the timeframe.</li>
                </ol>
            </div>
            <div class="margin-lt">
                <h6>Note</h6>
                <ol>
                    <li> Tour Operators do not have the option of downloading from Booking History Page.</li>
                </ol>
            </div>

            <div>
                <h5>Library(Listen)</h5>
                <div class="select">
                    <p class="position-relative ml-3"> Browse the Library and listen to the tales of your choice.</p>
                    <div class="margin-lt">
                        <h6><i>Operations</i></h6>
                        <ol>
                            <li> Select the category desired.</li>
                            <li> Select the Country/State/City/Place and listen to the tale.</li>
                        </ol>
                    </div>
                </div>
            </div> -->
            <div class="tale_category">
                <h5 class="mb-3">Tales Categories</h5>
                <ul class="list-unstyled mb-3 ml-3">
                    <li><span class="font-weight-bold">India Tour Tales (IT) :</span> The Tales of the places of tourism interest in India. It is a super set of ST, CT (India) and FT(India) Tales.</li>
                    <li>Tale selection path: <b><i>State-City-Place</i></b></li>
                </ul>
                <ul class="list-unstyled mb-3 ml-3">
                    <li><span class="font-weight-bold">World Tour Tales (WT) : </span> The Tales of the places of tourism interest in the rest of the world outside India.</li>
                    <li>Tale selection path: <b><i>Country-City-Place</i></b></li>
                </ul>
                <ul class="list-unstyled mb-3 ml-3">
                    <li><span class="font-weight-bold">Spiritual Tour Tales (ST) :</span>  are exclusively the Tales of Spiritual places in India like Temples, Mosques and Churches and other spiritual centres. <b>ST tales are free.</b></li>
                    <li>Tale selection path: <b><i>State-City-Place</i></b></li>
                </ul>
                <ul class="list-unstyled mb-3 ml-3">
                    <li><span class="font-weight-bold">City Tour Tales (CT) :</span> are the Tales of places selected from the list of IT/WT Tales and packaged together. These places are located within a particular city or nearby. The cities can be Indian or Global.</li>
                    <li>Tale selection path: <b><i>Country-City-Place</i></b></li>
                </ul>
                <ul class="list-unstyled mb-3 ml-3">
                    <li><span class="font-weight-bold">Festival Tour Tales (FT) :</span>  are the Tales of the places selected from the list of IT/WT Tales and packaged together. These places are visited by large number of people in a particular season because of a special event or significance.</li>
                    <li>Tale selection path: <b><i>Country-FestivalSet-Place</i></b></li>
                </ul>
            </div>
        </div>
    </div>
</div>