
<?php if(isset($type) && $type =='initialize') { ?>
<div class="table-responsive">
<table class="table table-hover" id="extTable">
    <thead>
    <tr class="text-nowrap">
        <th>S.no</th>
        <th class="text-center" data-placeholder="Transaction Date">Transaction Date</th>
        <th class="text-center" data-placeholder="Coupon Code">Coupon Code</th>
        <th class="text-center" data-placeholder="Coupon Type">Coupon Type</th>
        <th class="text-center" data-placeholder="Redeemer Name">Redeemer Name</th>
        <th class="text-center" data-placeholder="Redeemer Mobile">Redeemer Mobile</th>
        <th class="text-center" data-placeholder="Txn Ref ">Txn Ref</th>
        <th class="text-center" data-placeholder="Amount Paid ">Amount Paid</th>
        <th class="text-center" data-placeholder="Total Earnings">Total Earnings</th>
        <th class="text-center" data-placeholder="Balance">Balance</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>
    
    <?php if(count($transactions))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($transactions as $tx) { 
          $color = "";
          if($tx['transaction_type'] == \Admin\Model\ExecutiveTransaction::transaction_due)
              $color = "table-danger text-nowrap";
          else
              $color = "table-success text-nowrap";
          ?>
          <tr class="<?php echo $color; ?>">
              <td><?php echo $i+1; ?></td>
              <td class="text-center"><?php echo date("d-m-Y",strtotime($tx['transaction_date'])); ?></td>
              <td class="text-center"><?php echo $tx['coupon_code']; ?></td>
              <td class="text-center"><?php echo $tx['coupon_type']; ?></td>
              <td class="text-center"><?php echo $tx['username']; ?></td>
              <td class="text-center"><?php echo "(" . $tx['country_phone_code'] . ")" . $tx['mobile_number'] ; ?></td>
              <td class="text-center"><?php echo $tx['transaction_ref']; ?></td>
              <td class="text-center"><?php echo $tx['stt_paid_amount']; ?></td>
              <td class="text-center"><?php echo $tx['total_earnings']; ?></td>
              <td class="text-center"><?php echo $tx['balance_outstanding']; ?></td>
          </tr>
          <?php $i++; } } else { ?>
        <tr ><td class="text-center" colspan="10">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php //echo "id=".$id;?>
<input type="hidden" id="hid" value="0<?php //echo base64_encode("id=".$id);?>" />
</div>
<?php } ?>