
<?php if(isset($type) && $type =='initialize') { ?>
<!-- <style>
.table-condensed thead tr th{ color: unset !important;}
.calign input{text-align: center !important;}
</style> -->
<div class="table-responsive">
<table class="table table-hover" id="extTable">
    <thead>
    <tr class="text-nowrap">
        <th>S.no</th>
        <th class="text-center" data-placeholder="Purchase Date">Purchase Date</th>
        <th class="text-center" data-placeholder="Coupon Code">Coupon Code</th>
        <th class="text-center" data-placeholder="Coupon Type"">Coupon Type</th>
        <th class="text-center" data-placeholder="Coupon Amount"">Coupon Amount</th>
        <th class="text-center" data-placeholder="Validity End Date">Validity End Date</th>
        <th class="text-center" data-placeholder="Redeemer Mobile">Redeemer Mobile</th>
        <th class="text-center" data-placeholder="Redeemer Paid">Redeemer Paid</th>
        <th class="text-center" data-placeholder="Actual Price">Actual Price</th>
        <th class="text-center" data-placeholder="Commission">Commission receivable</th>
    </tr>
    <?php } ?>

    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>
    <input type="hidden" class="records" value="<?php echo $totalCount; ?>">
    <tbody>
    <?php } ?>
    
    <?php if(count($coupons))
      {
        $i=0;
        if(isset($offset))
        {
            $i=$offset;
        }

        foreach ($coupons as $cd) { 
          $color = "";
          if($cd['coupon_status'] == \Admin\Model\Coupons::Coupon_Status_Redeemed)
              $color = "table-danger text-nowrap";
          else
              $color = "table-success text-nowrap";
          if(1==1){ //if(!$cd['sr']){?>
          <tr class="<?php echo $color; ?>">
              <td><?php echo $i+1; ?></td>
              <td class="text-center"><?php echo date("d-m-Y",strtotime($cd['created_at'])); ?></td>
              <td class="text-center"><?php echo $cd['coupon_code']; ?></td>
              <td class="text-center"><?php echo $cd['coupon_type']; ?></td>
              <td class="text-center"><?php echo $cd['amount']; ?></td>
              <td class="text-center"><?php echo date("d-m-Y",strtotime($cd['validity_end_date'])); ?></td>
              <td class="text-center"><?php echo $cd['redeemer_mobile']; ?></td>
              <td class="text-center"><?php echo $cd['redeemer_paid']; ?></td>
              <td class="text-center"><?php echo $cd['redeemer_actual_amount']; ?></td>
              <td class="text-center"><?php echo $cd['commission_receivable']; ?></td>
          </tr>
          <?php $i++; } } } else { ?>
        <tr ><td class="text-center" colspan="10">No data</td></tr>
    <?php  } ?>
    <?php if(isset($type) && ($type =='initialize' || $type=="search") ) {?>

    </tbody>
    <?php } ?>
    <?php if(isset($type) && $type =='initialize') {?>

</table>
<?php //echo "id=".$id;?>
<input type="hidden" id="hid" value="0<?php //echo base64_encode("id=".$id);?>" />
</div>
<?php } ?>