<div class="container-fluid">
    <div class="container">
        <div class="text-uppercase avant-md tour-headding color-000 mb-3 d-flex justify-content-between mt-3">
            <p class="mb-0">Festival Tours</p>
        </div>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb bg-white">
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath(); ?>/">Home</a></li>
                <li class="breadcrumb-item"><a href="<?php echo $this->basePath(); ?>/seasonal-specials"><?php echo $places['seasonal_name']?></a></li>

                <li class="breadcrumb-item active" aria-current="page">Places</li>
            </ol>
        </nav>

        <div class="row mt-5">
            <?php if($places) { foreach ($places['places_list'] as $places) {?>
                <div class="col-12 col-md-3 mb-4">
                    <div class="slider-box bg-white mb-3 position-relative">
                        <div class="slider-image position-relative" style="background: #f5f5f5 url('<?php echo $imageUrl.$places['place_image']; ?>') no-repeat center / cover">
                        </div>
                        <div class="p-3">
                            <div class="d-flex align-items-center">

                                <div style=" min-width: 0">
                                    <div class="text-capitalize color-000 avant-bk tour-country text-truncate " >
                                        <?php echo $places['place_name']; ?>
                                    </div>
                                    <div class="avi_lan" data-toggle="tooltip" title="<?php echo implode(",",$places['languages'])?>">
                                        l+
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php }} ?>




        </div>



    </div>
</div>
<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();
    })
</script>