<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/vendor/sol.css">
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/vendor/bootstrap-datetimepicker.min.css"/>
<script src="<?php echo $this->basePath(); ?>/js/vendor/sol.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/moment.min.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/js/vendor/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/admin/tbe-home.js?v=1.4"></script>
<?php $role = ($_SESSION['Laminas_Auth']->storage['tbe_role'] == 'A')? "Role: AE" : "Role: TBE"; ?>
<div class="container-fluid my-5">
    <div class="container">  
        <?php echo $this->partial('/twistt-sidebar', array('activeTab'=>\Application\Constants\Constants::TWISTT_HOME_PAGE, 'userId'=>$userId)); ?>
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="user-page-name text-uppercase avant-md pb-3">
                    <h5><?php echo "Tourist Entry"; ?></h5>
                </div>
                <div class="stt-bg-primary border-radius-10 custom-shadow p-4 color-333">
                    <h6 class="font-weight-bold text-uppercase">Details</h6>
                    <div class="row">
                        <!-- <div class="col-sm-12 col-md-2">
                            <img src="<?php //echo $imageUrl.$taDetails[0]['file_path'];?>" alt="TA logo" height="50" class="mb-sm-2">
                        </div> -->
                        <div class="col-sm-12 col-md-12">
                            <div class="row">
                                <div class="col-sm-12 col-md-6"><?php echo "Name: " . $_SESSION['Laminas_Auth']->storage['tuser_name']; ?></div>
                                <!-- <div class="col-sm-12 col-md-6"><?php //echo $role; ?></div> -->
                            </div>
                            <div class="row">
                                <div class="col-sm-12 col-md-6"><?php echo "Mobile: " . $_SESSION['Laminas_Auth']->storage['tbe_mobile']; ?></div>
                                <!-- <div class="col-sm-12 col-md-6"><?php //echo "TA Name: " . $taDetails[0]['ta_name']; ?></div> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="bg-white border-radius-10 custom-shadow p-4 color-333 my-3">
                    <h6 class="font-weight-bold text-uppercase">Add Tourist</h6>
                    <div class="row py-2">
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <label class="text-black-50">Name</label>
                            <input type="text" class="form-control" id="tName"/>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <label class="text-black-50">Mobile</label>
                            <div class="row">
                                <!-- <div class="col-3"><input type="number" class="form-control" id="tcc" value="91"/></div> -->
                                <div class="col-3 dropdown">
                                    <button class="btn bg-white dropdown-toggle w-100 border" type="button" id="tcc" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:90%;height:38px;">
                                    <?php
                                            echo "+91";
                                    ?>
                                    </button>
                                    <div class="dropdown-menu w-100" aria-labelledby="dropdownMenuButton" style="overflow: scroll;max-height: 250px;">
                                        <?php if(count($mccList)){ 
                                            foreach($mccList as $mcc){?>
                                        <a class="cc-dropdown-item" href="#" value="<?php echo $mcc['phone_code'] ?>">
                                            <div class="row m-0 p-1" style="font-size:80%;">
                                                <div class="col-7 p-1"><?php echo $mcc['country_name'] ?></div>
                                                <div class="col-4"><?php echo $mcc['phone_code'] ?></div>
                                            </div>
                                        </a>
                                        <?php }} ?>
                                    </div>
                                </div>
                                <div class="col-9"><input class="form-control" id="tMobile"/></div>
                            </div>
                        </div>
                    </div> 
                    <div class="row py-2">
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <label class="text-black-50">Travel date</label>
                            <input type="text" class="form-control" id="tvl_date" value=""/>
                        </div>
                        <div class="col-sm-12 col-md-12 col-lg-6">
                            <label class="text-black-50">Select Plan Code</label>
                            <div class="dropdown">
                                <button class="btn bg-white dropdown-toggle w-100 border" type="button" id="ddupc" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:90%;height:38px;">
                                   <?php
                                        if(count($upcList)){
                                            echo $upcList[0]['upc'];
                                        }else{
                                            echo "No plans";
                                        }
                                   ?>
                                </button>
                                <div class="dropdown-menu  w-100" aria-labelledby="dropdownMenuButton" style="overflow: scroll;max-height: 250px;">
                                    <?php if(count($upcList)){ 
                                        foreach($upcList as $upc){?>
                                    <a class="dropdown-item" href="#" value="<?php echo $upc['id'] ?>">
                                        <div class="row">
                                            <div class="col-9"><?php echo $upc['upc'] ?></div>
                                            <div class="col-3 text-center"><img src="<?php echo $upc['taLogo'];?>" height="25" class="mb-sm-2 px-3"></div>
                                        </div>
                                    </a>
                                    <?php }} ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row my-3">
                        <div class="col">
                        <div><button type="button" class="btn submit-btn stt-bg-primary mb-3" id="addSds" <?php if(!count($upcList)){echo "disabled";}?>>Submit</button></div>
                        <input type=hidden id="htbeId" value="<?php echo $userId; ?>"/>
                        <input type=hidden id="hrole" value="<?php echo $_SESSION['Laminas_Auth']->storage['tbe_role']; ?>"/>
                        </div>
                    </div>
                    <h6 class="font-weight-bold text-uppercase my-3">Remaining tourists count</h6>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <thead class="stt-bg-primary">
                            <tr>
                                <th class="text-center">Plan Code</th>
                                <th class="text-center">Count</th>
                            </tr>
                            <tbody>
                            <?php foreach($upcList as $upc){ ?>
                                <tr class="position-relative">
                                    <td class="text-center">
                                        <?php echo $upc['upc'] ?>
                                        <img src="<?php echo $upc['taLogo'];?>" height="30" class="mb-sm-2 px-3">
                                    </td>
                                    <td class="text-center"><?php echo $upc['tourists_count']; ?></td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>