<div class="container-fluid px-0 aboutus-banner mb-5">
    <div class="container h-100 d-flex align-items-center">
        <div class="user-page-name text-uppercase avant-md">
            Terms
        </div>
    </div>
</div>

<div class="container-fluid my-5">
    <div class="container privacy-container">
        <div class="bg-white border-radius-10 custom-shadow p-4">
            <h4>
                Terms
            </h4>

            <ol class="terms_list">
                <li> Please read these “Terms” carefully before using the Mobile Application  “Susri Tour Tales”, and the web site https://www.susritourtales.com,    which are  the "Services"  operated by our company Susri Tour Tales Pvt Ltd (STT).</li>

                <li> Your access to and use of our  Services is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users and others who access or use the Services of Susri Tour Tales Pvt Ltd  (STT).</li>

                <li> <b>By accessing or using the Service itself,  you are construed  to be bound by these Terms. If you disagree with any part of the terms then you are not expected to  access the Service.</b></li>

                <li class="mt-3"><b> Subscription </b>
                    <ol>
                        <li> If you wish to subscribe to STT either by on-line payment or using Subscription Password, you need to provide your identity, phone number and email id and State of residence  as specified by the system.  If you wish to register yourself as a Sponsor, you need to provide further details as specified.</li>

                        <li>  Refusal to submit any of the details will not entitle you to get our services. You need to comply with the procedures, payments and service conditions specified as relevant to the service sought.</li>

                        <li>  You cannot hold STT responsible for any technical snags in the channel, connectivity and at the phone end. While logging in, subscribing and downloading, all permissions needed by the system are to be accepted by you for accessing the service by STT.</li>

                        <li>  In case you are a Sponsor, you have the responsibility to do ethical business with your customers.  At no time, you can sell the “Subscription Password” for more than the prevailing price. If STT gets authentic proof of your cheating the customer with excess charges or with expired passwords, you are liable to be expelled as Sponsor.</li>

                        <li>  As an aspiring Subscriber, you need to be careful when purchasing the passwords from a Sponsor. Price and Validity of Password are two primary parameters you need to take care. It is better to complete the process of subscription in the presence of Sponsor.  STT shall not interfere in arbitrating the disputes between you and your sponsor.</li>

                        <li>  STT  will not hold any responsibility for the mis-use of passwords at Sponsor’s end or at Subscriber’s end. STT shall not be responsible for messing up the management  of passwords, loss of passwords or errors in selling them by Sponsor or his customers. Payments made once cannot be refunded.</li>
                    </ol>
                </li>

                <li class="mt-3"><b> Content</b>
                    <ol>
                        <li> All the text and audio content of the Tour Tales in all languages is proprietary of Susri Tour Tales Pvt Ltd and copying any part of it or whole in any form is violation of the copyrights and such acts are liable for legal action.</li>

                        <li> STT asserts that the compilation and the creation of the “tales” is the sole proprietary of STT with the information learnt from various sources. </li>

                        <li> The sources of information are very exhaustive and acknowledging every reference is impossible. STT respects all such acknowledged and unacknowledged  sources. STT does not entertain any issue on this aspect.</li>

                        <li> STT Pvt Ltd has total independence in selecting the places and languages for the tales as well as their order of  uploading into the app. Users can suggest their choices but cannot question it.</li>

                        <li> STT enjoys the right of expressing the facts and its own views about the monuments including the myths and legends existing in circulation. STT cannot be questioned on that.</li>

                        <li> The pictures and music presented in the app are obtained from licensed sources or from personally shot/played/permitted by  STT personnel. Any resemblance is only accidental and STT does not entertain any inquiries in this regard. It can be challenged if desired.</li>
                    </ol>
                </li>

                <li class="mt-3"><b> Changes</b>
                    <ol>
                        <li> STT Pvt Ltd  reserves  the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material,  we will try to provide at least 20 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</li>
                    </ol>
                <li class="mt-3"><b> Contact us if you have any questions about these terms on our e-mail.</b></li>
                </li>
            </ol>
        </div>
    </div>
</div>