<div class="container-fluid my-4">
    <div class="container">
        <div class="row custom-shadow bg-white ">
            <div class="col-12 col-sm-12 col-md-12 col-lg-8 mb-4 mb-lg-0 p-0">
                <div class="position-relative overflow-hidden">
                    <img src="<?php echo $this->basePath(); ?>/img/user/TWISTT-PIC.jpg" class="img-fluid">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <div class="p-4">
                    <div class="text-capitalize avant-md color-000 my-4">
                        Logins
                    </div>
                    <div class="mb-3">
                        <a href="twisttae" class="btn submit-btn text-white" role="button">TWISTT ENABLER Login</a>
                    </div>
                    <div class="mb-3">
                        <a href="twisttse" class="btn submit-btn text-white" role="button">STT-SE Login</a>
                    </div>
                    <div class="text-capitalize avant-md color-000 my-4">
                        Downloads
                    </div>
                    <div class="mb-3">
                        <a href="download.php?file=TWISTTOrder.pdf" target="_new" class="btn submit-btn text-white" role="button">TWISTT Order Form</a>
                    </div>
                    <div class="mb-3">
                        <a href="download.php?file=TWISTTConfirmation.pdf" target="_new" class="btn submit-btn text-white" role="button">TWISTT Order Confirmation</a>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="row custom-shadow bg-white my-3">
            <div class="col-12">
                <div class="p-4">
                    <div>
                        <p>Hi! Tour Agency ! Don’t allow your tourist to travel alone; give <span class="text-danger">“STT”</span> to <span class="text-danger">hear the story of the site before seeing its glory.</span></p>
                        <p><span class="text-danger">TWISTT</span> is the short duration subscription of STT for 15 days.</p>
                        <p><span class="text-danger">TWISTT</span> subscription can be enabled on the tourist’s mobile by any “Tour Agency” from this portal, just by TWO simple steps..</p>
                        <p>
                            <ul>
                                <li>Contact STT at twistt.stt@gmail.com and buy a bulk license of <strong>TWISTT</strong> for a large number of ‘subscriptions’ applying in the Order form template enclosed.</li>
                                <li>Log-in to your account from here and enter the ‘Android’ mobile number of the tourist and ‘starting date of the tour’.</li>
                            </ul>
                        </p>
                        <p>***</p>
                        <h6 class="text-info"><b>Who should buy the TWISTT bulk licenses ?</b></h6>
                        <p><b>“Agencies”</b> associated with Tourism like- <span class="text-danger">Indian Embassies and Cultural associations abroad, Tourism Departments of Central and State Governments, Indian &amp; Foreign Tour Agencies, Tour Operators, Travel Agencies, Tour Coordinators, Hoteliers and anyone interested to be a Freelance TWISTT Enabler</span> - can buy the bulk license for enabling “<b>TWISTT</b> Subscriptions”.</p>
                        <h6 class="text-info"><b>Useful Information for “Tour Agency”</b></h6>
                        <p>
                            <ul>
                                <li><b>“Agency”</b> can authorise if desired many of their booking agents also to log-in and enter the tourist phone numbers.</li>
                                <li><b>“Agency”</b> can monitor the count of the consumed licenses.</li>
                                <li><b>“Agency”</b> has to advise the tourist to install the STT App</li>
                                <li>Enabling of “subscription” will be done by STT Pvt Ltd, 3 days prior to the date of travel.</li>
                                <li><b>“Agency”</b> <span class="text-danger">Name will also be displayed on the App of the tourist during TWISTT subscription period.</span></li>
                                <li>The enquiry, invoice, order, payment and confirmation - are all to be done off-line as on now. Will be made on-line along with iOS version of the App.</li>
                            </ul>
                        </p>
                        <p>***</p>
                        <h6 class="text-info"><b>Information for prospective STT-Sales Executives</b></h6>
                        <p>
                            <ul>
                                <li>STT-SE has to contact STT Pvt Ltd by mail on twistt.stt@gmail.com to get registered as STT-SE subjected to approval by STT Pvt Ltd.</li>
                                <li>STT-SE’s can log-in from here and track the contributions made by them and commission earned.</li>
                                <li>STT-SE has also to log-in with Mobile number as User-Id.</li>
                                <li>STT-SE has to ensure that his/her mobile number is entered in the Order Confirmation form by Tour Agency/ TWISTT Enablers.</li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath();?>/js/faq.js"></script>