<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/twistt.css">
<script src="<?php echo $this->basePath(); ?>/js/admin/twistt-forgot-password.js"></script>
<div class="container-fluid my-5">
    <div class="container"> 
        <div class="content bg-white custom-shadow p-4 color-333"> 
            <div class="bg-light border-radius-10 custom-shadow p-4 color-333">
                <div class="text-uppercase avant-md pb-3">
                    <h5><?php echo "Forgot Password"; ?></h5>
                </div>
                <div>
                  <div id="divSendOtp" class="row">
                    <div class="col-12 mb-4">
                      <label class="text-black-50">Please enter your registered mobile number / email id to recieve otp in order to reset your password</label>
                      <div class="row">
                        <div class="col-12 mb-3">
                            <input type="text" class="col-lg-6 form-control d-inline m-2" id="Y3VycmVudFBhc3N3b3Jk" />
                            <button type="button" class="btn submit-btn text-white d-inline m-2" id="sendOtp">Send Otp</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div id="divVerifyOtp" class="row d-none">
                  <div class="col-12 mb-4">
                    <div class="row">
                        <div class="col-sm-12 text-left">
                          <input type="text" class="col-lg-6 form-control d-inline m-2" id="txtOtp" />
                          <button type="button" class="btn submit-btn text-white d-inline m-2" id="verifyOtp">Verify Otp</button>
                        </div>
                    </div>
                  </div>
                </div>
                <div id="divPwdReset" class="d-none">
                    <div class="row">
                    <div class="col-12 col-lg-10">
                        <div class="row adding-form">
                            <div class="col-12 col-md-6 mb-4">
                                <div class="row">
                                    <div class="col-12 mb-3"><label class="text-black-50">New Password</label>
                                        <input type="password" class="form-control" id="bmV3UGFzc3dvcmQ"/>
                                    </div>
                                    <div class="col-12"><label class="text-black-50">Confirm Password</label>
                                        <input type="password" class="form-control" id="Y29uZmlybVBhc3N3b3Jk"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="mt-3">
                    <div class="row">
                        <div class="col-sm-11 text-left">
                            <button type="button" class="btn submit-btn text-white" id="Y2hhbmdlUGFzc3dvcmQ">Submit</button>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>