<div class="container-fluid my-4">
    <div class="container">
        <div class="row custom-shadow bg-white ">
            <div class="col-12 col-sm-12 col-md-12 col-lg-8 mb-4 mb-lg-0 p-0">
                <div class="position-relative overflow-hidden">
                    <img src="<?php echo $this->basePath(); ?>/img/user/TWISTT-PIC.jpg" class="img-fluid">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-4">
                <div class="p-4">
                    <div class="text-capitalize avant-md color-000 my-4">
                        Logins
                    </div>
                    <div class="mb-3">
                        <a href="twistt/executive/login" class="btn submit-btn text-white" role="button">TWISTT Executive Login</a>
                    </div>
                    <div class="mb-3">
                        <a href="twistt/enabler/login" class="btn submit-btn text-white" role="button">TWISTT Enabler Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>