<div class="container-fluid py-5>
    <div class=" container">
    <div class="row">
        <div class="col-md-12 my-5 mx-5">
            <img src="/img/user/logo.png" class="img-fluid" alt="logo">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 my-5 text-center wip-block">
            <p class="under-construction">This website is under construction</p>
        </div>
    </div>
</div>
</div>
<div class="wip-bg">