<?php
if (!isset($role)) {
    $role = null;
}
if (!isset($navigation)) {
    $navigation = null;
}
?>
<link rel="stylesheet" href="<?php echo $this->basePath() . '/css/light-bootstrap-dashboard.css' ?>">
<div class="logo d-flex justify-content-center align-items-center m-0">
    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
        <div>
            <img src="<?php echo $this->basePath('img/logo.png') ?>" alt="Susri" class="img-fluid logo-image">
        </div>
    </a>
</div>
<div class="side-menu position-absolute mCustomScrollbar " data-mcs-theme="light" id="content-3">
    <nav class="navbar-side qregular <?php echo $this->layout()->page; ?>" id="">
        <ul class="nav">
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::App_parameters ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/parameters">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            App Parameters
                        </span>
                    </div>
                </a>
            </li>
            <li class="<?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Users ? 'active' : '')) ?>">
                <a href="#userCollapse" data-bs-toggle="collapse" class="custom-collapse <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Users ? 'custom-collapse-open' : '')) ?>">
                    <div class="d-flex align-items-center justify-content-between">
                        <span class="text-capitalize">
                            Users
                        </span>
                        <i class="fas <?php echo (isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Users ? 'fa-angle-right' : 'fa-angle-right') ?>"></i>
                    </div>
                </a>
            </li>
            <div class="collapse w-100 <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Users ? 'show' : '')) ?>" id="userCollapse">
                <ul class="list-unstyled bg-secondary">
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Users_dashboard ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/user-dashboard">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Users Dashboard
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::All_Downloads ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/downloads">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    All Downloads
                                </span>
                            </div>
                        </a>

                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Subscription_plans ? 'active' : '');
                                ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/subscription-plans">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Subscription Plans
                                </span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <li class="<?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Tales ? 'active' : '')) ?>">
                <a href="#taleCollapse" data-bs-toggle="collapse" class="custom-collapse <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Tales ? 'custom-collapse-open' : '')) ?>">
                    <div class="d-flex align-items-center justify-content-between">
                        <span class="text-capitalize">
                            Tales
                        </span>
                        <i class="fas <?php echo (isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Tales ? 'fa-angle-right' : 'fa-angle-right') ?>"></i>
                    </div>
                </a>
            </li>
            <div class="collapse w-100 <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Tales ? 'show' : '')) ?>" id="taleCollapse">
                <ul class="list-unstyled bg-secondary">
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Languages ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/languages">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Languages
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Countries ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/countries">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Countries
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::States ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/states">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    States
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Cities ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/cities">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Cities
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Places ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/places">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Places
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::IT ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/india-tour-list">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    India Tales
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::WT ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/world-tour-list">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    World Tales
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::FT ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/free-tour-list">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Free Tales
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Bunched_Tales ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/bunched-tour-list">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Bunched Tales
                                </span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <li class="<?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::TWISTT_ENABLERS ? 'active' : '')) ?>">
                <a href="#teCollapse" data-bs-toggle="collapse" class="custom-collapse <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::TWISTT_ENABLERS ? 'custom-collapse-open' : '')) ?>">
                    <div class="d-flex align-items-center justify-content-between">
                        <span class="text-capitalize">
                            TWISTT Enablers
                        </span>
                        <i class="fas <?php echo (isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::TWISTT_ENABLERS ? 'fa-angle-right' : 'fa-angle-right') ?>"></i>
                    </div>
                </a>
            </li>
            <div class="collapse w-100 <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::TWISTT_ENABLERS ? 'show' : '')) ?>" id="teCollapse">
                <ul class="list-unstyled bg-secondary">
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::TE_Plans ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/te-plans">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    TE Plans
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::TE_Profiles ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/te-profiles">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    TE Profiles
                                </span>
                            </div>
                        </a>

                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::TE_Performance ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/te-performance">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    TE Performance
                                </span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::TEx_Dashboard ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/tex-dashboard">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            TEx Dashboard
                        </span>
                    </div>
                </a>
            </li>
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::Statistics ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/statistics">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            Statistics
                        </span>
                    </div>
                </a>
            </li>
            <li class="<?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Receipts_Expenditure ? 'active' : '')) ?>">
                <a href="#reCollapse" data-bs-toggle="collapse" class="custom-collapse <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Receipts_Expenditure ? 'custom-collapse-open' : '')) ?>">
                    <div class="d-flex align-items-center justify-content-between">
                        <span class="text-capitalize">
                            Receipts & Expenditure
                        </span>
                        <i class="fas <?php echo (isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Receipts_Expenditure ? 'fa-angle-right' : 'fa-angle-right') ?>"></i>
                    </div>
                </a>
            </li>
            <div class="collapse w-100 <?php echo ((isset($mainActiveTab) && $mainActiveTab == \Application\Constants\Constants::Receipts_Expenditure ? 'show' : '')) ?>" id="reCollapse">
                <ul class="list-unstyled bg-secondary">
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Receipts ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/receipts">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Receipts
                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="<?php echo ($activeTab == \Application\Constants\Constants::Expenditure_on_Commission ? 'active' : ''); ?>">
                        <a href="<?php echo $this->basePath(); ?>/a_dMin/expenditure">
                            <div class="d-flex align-items-center justify-content-between">
                                <span class="text-capitalize">
                                    Expenditure on Commission
                                </span>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::Ads ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/ads">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            Advertisements
                        </span>
                    </div>
                </a>
            </li>
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::Video_links ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/videos">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            Video links
                        </span>
                    </div>
                </a>
            </li>
            <li class="<?php echo ($activeTab == \Application\Constants\Constants::Change_Password ? 'active' : '') ?>">
                <a href="<?php echo $this->basePath(); ?>/a_dMin/change-password">
                    <div class="d-flex align-items-center">
                        <span class="text-capitalize">
                            Change Password
                        </span>
                    </div>
                </a>
            </li>
        </ul>
    </nav>
</div>