<script type="text/javascript" src="https://checkout.razorpay.com/v1/razorpay.js"></script>

<form method="POST" action="https://api.razorpay.com/v1/checkout/embedded" name="payment">
    <input type="hidden" name="key_id" value="<?php echo \Application\Handler\Razorpay::keyId; ?>">
    <input type="hidden" name="order_id" value="<?php echo $razorpayOrderId; ?>">
    <input type="hidden" name="name" value="Susri tour tales">
    <input type="hidden" name="description" value="Susri tour tales">
    <input type="hidden" name="image" value="<?php echo $url; ?>/img/logo.png">
    <input type="hidden" name="prefill[contact]" value="<?php echo $userDetails['mobile']; ?>">
    <input type="hidden" name="prefill[email]" value="<?php echo $userDetails['email']; ?>">

    <input type="hidden" name="callback_url" value="<?php echo $url; ?>/application/payment-callback">
    <input type="hidden" name="cancel_url" value="<?php echo $url; ?>/application/payment-cancel">
</form>
<script>
    var razorpay = new Razorpay({  key: "<?php echo \Application\Handler\Razorpay::keyId; ?>" });
    razorpay.checkPaymentAdapter('gpay')
        .then(() => {
            // Google Pay is available, show the payment option
            var paymentData = {
                amount: 100000, //pass in paise (amount: 100000 equals ₹1000)
                method: 'upi',
                contact: "<?php echo $userDetails['mobile']; ?>",  // customer's mobile number
                email:"<?php echo $userDetails['email']; ?>",  //customer's email address
                order_id:"<?php echo $razorpayOrderId; ?>" //..  and other payment parameters, as usual
            };
            razorpay.createPayment(paymentData, { gpay: true }).on('payment.success', function(response) {
                // response.razorpay_payment_id
                // response.razorpay_order_id
            })
                .on('payment.error', function(error) {
                    // display error to customer
                })
        })
        .catch((e) => {
            document.payment.submit();
             /*  console.log(e);
            alert("not avalibale");
            console.log("not avaliable");*/
            // Google Pay is unavailable
        });
</script>